### ISSUE TITLE
[spec] Missing angle brackets in a example of `valueRecordDef`

### ISSUE THREAD

**Issue by mashabow** [adobe-type-tools/afdko#100]
In [section 2.e.v](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#2.e.v "OpenType Feature File Specification | Adobe Developer Connection") of the OpenType Feature File Specification, there is a malformed example:

```
valueRecordDef 0 0 20 0 SECOND_KERN;
```

It should have angle brackets like this:

```
valueRecordDef <0 0 20 0> SECOND_KERN;
```

**Comment by readroberts** [comment]
Fixed in spec version 1.19
