### ISSUE TITLE
"pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available."

### ISSUE THREAD

**Issue by andreas-roehler** [adobe-type-tools/afdko#1001]

**Comment by josh-hadley** [comment]
Hi there, as far as I can tell from the information provided, this is not anything to do with AFDKO specifically and sounds like a general Python issue. As such, I am closing the issue. If you believe there is something specific to AFDKO, please provide additional details here and we'll reconsider.

In the meantime, [this question on StackOverflow](https://stackoverflow.com/questions/45954528/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-in) might help.
