### ISSUE TITLE
[spec] MarkAttachmentType accepts numeric value

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#1004]
`MarkAttachmentType` is [documented](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2.f.ii) to accept class names, but it seems that makeotf accepts also numeric values but this is not documented.

I suppose the numbers are for GDEF classes, but there is no way to define these independently. Is this what the unused `MarkAttachClass` was meant for (#994)?

**Comment by khaledhosny** [comment]
Is this still the case after the ANTLR v4 port?

**Comment by iterumllc** [comment]
Direct specification of GDEF class indexes was briefly part of the spec around v1.8 before being replaced by the present mechanism. The number option was presumably left in the featgram.g parser either for testing or backwards compatibility.

It appears that neither the feaLib nor the FontForge parser accepts the number. Therefore after some discussion the plan is to leave it out and see if its absence raises any issues, in which case it may (or may not -- depending on the case for it) be added back in with a deprecation warning.

It seems likely that this issue can be closed now but I'll leave that up to your judgement.
