### ISSUE TITLE
script in named lookup blocks

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#101]
In [section 4.e](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#4.e), the OpenType Feature File specification writes: “You may not use the script or language keywords within a named lookup block.” However, makeotf v2.0.90 accepts the following input:
```
languagesystem DFLT dflt;
feature test {
    lookup L {
        script grek;
        pos T 100;
    } L;
} test;
```

Should makeotf reject the above file, because it is in violation of the current spec? Or should the spec be changed, and say that script/language _are_ permitted inside named lookup blocks in case they happen to be placed inside a feature block?

Since the construct it getting used in existing feature files (we’ve seen such feature files getting emitted by the Glyphs.app font editor), it might be safer to change the spec. On the other hand, there might be an advantage to keeping the spec clean — it’s already a pretty complex language, and allowing exceptions to general rules won’t make it any easier.

**Comment by marekjez86** [comment]
Any feedback or suggestion on this mismatch between the spec and makeotf reality?

**Comment by readroberts** [comment]
There is some reason to prefer to not use the script/language keywords within a named lookup, but not enough to break existing files.

I would modify the spec to note that script and language keywords that are applied with in definition of a named lookup will not be applied when the names lookup is referenced, and that is it is better practice to apply  script and language keywords outside a named lookup, in order to avoid possible confusion about whether the script and language statements would be applied when the named lookup is referenced.

**Comment by behdad** [comment]
So, what *is* the intended semantics of this, when the lookup is referenced externally?

**Comment by marekjez86** [comment]
Are script/language keywords within a named lookup treated as if they were comments (i.e., not flagged as errors but ignored)?

**Comment by readroberts** [comment]
The current (and intended) case in makeotf is that script and language statements affect only the enclosing feature, and are not attached to lookups defined within a feature. As a result, script and language statements used within a named lookup have no effect on other features which reference the named lookup. I find this confusing and difficult to explain, but am reluctant to break existing font data. After thinking a bit more, I propose leaving the wording as is, and just add a warning to makeotf when script and language statements are used within a named lookup.

**Comment by readroberts** [comment]
In spec version 1.19, added statement that script and language keywords may not not be used within stand-alone lookups. Have not yet added warning to makeotfexe.

**Comment by readroberts** [comment]
Fixed wording in makeotfexe.
