### ISSUE TITLE
About the linespace

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#1047]
Why is there a blank space (blue rectangle) in word 2010?Not in word 2016.

![help](https://user-images.githubusercontent.com/5868202/70385135-1b45ce00-19c6-11ea-9e16-d04def6e542d.png)

How do I set the parameters in OS2 table?
table OS/2{
     FSType 2;
    TypoAscender  1589;
    TypoDescender  -674;
    TypoLineGap  0;
    winAscent  1487;
    winDescent  574;
    include(..\Rule_GLT\GLT_OS2_Table_Common.txt);
}OS/2;

table vhea{
    VertTypoAscender  1489;
    VertTypoDescender  -574;
    VertTypoLineGap  0;
}vhea;

**Comment by josh-hadley** [comment]
Hi there,

It looks like you have the correct syntax for setting OS/2 table parameters. Just be sure your `include` directive is pointing to the right location (check the [feature file specification section on includes](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#3)).

I will close this issue now. Please re-open or start a new issue if you encounter something that is an issue with one of the AFDKO tools related to this.

**Comment by readroberts** [comment]
I have a vague memory that older versions of MS Word 2010 did have bugs with showing the return character as a space or notdef characters under some circumstances. I see that the character spacing between the two versions is quite different as well. If you really want to investigate bugs in an old version of MS Word, I recommend asking on a typography web site like https://typedrawers.com/ if anyone remembers issues with Word 2010.
