### ISSUE TITLE
[tx]operand stack underflow <gid01101>

### ISSUE THREAD

**Issue by hardik05** [adobe-type-tools/afdko#1048]
i was testing something and found that while processing attached file, i am getting operand stack underflow <gid01101> message. not sure if its a bug or not but submitting for review.
PFA cff file attached.
[test.zip](https://github.com/adobe-type-tools/afdko/files/3942884/test.zip)

**Comment by cjchapman** [comment]
@hardik05 That is definitely a bad font. It fails both OT-Sanitizer and Font Validator.

Here are links to the GitHub repos for those tools if you'd like to try them yourself:
https://github.com/khaledhosny/ots
https://github.com/HinTak/Font-Validator/

Note that the convention is for an SFNT file containing a `CFF2` table to have the extension `.otf`, your file has the extension `.cff` which is normally used for a raw CFF table (i.e. a CFF font that is not inside of an SFNT wrapper).

**Comment by cjchapman** [comment]
Here's some info from Font Validator's report -- the fact that several tables, including the `CFF2` table, have bad checksums is enough to dissuade me from any further analysis of the font:
![Screen Shot 2019-12-10 at 7 53 39 AM](https://user-images.githubusercontent.com/17747678/70545298-34fc2800-1b22-11ea-9460-40edd8fd9404.png)

**Comment by cjchapman** [comment]
@hardik05 Just to be clear: I've closed this issue because the font is clearly bad and `tx` is reporting an issue and exiting gracefully (i.e. not crashing). I'm guessing this font was fuzzed. If you encounter a crash in an AFDKO tool while working with a font, even a fuzzed or otherwise bad font, please let us know.

**Comment by hardik05** [comment]
sure thanks @cjchapman for looking at it. i will submit another issue if i encounter any crashes.
