### ISSUE TITLE
[spec] Syntax of ignore sub statement is incomplete

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#105]
In [section 5.f.ii of the OpenType Feature File specification](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#5.f.ii), the syntax of the `ignore sub` statement is currently defined like this:
```
ignore substitute <backtrack glyph sequence>*
            <marked glyph sequence>
            <lookahead glyph sequence>*;
```

However, later down in example 3, the statement then gets illustrated with an example that does not conform to this syntax:
```
ignore substitute @LETTER a' n' d', a' n' d' @LETTER;
```

Also, makeotf seems to accept a comma-separated list of backtrack/input/lookahead triples. Therefore, the syntax specification for the `ignore sub` statement should be changed to reflect reality.

**Comment by readroberts** [comment]
Added wording to spec to clarify that commas separated clauses after 'ignore sub' consist of complete independent match sequences, each with "<backtrack sequence> <input sequence> <look ahead sequence>".
