### ISSUE TITLE
[tx] How to subroutinize CFF2 font?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/afdko#1068]
I have a psautohinted CFF2 font made with an up-to-date ufo2ft/fontTools and tried `tx -cff2 +S myfont.otf > myfontS.otf` from afdko 3.1.0. The resulting file is gunk that even tx deems invalid. How do I do this :grin:

**Comment by cjchapman** [comment]
@madig The resulting file is only a `CFF2` table, not a full `SFNT` file.  You can use `sfntedit` to put that `CFF2` table into your `SFNT` file.

**Comment by cjchapman** [comment]
@madig For example:
```
cp myfont.otf mynewfont.otf
tx -cff2 +S myfont.otf > mytable.CFF2
sfntedit -a CFF2=mytable.CFF2 mynewfont.otf 
 ```

**Comment by madig** [comment]
Thanks! I petition that this is added to the `-cff2` help text.

This curiously destroys spacing though (left: original, right: tx'd):
![Bildschirmfoto vom 2019-12-18 23-12-20](https://user-images.githubusercontent.com/380829/71131210-f0405300-21eb-11ea-96d1-c16926ecdabe.png)

This is solved by `+b`. Maybe that option should be on by default?

**Comment by cjchapman** [comment]
@madig Would you please create a new GitHub issue for the "destroyed spacing" problem you observed?

**Comment by cjchapman** [comment]
@madig Also, I've started a [How To](How-To) area in the wiki and added this example (with the `+b`).
