### ISSUE TITLE
[spec] Backtrack and lookahead missing from ignore pos syntax definition

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#107]
Currently, [section 6.h.vi](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#6.h.vi) of the OpenType Feature File Syntax specification defines the syntax of the `ignore pos` statement as follows:
```
ignore position <marked glyph sequence> (, <marked glyph sequence>)*;
```

However, backtrack and lookahead glyph sequences should be allowed as well.

**Comment by readroberts** [comment]
These are allowed. Updated feature spec to clarify usage.
