### ISSUE TITLE
COLR/CPAL - Feature file format?

### ISSUE THREAD

**Issue by ctrlcctrlv** [adobe-type-tools/afdko#1073]
Hello&mdash;

I'm writing from the FontForge project, where we're looking to implement COLR/CPAL fonts.

I was trying to find out if there's an accepted standard for defining palettes in Adobe feature files? Or defining the colors of each contour in a glyph by index?

Does anyone know? Or is this not seen as something that should be in a feature file?

Best,
Fred Brennan

**Comment by josh-hadley** [comment]
Hi Fred,

There's not currently any COLR/CPAL support in feature file syntax, nor do we have any plans to add such support.
