### ISSUE TITLE
[makeotfexe] Bad font built when feature file has multiple languagesystems and feature parameters

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#1080]
Commit https://github.com/adobe-type-tools/afdko/commit/5624e02b58390e605639c3633025cd73cd418da7  added a serious bug that causes makeotfexe to build a bad font when the feature file has both multiple languagesystems and feature parameters. The result of the bug is that in the layout table with a feature parameter, all lookups are suppressed.

**Comment by josh-hadley** [comment]
If you're affected by this bug, temporary workaround is to revert to [AFDKO version 3.0.1](https://github.com/adobe-type-tools/afdko/releases/tag/3.1.0) or earlier, until we have an updated release that fixes the issue.

**Comment by benkiel** [comment]
@readroberts could you explain further what you mean by feature parameters? I’m sure it’s obvious, but I’m drawing a blank

**Comment by readroberts** [comment]
Feature parameters are blocks of data referenced by the FeatParam field in a GSUB/GPOS Feature table. Current features which use this are optical size ('size'), stylistic names ('ssXX'), and Character Variant features ('cvXX'). The result of the bug is that in the layout table with a feature parameter, all lookups are suppressed.

**Comment by josh-hadley** [comment]
@benkiel See https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#4.c for more info on feature parameters.

**Comment by josh-hadley** [comment]
fixed by #1081

**Comment by benkiel** [comment]
@readroberts @josh-hadley, thank you. this indeed caught me: I was thinking you may be meaning fonts with stylistic set names, but wasn't 100% sure. Thank you for taking the time to confirm
