### ISSUE TITLE
Update buildcff2vf.py to catch changed exceptions

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#1088]
https://github.com/fonttools/fonttools/pull/1821 changed exception handling in fonttools that could break `buildcff2vf.py`'s handling scheme. Investigate and update `buildcff2vf.py` as needed.

**Comment by anthrotype** [comment]
nikolaus added an alias to the old exception name in varLib.cff so there should not be any breakage

**Comment by josh-hadley** [comment]
I agree, but I'm going to check confirm anyway.

**Comment by josh-hadley** [comment]
All `buildcff2vf` tests pass with fonttools https://github.com/fonttools/fonttools/commit/4be6aaf71cab6ace115c7bdec9ed39d0f66565b5. I will keep this open as a reminder to clean up and remove `buildcff2vf.py`'s redefinition of `MergeTypeError` after fonttools is released with the changes from that PR.
