### ISSUE TITLE
[spec] State default lookupflag in named lookup blocks

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#109]
Currently, [section 4.d](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#4.d) of the OpenType Feature File Specification says:
> The lookupflag attribute defaults to 0 at the start of a feature block.

Proposed change:
> The lookupflag attribute defaults to 0 at the start of a feature or named lookup block.

cc @khaledhosny who discovered that this is currently unspecified.

**Comment by readroberts** [comment]
Fixed in feature file spec 1.19.
