### ISSUE TITLE
[makeotf] hhea caretOffset: what generates it?

### ISSUE THREAD

**Issue by rbmntjs** [adobe-type-tools/afdko#1095]
My default makeOTF production* makes files that, according to ot-sanitiser, are setting a ‘bad’ value† for the hhea caretOffset. I’ve not set the caretOffset value in my hhea table, nor in the UFO.

1. Why is seemingly any value other than 0 wrong?
2. How does makeOTF decide on the value it sets?

*: `makeotf -nshw -f "$font_ufo" -gf GlyphOrderAndAliasDB -osv 4 -r -ga -o "$font_dir/$ps_name$date.otf" -ff "$font_dir/features"`
†: `WARNING: hhea: bad caret offset: 9`

**Comment by frankrolf** [comment]
Not an answer to your immediate question, just a remark:

- if you use the default name for the GlyphOrderAndAliasDB, there is no need to use the `-gf` option.
- if you use -r for release mode, the `-ga` option is automatically applied.

Have you tried using a different value for the OS/2 table? Perhaps that’ll make the error go away?
What kinds of overrides are in your features file?

**Comment by rbmntjs** [comment]
These are very valid remarks – artefacts of me slowly adjusting my build script from beta to release files and not knowing the tools when I started… Easy fixes, thanks.

Do you mean to simply set a 0 for the caretOffset value? Should it really be 0 for italic styles? Or do I need to calculate the right offsets, and if so, what are those, because no single value seemingly gets approved by ots. Otherwise I only set Ascender, Descender and LineGap in the hhea table.

**Comment by frankrolf** [comment]
How do you run the sanitizer exactly? I tried to reproduce your error locally (using Source Serif Italic), but can’t see any such output.

**Comment by rbmntjs** [comment]
I’m running it as part of `fontbakery check-universal`, where it runs, more specifically, `ots-sanitize`. But I’m really too unfamiliar with this tool to understand where to look.

And generally, I _am_ quite curious how makeOTF decides on the caretOffset value.

**Comment by rbmntjs** [comment]
Oh, also: I just built the font with a CaretOffset value in my hhea feature file and it still wrote generated values into the final font, which ots-sanitize reports on.

**Comment by frankrolf** [comment]
I made a little test. It may well be that `ot-sanitize` does not accept any CaretOffset beyond 0.
If you run the attached script in the same directory as the dummy UFO, you’ll see that ot-sanitize complains about any value other than 0.

Maybe @khaledhosny knows more?

```python
import os
import shutil
from fontParts.fontshell import RFont


feature_text = '''\
table hhea {{
    CaretOffset {};
    Ascender 800;
    Descender 200;
    LineGap 200;
}} hhea;
'''


for i in range(-10, 10, 1):
    print(f'caret offset {i}')
    dir_name = f'caret{i}'
    if os.path.exists(dir_name):
        shutil.rmtree(dir_name)
    os.mkdir(dir_name)
    ufo_file = os.path.join(dir_name, 'font.ufo')
    fea_file = os.path.join(dir_name, 'features.fea')
    shutil.copytree('dummy.ufo', ufo_file)
    f = RFont(ufo_file)
    f.info.familyName = 'CaretOffset'
    f.info.styleName = str(i)
    ps_name = f.info.familyName + '-' + str(i)
    f.info.postscriptFontName = ps_name
    f.save()
    with open(fea_file, 'w') as ff:
        ff.write(feature_text.format(i))
    os.chdir(dir_name)
    os.system('makeotf -r > /dev/null')  # we don’t want output from makeotf
    os.system(f'ots-sanitize {ps_name}.otf')
    os.chdir('..')
    print()

```

[dummy ufo + script.zip](https://github.com/adobe-type-tools/afdko/files/4236531/dummy.ufo.%2B.script.zip)

**Comment by cjchapman** [comment]
Here's the logic that OTS is using:
```C++
  // if the font is non-slanted, caret_offset should be zero.
  if (!(head->mac_style & 2) &&
      (this->caret_offset != 0)) {
    Warning("bad caret offset: %d", this->caret_offset);
    this->caret_offset = 0;
  }
```

Source:
https://github.com/khaledhosny/ots/blob/968e5f98ded4b90105ce78724e7af6940702b84f/src/metrics.cc#L52-L57

**Comment by rbmntjs** [comment]
That logic makes sense to me. That just leaves me with the other question: if makeOTF sets the caret offset automatically (which for me it does despite a 0 in my hhea table, let’s ignore that for now), why would it not also set the slant appropriately?

**Comment by benkiel** [comment]
Dumb question: do you have the italic angle set in your ufo?

**Comment by rbmntjs** [comment]
It’s a fair question, and yes, I do :) I managed to set the offset value to 0, and it‘s clear that makeOTF _does_ generate the rise and run values now. I’m running a final test here to see if caching was causing trouble, and if it now will validate the caret values.

**Comment by rbmntjs** [comment]
Yeah, so: I have an italic angle, makeOTF generates a rise, run, and offset – but ot-sanitize gives the warning. What is the `mac_style` value in @cjchapman’s snippet, and why is that wrong in my case?

**Comment by benkiel** [comment]
@rbmntjs Got it, you need to set the bit to say "hey, this is italic" for the OTS to be happy. That's the bit that controls style linking, and in you UFO it should be `styleMapStyleName` set to `italic` — I think (at least, that's how the UFO Spec has it, so that should work).

The way I do it, assuming that you are using makeOTF to build things, is to set `IsItalicStyle true` in the `fontinfo` file.

**Comment by twardoch** [comment]
The coupling of macStyle with the italic angle is unreasonable. macStyle controls style linking. The caret parameters control the shape of text cursor and selection, and should reflect the actual design. A sloped single-style roman or a script font should have macStyle Regular, but should have caret parameters that reflect the design. 

ots is faulty here.

**Comment by josh-hadley** [comment]
I agree with @twardoch on OTS's coupling of these two items; it should be perfectly valid to have a non-italic face with non-zero caretOffset. Might be interesting to see how FontBakery is handling this.

As to AFDKO and the question asked re: `hhea.caretOffset`, I believe that is now answered and resolved, so I will now close this question. @rbmntjs please re-open if there are remaining questions or AFDKO-specific issues to resolve.
