### ISSUE TITLE
makeinstancesufo doesn't remove overlap

### ISSUE THREAD

**Issue by jansindl3r** [adobe-type-tools/afdko#1100]
`afdko==3.2.0`
Result of running `makeinstancesufo`
<img width="486" alt="Screenshot 2020-03-14 at 01 23 22" src="https://user-images.githubusercontent.com/44162266/76670747-80472c00-6592-11ea-94f9-dbfc6d4f2703.png">

**Comment by frankrolf** [comment]
What should be the result? Bottom triangle removed?
Can you share the .glif file here?

**Comment by jansindl3r** [comment]
yes, and the top one too. I guess if there is optional argument to not remove overlaps, it should overlap it by default.
```
-c, --no-remove-overlap do NOT remove the instances' outline overlaps
```
From what I have looked, `makeotf` doesn't have such function, right?
[A_.glif.zip](https://github.com/adobe-type-tools/afdko/files/4332584/A_.glif.zip)

**Comment by frankrolf** [comment]
`makeotf` itself has no overlap removal – if you want to try just removing overlaps, use `checkoutlinesufo`.
I’ve tried that, and it seems to work (see attached):
[oplatky.ufo.zip](https://github.com/adobe-type-tools/afdko/files/4332634/oplatky.ufo.zip)

One question – how is the interpolation created? Are you using float coordinates?
Another question – please note the processed glyph will be found in the layer `glyphs.com.adobe.type.processedglyphs`, unless you ask checkoutlinesufo to process the foreground layer explicitly (which I think is not possible using `makeinstancesufo`)

Hope this helps!

**Comment by jansindl3r** [comment]
Alright, thanks! Can I ask? Now I see that it is in the background (the interpolated instance – sorry I forgot about the layering by AFDKO), why `makeotf` doesn't use that layer by default, when it is there? I have exported .otfs with the overlap.

`makeotf` claims ```-f <input font>     Specify input font path. Default is to search
                    for 'font.ufo, 'font.pfa', and cidfont.ps, all in the
                    current directory.
                    When a UFO file is specified, makeotf will prefer glyphs
                    from the glyphs.com.adobe.type.processedglyphs layer, which
                    is created by checkoutlinesufo and/or autohint tools.```

in my ufo I have indeed a layer without overlaps after running `makeinstancesufo` called `glyphs.com.adobe.type.processedglyphs` which is not used.

**Comment by frankrolf** [comment]
Make sure all OTFs are deleted, then just try building the instances again, and make the OTFs again. Sometimes, there’s just a caching issue, which makes it look like overlaps are present.

You should really attend a FDK workshop one day! 😉

**Comment by jansindl3r** [comment]
hmmm, interesting. I don't understand how could have that happened. Let's close it and if I will be able to track it more properly and see the issue again, I will get back.

I have actually attended one, but the teacher didn't explain this properly so I look like I haven't been to any. 🤓

**Comment by frankrolf** [comment]
🤣
