### ISSUE TITLE
pip installs old ufoProcessor

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1102]
From a discussion with @typemytype 

```
ERROR: afdko 3.2.0 has requirement ufoProcessor<=1.0.6,>=1.0.5, but you'll have ufoprocessor 1.8 which is incompatible.
```
ufoProcessor’s versioning semantics have changed from three to two digits: `1.0.5` → `1.0.6` → `1.7` → `1.8`

Is there a reason the afdko is insisting on an older version?

**Comment by typemytype** [comment]
This will become a real problem soon: http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html

**Comment by josh-hadley** [comment]
[This ufoProcessor bug](https://github.com/LettError/ufoProcessor/issues/29) is (and has been) blocking. Should be an easy fix.

**Comment by LettError** [comment]
I think the change in UFOprocessor's versioning semantics was a dumb typo and oversight on my part. I named the tag "1.08" rather than "1.0.8". 

Also I had to post a fix, so the newest is now "1.0.9"

How to make changes to Pypi? the 1.8 and 1.7 releases should be removed.
https://pypi.org/project/ufoProcessor/#history

**Comment by frankrolf** [comment]
https://stackoverflow.com/questions/20403387/how-to-remove-a-package-from-pypi

**Comment by LettError** [comment]
Yes thanks. Maybe @miguelsousa knows where the mail for the `letterror-ci` account goes to? (not to me)

**Comment by miguelsousa** [comment]
@LettError I'm receiving the password reset emails. I'd like to understand what your plans are. On PyPI the version numbering can only go up, and once you delete a release there is no way to reinstate it.

**Comment by miguelsousa** [comment]
PyPI is back on track https://pypi.org/project/ufoProcessor/1.9.0/

**Comment by josh-hadley** [comment]
`requirements.txt` has been updated with `ufoProcessor==1.9.0` (and other updates) and we now have PyUp functional again to catch future updates to dependencies. An upcoming AFDKO release will be issued soon with these updates.

**Comment by typemytype** [comment]
thanks!
