### ISSUE TITLE
I cannot install afdko because installation of psautohint failed.

### ISSUE THREAD

**Issue by BornForFever** [adobe-type-tools/afdko#1103]
Python: 3.8.1 64-bit
OS: Windows 10

this is the log:
```
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python38\python.exe' 'C:\Users\ywt\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\ywt\AppData\Local\Temp\tmp7c7o0kz9'
       cwd: C:\Users\ywt\AppData\Local\Temp\pip-install-7usa1164\psautohint
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\autohint.py -> build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\fdTools.py -> build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\otfFont.py -> build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\ufoFont.py -> build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\__init__.py -> build\lib.win-amd64-3.8\psautohint
  copying python\psautohint\__main__.py -> build\lib.win-amd64-3.8\psautohint
  running build_clib
  building 'psautohint' library
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for psautohint
Failed to build psautohint
ERROR: Could not build wheels for psautohint which use PEP 517 and cannot be installed directly
```
I tried installing the latest Microsoft Visual C++, but I still get this error message.

**Comment by josh-hadley** [comment]
We do not yet have wheels for Python 3.8 for either AFDKO or [psautohint](https://github.com/adobe-type-tools/psautohint/issues/230), so both would need to be built locally. That "should" work (and does, in our [test scheme](https://github.com/adobe-type-tools/afdko/runs/527490164?check_suite_focus=true), at least). Possibly your `PATH` needs to be updated to find the MSVC tools?

Workaround (if you're unable to get MSVC sorted out) would be to use Python 3.7 for the time being until we have Python 3.8 wheels for both AFDKO and psautohint available.

**Comment by josh-hadley** [comment]
@BornForFever we have just updated psautohint to 2.0.1 which includes Python 3.8 wheels. When you try to install AFDKO with pip, it should grab that version. Could you try installing again and let us know how it goes?

**Comment by BornForFever** [comment]
Everything goes well. Thanks!

发送自 Windows 10 版邮件应用

发件人: Josh Hadley
发送时间: 2020年3月26日 9:42
收件人: adobe-type-tools/afdko
抄送: BornForFever; Mention
主题: Re: [adobe-type-tools/afdko] I cannot install afdko becauseinstallation of psautohint failed. (#1103)

@BornForFever we have just updated psautohint to 2.0.1 which includes Python 3.8 wheels. When you try to install AFDKO with pip, it should grab that version. Could you try installing again and let us know how it goes?
