### ISSUE TITLE
Build Python 3.8 wheels

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#1105]
More users are adopting Python 3.8 and we do not yet have 3.8 wheels available in PyPI. [Some users](https://github.com/adobe-type-tools/afdko/issues/1103) are experiencing problems building locally. Adding Python 3.8 wheels for AFDKO and [psautohint](https://github.com/adobe-type-tools/psautohint/issues/230) to the distributed packages should alleviate this.

**Comment by miguelsousa** [comment]
The current py3.6 AFDKO wheels should install just fine on py3.8. It's psautohint that really needs the new ones, right?

**Comment by josh-hadley** [comment]
Indeed, it should just need the psautohint python 3.8 wheels, which are [in the v2.0.1 release of psautohint](https://pypi.org/project/psautohint/#files).
