### ISSUE TITLE
[makeotf] bug in recode.c which may result in crash with certain fonts

### ISSUE THREAD

**Issue by yarmola** [adobe-type-tools/afdko#1108]
recode.c, function sizeFDWidths (line 959 in current code base).

It calculates minsize, initializing it with SHRT_MAX:

`minsize = SHRT_MAX;`

That is not a good idea: actual value may be bigger than SHRT_MAX. 
It is better to `initialize it with -1` and then change on line 1005:

`if (totsize < minsize) { `

to 

`if (minsize  < 0 || totsize < minsize) {`

Then it works fine.

**Comment by josh-hadley** [comment]
@yarmola thanks for submitting this. By chance do you have (or could you describe how to create) a font that exercises this? I'm not questioning your assertion; I just want to have a test case to evaluate possible fixes.

**Comment by yarmola** [comment]
I have the font under NDA, cannot share. I may talk to owner about sharing it or we may do online debug session (which may be easier and faster).

**Comment by yarmola** [comment]
Actual value of minsize in this font is 37834 (which is why SHRT_MAX fails)
Font has 23K glyphs.

**Comment by josh-hadley** [comment]
OK that makes sense.

Wouldn't it be simpler to address this by initializing `minsize` to `INT_MAX`?

**Comment by yarmola** [comment]
that will solve it too, basically that is more or less the same as doing -1 compare.
