### ISSUE TITLE
Multiple chained lookups per position

### ISSUE THREAD

**Issue by simoncozens** [adobe-type-tools/afdko#1119]
The feature file spec (5.f.i) says:

> For each glyph or glyph class in the input sequence, the contextual rule may specify one lookup (§4.e) to be applied at that position. 

However, the OpenType spec allows more than one lookup per position. ("multiple substitutions may occur in a given context", [Substitution Lookup Record)](https://docs.microsoft.com/en-gb/typography/opentype/spec/gsub#substitution-lookup-record)

Syntactically it should not be a problem to extend the feature file spec to multiple lookups and allow e.g.

```
sub a' b lookup l1 lookup l2;
```

(unless someone has a glyph called `lookup` in which case they get what they deserve).

**Comment by josh-hadley** [comment]
Yes, I believe [Monotype's source format](http://monotype.github.io/OpenType_Table_Source/otl_source.html#chained-substitution-and-positioning) supports something like this. It would be useful to extend the feature file specification to enable this as well.

**Comment by anthrotype** [comment]
> unless someone has a glyph called lookup in which case they get what they deserve

that's a valid glyph name, I wouldn't want to have the compiler check if "lookup" in glyphSet to determine whether it's actually a glyph name or a lookup reference token (we do similar check for ambiguous glyph ranges and it's not ideal).

Maybe `lookup` can be followed by a comma separated list of lookup names, e.g. `lookup l1, l2`

**Comment by simoncozens** [comment]
I suspect someone *already* gets what they deserve if they have a glyph called lookup and they try to use chained contextuals...

**Comment by anthrotype** [comment]
> Glyph names conflicting with keywords must be escaped, and lookup is a keyword already.

right. Ok then

**Comment by punchcutter** [comment]
This should also work for GPOS. I use this feature a lot in Monotype format for substitution and positioning.

**Comment by simoncozens** [comment]
Yes, should work, we just need a test for it. I was confused by the existing pos code which seemed to have more than one lookup anyway...

**Comment by punchcutter** [comment]
I can make some tests. I have situations with about 5 lookups referenced. Maybe more.

**Comment by simoncozens** [comment]
I've added a test for multiple lookups per position in the pull request (#1132). It didn't work, so I fixed it. :)
