### ISSUE TITLE
fontsetplot/proofpdf -g broken when using multiple fonts

### ISSUE THREAD

**Issue by GTMxCode** [adobe-type-tools/afdko#1125]
Hey, been trying to make use of and understand these functions and how they can be of use. After finding out that waterfallplot doesnt work with ttfs and after a lot of trudging through the depths to figure out why and what I could do to maybe make it work with them I gave up and figured what was more necessary was comparison across fonts for now. So I set out to use fontsetplot but I ran into this issue. 

The fonts im trying to compare have upwards of 7000 glyphs and I dont need them all displayed, what I wanted was just the standard a-Z, numbers, punctuation and maybe some other chars. I started simply by trying to output a-Z,zero-nine
`fontsetplot -g a-z,A-Z,zero-nine font1.ttf font2.ttf ....`

Which generates something like:

> Collecting font data from:
>         font.ttf.
>         font2ttf.
> Writing PDF pages...
> Traceback (most recent call last):
>   File "/home/gtm/.local/bin/fontsetplot", line 8, in <module>
>     sys.exit(fontsetplot())
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/proofpdf.py", line 935, in fontsetplot
>     main()
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/proofpdf.py", line 972, in main
>     proofMakePDF(params.rt_fileList, params, txPath)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/proofpdf.py", line 840, in proofMakePDF
>     pdfFilePath = makeFontSetPDF(pdfFontList, params, doProgressBar)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/pdflib/fontpdf.py", line 2156, in makeFontSetPDF
>     pdfGlyph = pdfFont.getGlyph(glyphName)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/pdflib/fontpdf.py", line 464, in getGlyph
>     return self.clientGetGlyph(glyphName)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/pdflib/ttfpdf.py", line 60, in clientGetGlyph
>     return txPDFGlyph(self, glyphName)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/pdflib/fontpdf.py", line 638, in __init__
>     self.clientInitData()
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/pdflib/ttfpdf.py", line 113, in clientInitData
>     clientGlyph.draw(pen)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 773, in draw
>     glyph.draw(pen, glyfTable, offset)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/fontTools/ttLib/tables/_g_l_y_f.py", line 1181, in draw
>     pen.addComponent(glyphName, transform)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/fontTools/pens/basePen.py", line 176, in addComponent
>     glyph = self.glyphSet[glyphName]
> TypeError: 'NoneType' object is not subscriptable

Tried it with one font it works. So I tried multiple fonts again with just A-Z - it works. Eventually this led to me typing out the entire comma delimited alphabet and after a bunch of trial and error I discovered that when trying to output multiple fonts **the letters  'i' and 'j' cannot be used in the glyph list,** and neither can using numbers to refer to glyphs in any form, eg:

`fontsetplot -g i,j font.ttf font2.ttf `      -doesnt work
`fontsetplot -g a-h,k-z,A-Z,zero-nine font.ttf font2.ttf `      -works
`fontsetplot -g 0-200 font.ttf`      -works
`fontsetplot -g 0-200 font.ttf font2.ttf`       -doesnt work

I figure there's gotta be something up with the parsing of the command line when it comes to dealing with multiple fonts and something along the way - since theyre being passed around and through so many different modules - must go awry, but I haven't really dug any further into it and I know next to nothing about python for the moment so I cant really provide any more information

Tbh I think i and j are pretty important characters and to have to leave them out is sucky.

**Comment by frankrolf** [comment]
While the tool probably shouldn’t fail when TTF fonts are used, it’s understandable – those proofing tools were developed along with the first OTF fonts.

Here are some tests I ran:
`fontsetplot -g i,j AcuminPro-Light.ttf AcuminPro-Regular.ttf AcuminPro-Bold.ttf` ✅
`fontsetplot -g i,j AcuminPro-Light.otf AcuminPro-Regular.otf AcuminPro-Bold.otf` ✅
`fontsetplot -g "i,j" AcuminPro-Light.ttf AcuminPro-Regular.ttf AcuminPro-Bold.ttf` ✅
`fontsetplot -g "i,j" AcuminPro-Light.otf AcuminPro-Regular.otf AcuminPro-Bold.otf` ✅

`fontsetplot -g "i,j" AcuminPro-Light.ttf` ✅
`fontsetplot -g "i,j" AcuminPro-Light.otf` ✅
`fontsetplot -g 0-100 AcuminPro-Light.ttf` ❌
`fontsetplot -g 0-100 AcuminPro-Light.otf` ✅
`fontsetplot -g 0-100 AcuminPro-Light.ttf AcuminPro-Regular.ttf AcuminPro-Bold.ttf` ❌
`fontsetplot -g 0-100 AcuminPro-Light.otf AcuminPro-Regular.otf AcuminPro-Bold.otf` ✅
`fontsetplot AcuminPro-Light.ttf` ❌
`fontsetplot AcuminPro-Light.otf` ✅

`fontsetplot -g a-z AcuminPro-Regular.otf` ✅
`fontsetplot -g a-z AcuminPro-Regular.ttf` ✅

The difference in results makes me wonder about the fonts you’re using? It’s clear that there is a problem with TTFs here, but why do our results differ? When I just run `fontsetplot`, I see
```
proofpdf v1.21 Aug 28 2018
```

Are we talking about the same version?

**Comment by frankrolf** [comment]
I have a hunch that the proofing script just doesn’t know how to handle components, since those don’t occur in OTF fonts (but do in TTFs).

**Comment by josh-hadley** [comment]
If TrueType composites/components are suspected as being the problem, one could first run the fonts through the newly-added `ttfdecomponentizer`, then try `fontsetplot` on the resulting decomponentized fonts.

**Comment by frankrolf** [comment]
That worked.
I did the following: In the directory of my example fonts, I created a new dir called `output` to store decomponentized variants.

```
ttfdecomponentizer -d . -o output
cd output
fontsetplot -g 0-100 *.ttf
``` 
✅

**Comment by josh-hadley** [comment]
@GTMxCode I suspect this will work for you, too. If you get a chance to try, please let us know. Based on your initial post, I suspect your `font2.ttf` uses composites for `i` and/or `j`, but `font1.ttf` does not.

So a possible improvement might be to have `fontsetplot` and friends call `ttfdecomponentizer` on TTF inputs. It could get a little messy, with temp files, etc. but might make for a better experience.

N.B. the deomponentization process leaves the resulting font without hints on the decomposed characters, but I don't think that matters for the various PDF-based proofing scripts because the resulting PDFs won't be making use of TrueType hints anyway.

**Comment by GTMxCode** [comment]
Hey guys, I suspect youre right about the  component glyphs, the is and js are made up of a 'dotless' element and the dot. I went back the other day and tired with some other fonts, just a single font and was getting the error, and I realized that some of the fonts I had been testing with I had previously modified  to test with other programs..

So I went about writing a shell script to automate the whole thing, script pulls all fonts that are ttf,otf,cff from the current working directory, allows more directories to be added, and/or individual fonts,. can specific a glyph list, or  for it to use all glyphs, or letting it default to the scripts  built in default list (a-Z,0-9, punc etc),

All going fairly smoothly until I got to the decomponentizer. It will NOT accept any form of output directory as far as I can tell, I tried every conceivable way to input a path but I consistently get this error:

>  ttfdecomponentizer -o '/tmp/_fontplot' GTMxFont-medium-TEST.ttf
> Processing GTMxFont-medium-TEST.ttf...Traceback (most recent call last):
>   File "/home/gtm/.local/bin/ttfdecomponentizer", line 8, in <module>
>     sys.exit(main())
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/ttfdecomponentizer.py", line 141, in main
>     count = process_font(input_file, output_file, opts.verbose)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/afdko/ttfdecomponentizer.py", line 112, in process_font
>     font.save(output_path)
>   File "/home/gtm/.local/pipx/venvs/afdko/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 165, in save
>     file = open(file, "wb")
> IsADirectoryError: [Errno 21] Is a directory: '/tmp/_fontplot'

and yes its a directory.

and unbeknownst to me at first , it modifies the original font rather than creating a modified copy.. So I guess my next move in the script it just to manually copy all the files to the created tmp folder and directly modify them there. this has been way more effort than I imagined ;o

**Comment by frankrolf** [comment]
From `ttfdecomponentizer -h`:
```
positional arguments:
  INPUT            path to input TTF font file OR directory if -d specified.
```

This means that if you want to specify an output directory, the input also needs to be specified a s a directory.

This works:
```
ttfdecomponentizer -d dir_input -o dir_output
```

**Comment by josh-hadley** [comment]
From the discussion, I think this is sorted now, so I am going to close the issue. @GTMxCode if that's not the case, feel free to re-open with additional details. Thanks @frankrolf for the great help and code examples!
