### ISSUE TITLE
codecov.io no longer shows coverage for C code

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#1128]
Coverage for C code seems to have stopped at some point and only coverage for Python code is currently shown.

**Comment by josh-hadley** [comment]
I have added an Action for calculating and uploading coverage for both C and Python. Results [here](https://codecov.io/gh/adobe-type-tools/afdko/tree/7ab90a59c87f6c100b2e16c4e25c7cf2574e8455). @khaledhosny could you give that a quick review? Looks like a similar situation with partial coverage reporting on the C code.

**Comment by khaledhosny** [comment]
I looked into some files and it seems to be the case, I didn’t see any obvious other oddity.

**Comment by josh-hadley** [comment]
@cjchapman noted that the colorized line highlighting was not working. So I made a minor update to the codecov.io config as noted [here](https://docs.codecov.io/docs/fixing-paths) which seems to fix that. It doesn't change the "partial" coverage reporting, though.

**Comment by josh-hadley** [comment]
Tidying up -- I think this is sufficiently addressed and I am closing the issue. Please re-open or create a new one if this becomes a problem again.
