### ISSUE TITLE
Convert from TeX fonts?

### ISSUE THREAD

**Issue by probonopd** [adobe-type-tools/afdko#1129]
I would like to use afdko to convert fonts originally intended for use with TeX to otf and ttf.

MakeOTF seems to need `.pfa`, `features`, and `features.kern` files, as well as `FontMenuNameDB` and `GlyphOrderAndAliasDB`.

However, not all of those seem to be available, e.g., at http://mirrors.ibiblio.org/CTAN/fonts/garamondx/. There is only afm, enc, map, mtx, etx, fd, tfm, pfb, vf.

Can afdko still be used to convert such a font family to otf and ttf, and if so, how?

**Comment by cjchapman** [comment]
@probonopd You can use `makeotf` to build an `otf` from a `pfb` like this:
```bash
$ makeotf -r -f NewG8-Reg.pfb
makeotf [Warning] Could not find default features file. Font will be built without any layout features.
makeotf [Warning] Could not find FontMenuNameDB file. Font will be built with menu names derived from PostScript name.
makeotfexe [WARNING] negative non-edge stem width (fixed) <onequarter>
makeotfexe [WARNING] negative non-edge stem width (fixed) <threequarters> (X3)
makeotfexe [WARNING] negative non-edge stem width (fixed) <pi>
makeotfexe [WARNING] FontMenuNameDB file was not specified or not found. [NewG8-Reg]
makeotfexe [WARNING] Glyph renaming was requested, but the GlyphOrderAndAliasDB file was not specified.
Built release mode font 'NewG8-Reg.otf' Revision 1.000
```

**Comment by cjchapman** [comment]
@probonopd Then you can use `otf2ttf` to convert the `otf` to a `ttf` like this:
```bash
$ otf2ttf NewG8-Reg.otf
```

**Comment by probonopd** [comment]
Thanks for the explanation, it is working. I was worried that this might not preserve the full kerning information, but apparently it does.
