### ISSUE TITLE
Convert ufo that lack a lib.plist?

### ISSUE THREAD

**Issue by probonopd** [adobe-type-tools/afdko#1130]
I would like to use afdko to convert a FontForge-generated `ufo` to `otf`. However, FontForge does not add a `lib.plist` to the `.ufo` directory. Is there a way to still convert it?

References:
* https://github.com/fontforge/fontforge/issues/2161
* https://github.com/probonopd/font-leutkirch/issues/2

**Comment by frankrolf** [comment]
A workaround could be building the lib.plist (and the `public.glyphOrder` array within) yourself, based on the alphabetical order given in the normal contents.plist file. Here is a draft script:

```
'''
Create a lib.plist file in a given UFO, based on the information
in glyphs/contents.plist (alphabetical order).
'''

import os
import argparse
import plistlib

parser = argparse.ArgumentParser(
    description=__doc__)

parser.add_argument(
    'ufos',
    action='store',
    nargs='+',
    metavar='UFO',
    help='input UFO(s)')

args = parser.parse_args()

for ufo_path in args.ufos:
    contents_path = os.path.join(ufo_path, 'glyphs', 'contents.plist')
    lib_path = os.path.join(ufo_path, 'lib.plist')
    with open(contents_path, 'rb') as pl_file:
        contents_dict = plistlib.load(pl_file)

    glyph_names = sorted(contents_dict.keys())
    lib_dict = {}
    lib_dict['public.glyphOrder'] = glyph_names
    with open(lib_path, 'wb') as pl_file:
        plistlib.dump(lib_dict, pl_file)
```

**Comment by probonopd** [comment]
This works flawlessly. Thank you so much @frankrolf.

**Comment by frankrolf** [comment]
Great to hear! :-)

**Comment by probonopd** [comment]
Do you think it may be integrated into afdko? Or should tools like FontForge do this?

**Comment by frankrolf** [comment]
I think glyph order is quite important in a UFO file. I don’t see why an editing tool like FontForge would not be interested in writing the `public.glyphOrder` key.

That said, `tx` (which is the tool invoked while reading the UFO) should probably not fail if the lib.plist is not present.

**Comment by josh-hadley** [comment]
Per [a related discussion](https://github.com/adobe-type-tools/afdko/issues/1255), I'm closing this because our policy is not to modify user UFOs.

**Comment by ctrlcctrlv** [comment]
@frankrolf I assume you intended that script to be open source, and added it to FRBAC. Please confirm in https://github.com/ctrlcctrlv/FRBAmericanCursive/commit/153ba1ea35623d04f78ed173fb2abf3edbb01ecb or here :-)
