### ISSUE TITLE
[makeinstancesufo] should surface more info when failing

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1145]
I just encountered my good friend #790 again, in the middle of a `makeinstancesufo` session.
I have no idea if there would be a way to make this happen, but it would be useful to know what exactly makes the process fail, right away.

Here is my journey (please note that the whole makeinstancesufo process takes several minutes):

1 . In non-verbose mode, the only output is `ERROR:afdko.makeinstancesufo:index must represent an on curve point`, without even specifying what instance might contain the issue.

2. Using the `-v`-mode in a second complete run, I can at least find out which instance we are talking about.
```
INFO:_psautohint:f.ligalong: Removed hints from short element at -6 -232.
INFO:_psautohint:tonos.cap: Removed hints from short element at 76 449.
INFO:_psautohint:turkicdsccmb: Removed conflicting hints at 32 -33.
INFO:psautohint.autohint:Done with font /Users/fgriessh/work/source-serif-pro/Italic/Instances/CaptionBlackIt/font.ufo. End time: Wed May 27 14:35:03 2020.
INFO:afdko.makeinstancesufo:Doing overlap removal with checkoutlinesufo on /Users/fgriessh/work/source-serif-pro/Italic/Masters/../Instances/ExtraLightIt/font.ufo ...
ERROR:afdko.makeinstancesufo:index must represent an on curve point
```

3. The `-vv` mode doesn’t add anything useful to this:

```
makeinstancesufo -i 6 -vv -d Italic/Masters/SourceSerifPro-Italic.designspace
INFO:afdko.makeinstancesufo:Building 1 instance...
INFO:afdko.makeinstancesufo:Built 1 instances.
INFO:afdko.makeinstancesufo:Applying UFO normalization...
DEBUG:ufonormalizer:Normalizing "glyphs/contents.plist".
DEBUG:ufonormalizer:Normalizing "glyphs/layerinfo.plist".
DEBUG:ufonormalizer:Normalizing "metainfo.plist".
DEBUG:ufonormalizer:Normalizing "fontinfo.plist".
DEBUG:ufonormalizer:Normalizing "groups.plist".
DEBUG:ufonormalizer:Normalizing "kerning.plist".
DEBUG:ufonormalizer:Normalizing "layercontents.plist".
DEBUG:ufonormalizer:Normalizing "lib.plist".
INFO:afdko.makeinstancesufo:Applying post-processing...
INFO:afdko.makeinstancesufo:Doing overlap removal with checkoutlinesufo on /Users/fgriessh/work/source-serif-pro/Italic/Instances/ExtraLightIt/font.ufo ...
ERROR:afdko.makeinstancesufo:index must represent an on curve point
```

Finally, doing `checkoutlinesufo -e font.ufo` in the correct instance brings me back to this old friend:

```
t Colinear line at (199, 453). There is an overlap.
t.sups Colinear line at (213, 733). There is an overlap.
tau There is an overlap.
tcaron Colinear line at (199, 453). There is an overlap.
tcedilla Colinear line at (199, 453). There is an overlap.Traceback (most recent call last):
  File "/Users/fgriessh/.pyenv/versions/3.7.4/bin/checkoutlinesufo", line 8, in <module>
    sys.exit(main())
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/afdko/checkoutlinesufo.py", line 1107, in main
    run(sys.argv[1:])
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/afdko/checkoutlinesufo.py", line 1078, in run
    restore_contour_order(fixed_glyph, original_contours)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/afdko/checkoutlinesufo.py", line 936, in restore_contour_order
    contour.setStartPoint(pi)
  File "/Users/fgriessh/.pyenv/versions/3.7.4/lib/python3.7/site-packages/defcon/objects/contour.py", line 223, in setStartPoint
    assert point.segmentType is not None, "index must represent an on curve point"
AssertionError: index must represent an on curve point
```

I would love to see #790 disappear, but I can understand this might be a complex problem. I’d be just as happy to see which glyph and instance my `makeinstancesufo` process is failing at.

**Comment by josh-hadley** [comment]
@frankrolf with #790 solved, what else needs to happen to solve this issue?

**Comment by frankrolf** [comment]
Celebratory drinking and rejoicing!

**Comment by josh-hadley** [comment]
I will go ahead and close this, then. I think there probably are other places where `makeinstancesufo` could surface more info when failing but it's probably best to open issues specific to those failures, when they happen.

**Comment by frankrolf** [comment]
@josh-hadley Yes, I agree. Thanks very much for your work on fixing the root problem!

**Comment by josh-hadley** [comment]
@frankrolf how's this:
```python
$ makeinstancesufo --traceback -d SourceSerifPro.designspace
Traceback (most recent call last):
  File "afdko-venv/bin/makeinstancesufo", line 8, in <module>
    sys.exit(main())
  File "afdko-venv/lib/python3.7/site-packages/afdko/makeinstancesufo.py", line 483, in main
    run(opts)
  File "afdko-venv/lib/python3.7/site-packages/afdko/makeinstancesufo.py", line 343, in run
    updateInstance(instancePath, options)
  File "afdko-venv/lib/python3.7/site-packages/afdko/makeinstancesufo.py", line 96, in updateInstance
    checkoutlinesUFO(co_args)
  File "afdko-venv/lib/python3.7/site-packages/afdko/checkoutlinesufo.py", line 1103, in run
    restore_contour_order(fixed_glyph, original_contours)
  File "afdko-venv/lib/python3.7/site-packages/afdko/checkoutlinesufo.py", line 950, in restore_contour_order
    assert not(ctr_starts[ci]), "Can't happen: duplicated start point!"  # noqa: E501
KeyError: 2
```

**Comment by frankrolf** [comment]
Much better I think! At least one will know more about the error.
However, this error still tells me nothing about the file and/or glyph the error occurs in. Would that be possible?

**Comment by josh-hadley** [comment]
That would need to happen in `checkoutlinesufo`, where this particular error originates. At best `makeinstancesufo` could know the file being processed, but not the specific glyph. 

I guess this item needs to be expanded to be a general improvement of error message origination in all subprocesses that `makeinstancesufo` calls.

**Comment by josh-hadley** [comment]
I think [these changes](https://github.com/adobe-type-tools/afdko/compare/jh-more-checkoutlines-overlap) should help for this specific case -- mainly because it _should_ avoid both the KeyError (contour index out-of-range) as well as the failed assertions. But should either of them occur, they will have improved messaging detailing the glyph and contour/point location.
