### ISSUE TITLE
Inconsistency: Symbol or Latin

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#1156]
in
https://github.com/adobe-type-tools/afdko/blob/464008517cbd92ce211ac51182c9941b95303ce8/c/makeotf/makeotf_lib/source/hotconv/map.c#L1848
is says to fall back to Symbol, but it is actually setting Latin.

**Comment by josh-hadley** [comment]
From what I can tell, this comment has been incorrect with regard to the actual behavior since AFDKO became open source. So a fix here would be to update the comment.
