### ISSUE TITLE
tx binary conflicts with other software

### ISSUE THREAD

**Issue by antlarr-suse** [adobe-type-tools/afdko#1162]
When building an afdko package it generates a `tx` binary that gets installed to `/usr/bin` .

I think it would make sense to rename the binary to something else so that it doesn't conflict with other software (tx is too commonly associated to the rx/tx pair, while afdko's `tx` has nothing to do with transmitting anything).

As an example of another project using the same name for a binary that gets installed to the same directory you have the transifex project, whose `transifex-client` openSUSE package also installs a `/usr/bin/tx` binary (other distributions probably also have the same package, maybe with another name).

I would suggest renaming `tx` to `afdko-tx`, but of course, that's only a suggestion.

**Comment by frankrolf** [comment]
This was brought up before in #672. How can such a conflict practically be avoided? The afdko’s `tx` has been around for much longer than transifex, FWIW.

**Comment by antlarr-suse** [comment]
It can be avoided by using a prefix (like my proposal of `afdko-tx` ) or using a single entry point like it was proposed in that previous issue. So all executables would be under (for example) `/usr/lib64/afdko/` and there would be just an `afdko` binary in `/usr/bin` that would consume the first argument to know which binary to execute with the rest of parameters. So instead of running for example `tx -cff -dd /tmp/cff -a *.pfb`  users would run `afdko tx -cff -dd /tmp/cff -a *.pfb`

I understand that that's disruptive and may break workflows as was mentioned in that issue, but I don't think we should look at it from a "who was here first" point of view, but from the point of view of a trying to find a long-term solution that benefits users who currently can't install in the same system afdko and transifex-client.

**Comment by cjchapman** [comment]
I'm closing this issue as I do not want to inconvenience the folks who've been using AFDKO for decades to resolve a conflict for the few, if any, who also use Transifex.
