### ISSUE TITLE
STAT table is created with incorrect values

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/afdko#1164]
With the following STAT definition (edited to only show a couple values) the resulting STAT table has values divided by 65536 instead of the expected values.

```
table STAT {
   ElidedFallbackName { name "Regular"; };

   DesignAxis wght 0 { name "Weight"; };
   DesignAxis ital 1 { name "Italic"; };

   AxisValue {
      location wght 400 350 - 450;
      name "Regular";
      flag ElidableAxisValueName;
   };

   AxisValue {
      location ital 1;
      name "Italic";
      flag ElidableAxisValueName;
   };
} STAT;
```
For `ital` the resulting value is `0.00002` instead of the expected `1`

For the Regular weight values the results are
```
<NominalValue value="0.0061"/>
<RangeMinValue value="0.00534"/>
<RangeMaxValue value="0.00687"/>
```
instead of the expected values
```
<NominalValue value="400"/>
<RangeMinValue value="350"/>
<RangeMaxValue value="450"/>
```

**Comment by josh-hadley** [comment]
@khaledhosny can you take a look at this? Also it would be good to have a new test case that uses fixed point in one or more of the `AxisValue` inputs, to confirm that we are correctly handling fixed point throughout the process.

**Comment by khaledhosny** [comment]
Ah, I think I know what is going on. The Axis value type is `Fixed` (16.16 fixed point), but the code does not do any conversion an writes it verbatim. So we need to accept `float` and convert to `Fixed` internally. Our feature grammar doe not accept any `float`s except for font revision, so that would need a bit of new code.

**Comment by khaledhosny** [comment]
We are only accepting integers at the moment, so float input is not possible at all.

**Comment by cjchapman** [comment]
We need to accept float, as the axis range could be quite small, e.g. 0 to 1.

You could get the value as a string and then use `strtof()` on it, similar to how `setFontRev()` is used now.
