### ISSUE TITLE
makeotf does not implement glyph ranges according to spec

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#117]
In https://github.com/behdad/fonttools/issues/559#issuecomment-202122434 @schriftgestalt wrote that makeotf is not following the spec for glyph ranges. Re-filing this here because it sounds like an AFDKO bug (either in the spec or in the makeotf implementation). @schriftgestalt, would you have an example that illustrates the problem?

**Comment by schriftgestalt** [comment]
I don’t have an example. I think I explained it as good as I can ;)

**Comment by brawer** [comment]
Hm, I tried to reproduce the bug report, but no success. Here’s a test font: 
[AFDKOBug117-Regular.ttf.zip](https://github.com/adobe-type-tools/afdko/files/193268/AFDKOBug117-Regular.ttf.zip) where the glyph order is reversed for glyphs E–H and e–h: 

```xml
    <GlyphID id="0" name=".notdef"/>
    <GlyphID id="1" name="A"/>
    <GlyphID id="2" name="B"/>
    <GlyphID id="3" name="C"/>
    <GlyphID id="4" name="D"/>
    <GlyphID id="5" name="H"/>
    <GlyphID id="6" name="G"/>
    <GlyphID id="7" name="F"/>
    <GlyphID id="8" name="E"/>
    <GlyphID id="9" name="a"/>
    <GlyphID id="10" name="b"/>
    <GlyphID id="11" name="c"/>
    <GlyphID id="12" name="d"/>
    <GlyphID id="13" name="h"/>
    <GlyphID id="14" name="g"/>
    <GlyphID id="15" name="f"/>
    <GlyphID id="16" name="e"/>
```

Now, when applying the following feature file:
```
feature test {
  sub [A-F] by [a-f];
} test;
```

makeotf produces a GSUB table with the following mapping, just as one would expect:
```
        <SingleSubst index="0">
          <Substitution in="A" out="a"/>
          <Substitution in="B" out="b"/>
          <Substitution in="C" out="c"/>
          <Substitution in="D" out="d"/>
          <Substitution in="E" out="e"/>
          <Substitution in="F" out="f"/>
        </SingleSubst>
```

Note that in the output, there is an E → e mapping even though the glyph ID of E is higher than that of F in the input test font. So it actually appears that makeotf does _not_ look at glyph IDs when interpreting the range expressions. In other words, makeotf’s implementation seems to be faithfully implementing the spec.

@schriftgestalt, do you see another way to reproduce the bug?

**Comment by schriftgestalt** [comment]
You are right. I did tried this some time ago but I must have done something wrong. Sorry for the confusion.

I think I was mislead my this line: 
```
gcAddRange(gid, endgid, p, q);
```
gid and endgid are the glyph IDs and p and q are the actual names, and those are then used to build the range, not the IDs.

**Comment by brawer** [comment]
No problem. Thanks for the confirmation.
