### ISSUE TITLE
FontMenuNameDB behavior can be a bit confusing

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1171]
I remember the `FontMenuNameDB` file used to be an integral file required to build an OTF – even for just building a single style. `makeotf` would fail without a `FontMenuNameDB` (and without a `GlyphOrderAndAliasDB`).

A while ago this changed, so `makeotf` can be called without much of that collateral – font naming will be deduced from the PS name within the UFO.

Today I noticed that the presence of a `FontMenuNameDB` which has _unrelated_ names in it can make `makeotf` fail.
See attached projects for an example.

- Both projects contain a `font.ufo` file with PS name `abc-def`
- When adding this FontMenuNameDB (`does not work.zip`) project, `makeotf` will fail:

```
[Unrelated-Fontname]
	f=Unrelated
	s=Fontname
```

This behavior could be a deliberate decision, or an oversight – I just wanted to put it up for discussion.

[does work.zip](https://github.com/adobe-type-tools/afdko/files/4799818/does.work.zip)
[does not work.zip](https://github.com/adobe-type-tools/afdko/files/4799819/does.not.work.zip)

**Comment by punchcutter** [comment]
I thought this made sense because if there _is_ a `FontMenuNameDB` then shouldn't it have the correct names for the font? If it _only_ contains unrelated names then that seems like a big mistake somewhere and I would expect an error.

**Comment by frankrolf** [comment]
Yes – I am encountering this when running `buildmasterotfs` in the context of building a Variable Font.
It could still be a perfect FontMenuNameDB, just not contain the names of the masters.

**Comment by punchcutter** [comment]
I'm doing the exact same thing so I made sure the `FontMenuNameDB` had all the master names just so I wouldn't run into this, but that totally makes sense to build the masters without requiring the names to be defined here.

**Comment by frankrolf** [comment]
As usual, this comes from me preparing a stripped-down exercise, where I found this behavior a bit counterintuitive.

**Comment by miguelsousa** [comment]
@frankrolf The error is coming from **makeotfexe**, right? IIRC **makeotf.py** doesn't parse the `FontMenuNameDB` file.

**Comment by frankrolf** [comment]
@miguelsousa Yes, correct! 😊
