### ISSUE TITLE
[makeotf] update docs to describe how to invoke 5- and 6-digit Unicode values needed for SPUA-A and SPUA-B

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1177]
[Docs:](https://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#glyphorderandaliasdb-goadb)

> The third field is a Unicode value, specified in the form uniXXXX or uXXXX, where XXXX is a Unicode value (hexadecimal).

Codepoints in [SPUA-A](http://www.unicode.org/charts/PDF/UF0000.pdf) are represented with 5 hex digits; those in [SPUA-B](https://unicode.org/charts/PDF/U100000.pdf) with 6. The four-digit limitation on codepoints in the GOADB means that one cannot make a font with codepoints in these areas.

**Comment by benkiel** [comment]
Not well documented there, but for those above 4 digits, use `uXXXXX` or `uXXXXXX`. `uni` is only for four digits, afaik

**Comment by punchcutter** [comment]
Yes, that's not so clear. We'll update the docs.

**Comment by mbutterick** [comment]
Oh really? Here’s a (disassembled) `pfa` and a `goadb` that uses the 6-digit convention. Though `makeotf` compiles the font, the resulting font has no codepoints.

```
%!
0 dict dup begin
/FontName /Test def
/Private 0 dict dup begin
/RD {string currentfile exch readstring pop} def
/CharStrings 5 dict dup begin
/D {
0 1000 hsbw
0 0 rmoveto
0 1000 rlineto
1000 0 rlineto
closepath
endchar
} def
/C {
0 1000 hsbw
0 0 rmoveto
0 1000 rlineto
1000 0 rlineto
closepath
endchar
} def
/B {
0 1000 hsbw
0 0 rmoveto
0 1000 rlineto
1000 0 rlineto
closepath
endchar
} def
/A {
0 1000 hsbw
0 0 rmoveto
0 1000 rlineto
1000 0 rlineto
closepath
endchar
} def
/.notdef {
0 1000 hsbw
0 0 rmoveto
0 1000 rlineto
1000 0 rlineto
closepath
endchar
} def
end % of CharStrings dict
def
end % of Private dict
```

```
.notdef .notdef u000000
space space u000014
A A u000029
B B u00002A
C C u00002B
D D u00002C
```

If I replace the above `goadb` with one that uses the 4-digit convention:

```
.notdef .notdef u000000
space space u000014
A A u000029
B B u00002A
C C u00002B
D D u00002C
```

The resulting font has the expected codepoints.

**Comment by mbutterick** [comment]
`makeotf` logging output with 6-digit `goadb`:

```
makeotfexe [WARNING] missing /FontBBox (default inserted)
makeotfexe [WARNING] FontMenuNameDB file was not specified or not found. [Test]
makeotfexe [WARNING] <Test> cmap{plat=1,script=0,lang=0}: empty encoding
makeotfexe [WARNING] <Test> unable to patch FontBBox in CFF table
makeotfexe [WARNING] <Test> cmap{plat=3,script=1,lang=0}: empty encoding
```

With 4-digit `goadb`:

```
makeotfexe [WARNING] missing /FontBBox (default inserted)
makeotfexe [WARNING] FontMenuNameDB file was not specified or not found. [Test]
makeotfexe [WARNING] <Test> unable to patch FontBBox in CFF table
```

**Comment by punchcutter** [comment]
You can't mix the lengths like that. If something can be represented by 4 digits then you use 4. If it requires 5 or 6 then you use 5 or 6. I guess maybe that could also use clarification.

**Comment by benkiel** [comment]
@mbutterick in my GOADB files, I'm not using the third column (often) to assign unicode, just changing the final name (first column) to the `uXXXXX` value. That works. So, @punchcutter, there could be something there that isn't working but should

**Comment by punchcutter** [comment]
I'm not sure what might not be working. It all seems to be working for me using 4, 5, or 6 digit unicodes to either rename or set the Unicode value.

**Comment by mbutterick** [comment]
FWIW this GOADB works for me.

```
.notdef .notdef u0000,uF00000
space space u0020,uF00020
A A u0041,uF00041
B B u0042,uF00042
C C u0043,uF00043
D D u0044,uF00044
```
