### ISSUE TITLE
[Question] How to keep the AFDKO and extensions/modules up to date?

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#118]
What's the best way to keep my local AFDKO with all modules/extensions always up to date? With regard to the dependencies. I would like to automatize that.

![afdko-build-dir](https://cloud.githubusercontent.com/assets/18100950/14156017/974497b2-f6c4-11e5-9f33-1748c2c0649a.gif)

**Comment by readroberts** [comment]
Having an automated way to do this is certainly a very good idea. It does need to be cross platform between OSX, Linux, and Windows. I will eventually get around to this but it may take a long time - if anyone else wants to be volunteer, please go ahead. I would probably write a setup.py script. The script would have to take care of removing old modules, which in some cases have python module version numbers and Python version number in them

**Comment by miguelsousa** [comment]
The current installation setup forces the update of the tools' dependencies.
