### ISSUE TITLE
[makeotf] ambiguities in docs about compilation behavior of `features[.*]` files

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1189]
The [docs show an example](https://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#using-makeotf) of a project tree with separate `features.family`, `features`, and `features.kern` files.

But the [docs for `makeotf`](https://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#makeotf-options) only show support for the main `features` file with the `-ff` flag.

1) Are the `features.family` and `features.kern` hard-coded names? Are they derived from whatever name is given in the `-ff` flag?

2) Do these names represent a pattern? That is, can I have a `features.liga` file? Or are `features.kern` and `features.family` special exceptions?

3) What are the semantics for how `features.family` and `features.kern` are combined with the base `features` file? Are they just concatenated? If so, in what order?

**Comment by moyogo** [comment]
Wouldn’t these separate feature files be included in the main feature file with the [`include` directive](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#3-including-files)?

**Comment by mbutterick** [comment]
OK, I understand now. Only the main `features` file is loaded by `makeotf`, which can `include` other files, but they have no special status. Thanks.

**Comment by miguelsousa** [comment]
Also, the files can be named whatever you like. These days we tend to use a `.fea` filename extension — see [Source Serif repo](https://github.com/adobe-fonts/source-serif-pro/tree/main), for example — as that enables syntax highlighting in text editors such as Sublime Text and TextMate.
