### ISSUE TITLE
makeotfexe does not accept hex or octal STAT values as stated in feature file spec

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/afdko#1190]
The [spec](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9.i) says that for STAT location values 

`value` is a signed number and can be specified using decimal, hex and octal formats as well

except that makeotfexe does not allow hex or octal here. It's just as easy to remove this from the spec as it is to add hex/octal support, but I can't really see a reason to use hex or octal here.

**Comment by khaledhosny** [comment]
Yes, this text should be removed. Hex and octal were supported when we were accepting signed integers not floats.
