### ISSUE TITLE
Provide single entry point to all executables

### ISSUE THREAD

**Issue by medicalwei** [adobe-type-tools/afdko#1196]
I am currently packaging AFDKO in Debian, but we encountered a problem that the name of the binary `tx` has been taken by Transifex Client (a client of i18n platform) in Debian repository: https://bugs.debian.org/965151

I managed to resolve it by putting all binaries to another directory (currently `/usr/libexec/afdko`), and provide another shell script `afdko` in `/usr/bin`, to provide users an access to the binaries.  To build font packages using AFDKO in Debian, currently I would suggest contributors to prepend `/usr/libexec/afdko` in PATH in our packaging scripts.

We would like to upstream this.  However, knowing that it would break existing scripts that uses AFDKO, I would like to know what's your stance on the problem.

https://salsa.debian.org/fonts-team/afdko/-/tree/debian/master/debian/scripts

**Comment by benkiel** [comment]
This has come up before, see https://github.com/adobe-type-tools/afdko/issues/1162
