### ISSUE TITLE
Proposal for minor change to STAT feature syntax

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#1197]
We (Adobe FDK developers) are considering a minor (but breaking) change to the Feature File Specification for defining range-based STAT AxisValues (known as ‘location format B’ in the Feature File Spec and ‘Format 2’ in the OpenType spec).
The original proposal ([here](https://github.com/adobe-type-tools/afdko/issues/176)) and current implementation use a hyphen (`-`) to separate `<rangeMinValue>` and `<rangeMaxValue>`. After some testing and discussion here, it turns out that the hyphen is not necessary.

Removing the hyphen from the Feature File specification:
 - makes parsing less complicated
 - makes the documentation simpler
 - makes the .fea code cleaner:

```fea
    # format 2
    AxisValue {
        location wght 400 300 500;
        name “Regular”;
        flag ElidableAxisValueName;
    };
```

We wanted to make folks aware of this likely change and give an opportunity to discuss, in the unlikely event that this would have an untenable impact on workflows or other implementations (@punchcutter has work-in-progress on the fontTools implementation of this and will update that work with this change, if applicable).

To be clear: _we are not talking about changing any aspect of the OpenType specification_. This is applicable only to the AFDKO Feature File Specification, and _only_ for STAT AxisValue location format B.

At worst, we expect the impact would be that STAT table definitions in .fea files using the currently defined (as of AFDKO 3.5.0) range-based AxisValue format would need to remove the `-` from any such range definitions in order to be correctly parsed with the updated `makeotfexe`.

cc: @sairuspatel @khaledhosny

**Comment by twardoch** [comment]
At FontLab, we have not yet incorporated the new AFDKO but we're looking forward to adopt it, and we support the change.

**Comment by khaledhosny** [comment]
I have no objection.

**Comment by anthrotype** [comment]
sounds good to me
