### ISSUE TITLE
[fea syntax] OS/2 yStrikeoutSize and yStrikeoutPosition values cannot be set.

### ISSUE THREAD

**Issue by KazunariTsuboi** [adobe-type-tools/afdko#1205]
I need to set the OS/2 StrikeoutSize and StrikeoutPosition values. I expected that the following description can be set in fea. 
But it didn't work.Is there a way I'm overlooking?

```
include(../familyfeatures.fea);
table OS/2 {
	WeightClass 400;
	XHeight 536;
	Panose 2 11 5 2 4 5 4 2 2 4;
	StrikeOutSize = 50;
	StrikeOutPosition = 328;
	include(../familyos2.fea);
} OS/2;
```

If I did not include the two lines for StrikeOutSize and StrikeOutPosition, the font build will succeed. 
If I include two lines, the following error will be output.

```
syntax error at "StrikeOutSize" missing "}" [/home/guest/TEST Sans/TEST/features 6]
makeotfexe [FATAL] <TESTSans-Regular> aborting because of errors
```

**Comment by frankrolf** [comment]
The strikeout/underline sizes are automatically set by `makeOTF` – I assume this happens via measuring the thickness of the hyphen.
Here are all the keys that can be set in the os/2 table: https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#9f-os2-table

That said, you need to check your syntax: the `=` sign is not used in any of the other lines, which produces this particular error message.

**Comment by benkiel** [comment]
To set these to custom values, the only way I know of is to post process your font binaries with something like fontTools.

**Comment by frankrolf** [comment]
@benkiel Do you know which applications/browsers make use of those values? (Not Adobe apps but I remember MS Office does). I know you’ve been dealing with underline/strikethrough for a while ;-)

**Comment by KazunariTsuboi** [comment]
Thank you for your kind reply!
I will use fontTools to fix this value.

**Comment by benkiel** [comment]
@frankrolf MS Office for sure, I've not catalogued others

**Comment by gferreira** [comment]
hello @frankrolf 

> Do you know which applications/browsers make use of those values?

have a look at [The state of underlines and strikethroughs](https://www.harbortype.com/the-state-of-underlines-and-strikethroughs/)
