### ISSUE TITLE
[makeinstancesufo] wrong camelCasing in designspace attribute

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1211]
If an instance entry in a designspace file does not contain a PostScript font name attribute, `makeinstancesufo` complains in the following way:
```
WARNING:afdko.makeinstancesufo:Instance at index 0 has no 'postScriptFontName' attribute.
```

However, the ps font name needs to be indicated like this:
```
postscriptfontname="BlahBlah-Blah"
``` 

Note the casing being different in warning vs required.

**Comment by frankrolf** [comment]
This change seems to have fallen on our feet (not sure how):
Generating from a normal .designspace, I get this output:
```
WARNING:afdko.makeinstancesufo:Instance at index 0 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 0 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 0 has no 'stylename' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 1 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 1 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 1 has no 'stylename' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 2 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 2 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 2 has no 'stylename' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 3 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 3 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 3 has no 'stylename' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 4 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 4 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 4 has no 'stylename' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 5 has no 'familyname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 5 has no 'postscriptfontname' attribute.
WARNING:afdko.makeinstancesufo:Instance at index 5 has no 'stylename' attribute.
```
All of those attributes exist.
Will investigate.

**Comment by josh-hadley** [comment]
I had a look at this and it looks like [the `designspaceLib` code](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/designspaceLib/__init__.py#L939) reads the _XML_ attribute as all lowercase (e.g. `postscriptfontname`), but uses camel-cased for the *Python* attribute (`postScriptFontName`), which is a bit confusing.

The fix here is to revert the checks in `buildmasterotfs` back to camel-cased (which is testing the Python attribute names, not XML), but keep the all-lowercase attribute names in the .designspace files.

**Comment by frankrolf** [comment]
Alright, thank you Josh! Perhaps the real solution should be in [this](https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/makeinstancesufo.py#L247) line:

from
```
                    f"Instance at index {i} has no '{attr_name}' attribute.")
```
to
```
                    f"Instance at index {i} has no '{attr_name.lower(}' attribute.")
```

**Comment by josh-hadley** [comment]
Having the error message use the XML (all-lowercase) attribute name seems sensible for communicating the problem to the user (in addition to reverting the actual check to use the Python/camel-cased names).
