### ISSUE TITLE
[checkoutlinesufo] needs a -o (output file) option

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#1242]
Currently, `checkoutlinesufo` writes a new layer when the input is UFO, which is fine, but for non-UFO inputs, the input file gets overwritten. It would be useful to have a `-o` option to specify an output file for such cases to avoid accidentally overwriting the input.

**Comment by frankrolf** [comment]
Unless I am completely wrong:￼
￼The default mode does not overwrite the input file. Only the -e option will.￼

**Comment by josh-hadley** [comment]
Yes, that's correct. To clarify, with non-UFO inputs _and_ the `-e` option, the input file will be overwritten in place. This request is to deal with that specific case.

**Comment by alerque** [comment]
Thanks for fixing this!
