### ISSUE TITLE
[makeotf] is it possible to compile features without every named glyph?

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1248]
According [to the docs](https://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#glyphorderandaliasdb-goadb):

> both the source font file and the features definition file must use the same glyph names

Is it possible (directly, or via clever workaround) to coax `makeotf` to compile a font even if not all the glyphs mentioned in the `features` file are available? 

I’m trying to build a font compiler that can build a font from some selected subset of glyphs in a source file. I can take glyphs out of the source easily enough. But if any of those removed glyphs are mentioned in the `features` file, the compile will fail. So somehow, the `features` file has to be filtered according to the glyphs that are actually in the font.

I’ve written an `fea` preprocessor that will delete any glyph classes or `sub`/`pos` rules that pertain to missing glyphs. It works well enough, but it’s fragile because it doesn’t parse the whole `fea`. I’m wondering if there’s a better way.

**Comment by josh-hadley** [comment]
I don't think anything like this is supported currently, and I don't foresee it being supported any time soon (although we'd certainly consider any code contributions that could solve it).

Maybe some sort of iterative subsetting could be used to work around: make your initial subset, try makeotf, catch and address any missing glyph errors, update the subset, and try again until you don't get missing glyph errors?

**Comment by miguelsousa** [comment]
I _think_ that if you build the font in development mode (i.e. no `-r` option) makeotf won't be strict about any eventual feature file errors.

**Comment by mbutterick** [comment]
Thanks for the suggstion. Removing the `-r` option doesn’t change anything, I’m afraid: `makeotf` will still fail if glyphs are missing.

**Comment by frankrolf** [comment]
This would all be simpler if the OpenType features were objects themselves, rather than just a text file.
@typoman has done some thinking in that direction, here is a repo that is related: https://github.com/typoman/featureman

I have been trying to find a longer discussion about this topic which took place somewhere on GitHub, but maybe Bahman himself can point it out.

**Comment by typoman** [comment]
There is a similar topic that I started on the fonttools repo. I haven't had time to take a look at it but the main issue as I remember was that fonttools feature parser sometimes parses the glyphs as strings and sometimes as glyph a fonttools.fealib.ast object. If this inconsistency is resolved, making a subsetter would not be a hard task.

**Comment by mbutterick** [comment]
Thanks, I didn’t know `fonttools` could parse `fea` files. (I’m not using Python, so `fonttools` may not be able to solve my problem, but maybe I can get some ideas.)

Another idea I tried is using glyph classes everywhere instead of hard-coded glyph names. So this:

```
feature ordn { 
    sub zero a' by ordfeminine;
} ordn;
```

Would become this:

```
@aclass = [a];
@zeroclass = [zero];
feature ordn { 
    sub @zeroclass @aclass' by ordfeminine;
} ordn;
```

Now suppose `a` and `zero` are missing. I would rewrite the glyph class and thereby avoid having to edit any individual `sub` or `pos` rules (because they all rely on the glyph class):

```
@aclass = [];
@zeroclass = []
feature ordn { 
    sub @zeroclass @aclass' by ordfeminine;
} ordn;
```

Unfortunately this doesn’t work: `makeotf` rejects a glyph class with zero members.

FWIW the AFDKO documentation [does not forbid](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2g-glyph-classes) a glyph class with zero members, so this behavior is a little surprising, because when I see “list of X” without further qualification, I assume an empty list is acceptable.

**Comment by frankrolf** [comment]
> Unfortunately this doesn’t work: makeotf rejects a glyph class with zero members. 
FWIW the AFDKO documentation does not forbid a glyph class with zero members, so this behavior is a little surprising, because when I see “list of X” without further qualification, I assume an empty list is acceptable.

I think it would be quite difficult for the feature parser to compile this feature if the trigger class (indicated by the `'`) is empty. I understand the failure in this case, and I think we need to clarify the documentation.

That said, one thing that would be very useful would be a dry-run of a feature file – to see if that feature _would_ compile in a font, without actually writing a font file at all.

**Comment by mbutterick** [comment]
Maybe my idea is less terrible than I thought. To satisfy `makeotf`, you could force every class to have at least one glyph (say, by putting `.notdef` at the beginning of every class). So my previous example:

```
@aclass = [a];
@zeroclass = [zero];
@ordfeminineclass = [ordfeminine];
feature ordn { 
    sub @zeroclass @aclass' by @ordfeminineclass;
} ordn;
```

Would become this:

```
@aclass = [.notdef a];
@zeroclass = [.notdef zero];
@ordfeminineclass = [.notdef ordfeminine];
feature ordn { 
    sub @zeroclass @aclass' by @ordfeminineclass;
} ordn;
```

This time, suppose `a` and `ordfeminine` are missing. We remove them from the classes:

```
@aclass = [.notdef];
@zeroclass = [.notdef z];
@ordfeminineclass = [.notdef];
feature ordn { 
    sub @zeroclass @aclass' by @ordfeminineclass;
} ordn;
```

This time, `makeotf` **will** compile the feature.
