### ISSUE TITLE
[makeotf] documentation insufficiently describes required feature file elements

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1249]
The [docs describe](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4.a) a `feature` block:

> A feature block may contain glyph substitution rules [§5], glyph positioning rules [§6], or both.

The word “may” connotes that neither type of rule is mandatory, therefore the feature block can be empty.

In practice, this is not true: `makeotf` will throw an error if a feature file contains an empty feature block. (Unclear whether this should be considered a bug in the documentation, or in `makeotf`)

For instance, this `features` file fails:

```
languagesystem latn dflt;
feature numr {
} numr;
```

But this one succeeds:

```
languagesystem latn dflt;

feature numr {
sub .notdef by .notdef;
} numr;
```

As does this:

```
languagesystem latn dflt;
```

---

Relatedly, a blank `features` file also fails:

```
# featureless surface
```

The docs are silent on whether a blank file should be valid. But it seems like it must be, since no particular element is specified as being mandatory. 

For instance, this `features` file is valid:

```
languagesystem latn dflt;

feature numr {
sub .notdef by .notdef;
} numr;
```

We can remove either the `languagesystem` statement or the `feature` block and still have a valid features file:

```
feature numr {
sub .notdef by .notdef;
} numr;
```

```
languagesystem latn dflt;
```

But we can’t remove both.

**Comment by josh-hadley** [comment]
> The word “may” connotes that neither type of rule is mandatory, therefore the feature block can be empty.
> ...
> (Unclear whether this should be considered a bug in the documentation, or in makeotf)

Thanks for pointing this out. I think a simple change of "may" to "must" should clarify the documentation sufficiently. Although to be completely unambiguous, I suppose it should be rewritten as something like, "A feature block _must_ contain _one or more_ glyph substitution [§5] or glyph positioning [§6] rules, or a combination of both types.". I will get a PR going on this.

> Relatedly, a blank features file also fails

Probably we could make a general statement in the documentation that "a feature file must specify at least one element (e.g. a `languagesystem`, `feature` block, etc.)". More exhaustive testing of what will/won't work would be welcomed to help nail down precisely what must be specified and get the documentation into a more accurate state.

**Comment by mbutterick** [comment]
> Probably we could make a general statement in the documentation that "a feature file must specify at least one element (e.g. a languagesystem, feature block, etc.)".

Looking at the [feature-file grammar](https://github.com/adobe-type-tools/afdko/blob/0109e66efea54dfeb856483905c9a89f04fa12e5/FDK/Tools/Programs/makeotf/makeotf_lib/build/hotpccts/featgram.g), a `featureFile` [must contain](https://github.com/adobe-type-tools/afdko/blob/0109e66efea54dfeb856483905c9a89f04fa12e5/FDK/Tools/Programs/makeotf/makeotf_lib/build/hotpccts/featgram.g#L2172) one or more of five possible elements, one of which is a `topLevelStatement`. But [the grammar](https://github.com/adobe-type-tools/afdko/blob/0109e66efea54dfeb856483905c9a89f04fa12e5/FDK/Tools/Programs/makeotf/makeotf_lib/build/hotpccts/featgram.g#L2162) for `topLevelStatement` says that it can be blank. If that is so, then a blank features file is legal.

On my more current installation of AFDKO, the empty features file compiles. So I will look more closely at where the error is arising.

(The grammar [does insist](https://github.com/adobe-type-tools/afdko/blob/0109e66efea54dfeb856483905c9a89f04fa12e5/FDK/Tools/Programs/makeotf/makeotf_lib/build/hotpccts/featgram.g#L1773) on one or more statements inside a feature block.)

**Comment by mbutterick** [comment]
I retract the blank-features issue. I just tested again on `makeotfexe` 2.5.65599 and it does not complain.

**Comment by josh-hadley** [comment]
OK so to try to wrap this up: what else about the documentation needs to get updated to match the actual behavior of `makeotf`? Or is everything sorted now?
