### ISSUE TITLE
ufoNormalizer dependency uses deprecated keyword arg; failures in Python 3.9

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#1253]
The deprecation of parts of `plistlib` in Python 3.9 leaves `ufoNormalizer` as a point of failure under Python 3.9 (in [makeinstancesufo](https://github.com/adobe-type-tools/afdko/runs/1377316759?check_suite_focus=true#step:8:53) which uses `ufoNormalizer`). See https://github.com/unified-font-object/ufoNormalizer/issues/73 for details.

**Comment by josh-hadley** [comment]
Possible solution is to [switch to `ufolib2`](https://github.com/unified-font-object/ufoNormalizer/issues/73#issuecomment-737507209)

**Comment by benkiel** [comment]
@josh-hadley it's not. ufoLib2 has a terrible name, it's a lightweight set of objects (think defcon, but for in-memory things, not app building things).

**Comment by josh-hadley** [comment]
@benkiel thanks. Guess we'll have to sort out a fix in `ufoNormalizer`. Is anyone actively maintaining that project?

**Comment by benkiel** [comment]
@josh-hadley honestly, work up whatever patch you think is best for `ufoNormalizer` and submit the PR, I don't have an opinion on the best thing, trust you. @typesupply might have one.
