### ISSUE TITLE
"Pair positioning has conflicting statements in feature 'kern'": significance of this warning? [makeotfexe]

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1260]
According to [the docs](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6bi-specific-and-class-pair-kerning):

> In the `kern` feature, the specific glyph pairs should precede the glyph class pairs in the feature file, mirroring the way that they will be stored in the font.

When I have specific glyph-to-glyph pairs that override class kerning pairs, I follow the directive to list them first in the `kern` feature. And yet — I sometimes (not always) get the warning “Pair positioning has conflicting statements in feature 'kern'; choosing the first value”.

I don’t see any problems in the behavior of the generated OTF — the class kerns work as they should, as do the overrides.

Thus, what is the significance of this warning, if the `kern` feature seems to endorse overriding class kerns by putting exceptions at the beginning of the list? Is there a better way of expressing this that will satisfy `makeotfexe`?

**Comment by frankrolf** [comment]
This is not usually the case with kerning exceptions as you describe, but a situation where the user (font creator) intent is indeed unclear.
I have definitely gotten these kinds of warnings in the past, but could always resolve them by editing kerning data (which is why I don’t have a specific example at hand).

Can you perhaps isolate an example for which this warning is shown?

**Comment by mbutterick** [comment]
I think the problem arises when the exception pair overrides a glyph-to-class kern that uses `enum` rather than a class-to-class kern. For instance this:

```
languagesystem latn dflt;

feature kern {
    @_A_second = [A AE];
    pos F AE -100;
    enum pos F @_A_second -40;
} kern;
```

Means the same as this:

```
languagesystem latn dflt;

feature kern {
    @_A_second = [A AE];
    pos F AE -100;
    pos F A -40;
    pos F AE -40;
} kern;
```

And now the conflict is evident.

But this leads to another question — I thought that glyph-to-class pairs had to be described with`enum`, because the [GPOS table only supports](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-2-pair-adjustment-positioning-subtable) glyph-to-glyph (= format 1) and class-to-class (= format 2) pair positioning. A glyph-to-class pair is neither of those things, so we use `enum` to turn it into the equivalent list of glyph-to-glyph pairs.

But the AFDKO [docs explicitly endorse](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6bi-specific-and-class-pair-kerning) notating a glyph-to-class pair as `pos F @_A_second -40` instead of  `enum pos F @_A_second -40`. OK, but what does this glyph-to-class notation *mean*, in terms of the GPOS lookup generated?

**Comment by frankrolf** [comment]
I can only describe this in very simple terms, but maybe it’ll help:

As you already know and illustrated, `enum` “explodes” any pair which contains a kerning class into single pairs.
In the font file, single- and class-pairs are stored in different subtables (class 1 and class 2), where any pair involving a class is always categorized as a class 2 pair (therefore, also a glyph-to-class pair).

`enum` is really only used as a shorthand whenever there’s an exception glyph, for example:
```
@MMK_L_LAT_I = [I Igrave Iacute Icircumflex Idieresis Imacron Idotaccent Iogonek Icaron Idotbelow Ihoi Itilde];
@MMK_R_LAT_j = [j dotlessj jcircumflex];

# exception for every single combo possible with the the @MMK_R_LAT_j group stored as glyph-to-glyph pairs, therefore class 1:
enum pos Iogonek @MMK_R_LAT_j 20;

...
```

**Comment by frankrolf** [comment]
BTW if you are looking into analyzing kerning expectations vs actual output, I have written some tools for that:
https://github.com/adobe-type-tools/kern-dump

**Comment by mbutterick** [comment]
> In the font file, single- and class-pairs are stored in different subtables, where any pair involving a class is always categorized as a class 2 pair (therefore, also a glyph-to-class pair is).

So in the notation `pos F @_A_second -40`, if `makeotfexe` treats this as a class-to-class pair, what is the left-hand class?

**Comment by frankrolf** [comment]
That is my understanding.
