### ISSUE TITLE
`makeotfexe` does not use default features file

### ISSUE THREAD

**Issue by mbutterick** [adobe-type-tools/afdko#1261]
According to [the docs](http://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#makeotf-options):

> –ff | <file path> | Specify path to features file. If not provided, MakeOTF assumes the file name is features.

Attached is a zip containing `simple.pfa` and `features`. If I run this:

```
makeotfexe -f simple.pfa --ff features
```

The font fails to compile due to errors in the features file. Whereas if I run this:

```
makeotfexe -f simple.pfa
```

The font will compile, but only because `makeotfexe` is ignoring `features`. Therefore, I conclude that contrary to the docs, `makeotfexe` does not load a features file unless the `-ff` switch is explicitly specified.

[Archive.zip](https://github.com/adobe-type-tools/afdko/files/5631728/Archive.zip)

**Comment by josh-hadley** [comment]
The section of the docs you quoted is talking about **`makeotf`**, not `makeotfexe`. And in fact,

```
makeotf -f simple.pfa
```

will pick up the `features` file as advertised, and building your example will fail because of the errors in that file.

N.B. also in the docs, [just above the part you linked to](http://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#using-makeotf) is this (emphasis added):
> MakeOTF comes in two parts which can actually be called independently:
> `makeotfexe` is a program written in C, and is actually the tool that builds the OpenType font file. _It requires, however, that all the source files be explicitly specified with options on the command line_.
> `makeotf` is a command shell that calls the Python™ script `makeotf.py`. This will look for the source files in some standard locations, and fill in default values for options. It can also read the options needed from a project file (`current.fpr`), which means that for a particular font, one only needs to type-in all the options once. When `makeotf.py` has gathered all the source files, it will call the `makeotfexe` program.

**Comment by mbutterick** [comment]
My mistake — I was relying partly on the text visible when running `makeotfexe -h`, which says:

```-ff  <path>  : Specify path other than default 'features' for feature file```

So maybe the (smaller) issue is that the command-line documentation for `makeotfexe` is not consistent with the online docs.

**Comment by josh-hadley** [comment]
> maybe the (smaller) issue is that the command-line documentation for makeotfexe is not consistent with the online docs

That does appear to be the case. I'll leave this issue open as a reminder to investigate and possibly update `makeotfexe`'s help documentation.
