### ISSUE TITLE
[Wish] a few more autohint options

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#129]
1. Remove both, vertical and horizontal hints
2. Remove vertical hints
3. Remove horizontal hints
4. Create vertical hints only
5. Create horizontal hints only
6. Subroutinize / Desubroutinize (actually the default)

And maybe:
1. Remove alignment zones
2. Remove (I miss the correct term) vertical stem width values
3. Remove (I miss the correct term) horizontal stem width values

With regard to 7, 8 and 9: This can be easily done with the help of TTX. So I am not sure, whether these options are useful.

**Comment by Arno-Enslin** [comment]
I have found a way to remove hints and to desubroutinize with the AFDKO/FontTools, but it is slow and really uncomfortable. From my batch file:

```
for %%f in (Decompile\*.otf) do (
%TX_exe% -cff -dd DecompileD -S +b -n -a "%%f"
%MakeOTF_py_Com% -nS -f "DecompileD\%%~nf.cff"
%ttx_py_Com% -t "CFF " -d DecompileD "DecompileD\%%~nf.otf"
%ttx_py_Com% -m "%%f" -d CompileD "DecompileD\%%~nf.ttx"
```

Explanation:
1. TX generates a CFF font from the source font without hints and without subroutines.
2. MakeOTF builds a dummy font from this CFF then.
3. TTX dumps the CFF table from the dummy font and
4. TTX merges the dumped CFF table into the source font.

**Comment by kenlunde** [comment]
In this case, the AFDKO _sfntedit_ tool is your friend because it is used to remove, insert, or replace entire _sfnt_ tables without compiling the tables themselves, and what you want to do can be accomplished using only two functional command lines (using _%SFNTEDIT_exe%_ to represent _sfntedit_):

```
%TX_exe% -cff -dd DecompileD -S +b -n -a "%%f"
%SFNTEDIT_exe% -a CFF="DecompileD\%%~nf.cff" "%%f"
```

(I am not sure whether I represented the _%_ stuff correctly, but you should get the idea.)

**Comment by twardoch** [comment]
I agree with Ken. Arno, I've mentioned sfntedit before — you should really give it a try! As Ken points out, the bare CFF file just so happens to also be the binary "CFF " table, so sfntedit is your best friend there :)

**Comment by twardoch** [comment]
(Basically, for your CFF workflows, you don't need ttx. tx and sfntedit willdo a good job.)

**Comment by Arno-Enslin** [comment]
@ Ken and Adam

Generally it works fine with sfntedit. There are only two differences:

With sfntedit instead of makeotf and TTX:
```
<Encoding>
</Encoding>
<BlueScale value="0.03750000149"/>
```

With makeotf and TTX (matches the values of the source font):

```
<Encoding name="StandardEncoding"/>
<BlueScale value="0.0375"/>
```

And surprisingly it does not work, if I transfer the CFF table with sfntedit from the dummy font (generated with makeotf) to the source font, because this results in an invalid font (TTX decompiles the cff table to hexdata).

**Comment by kenlunde** [comment]
The _sfntedit_ tool doesn't modify tables, so it's happening upstream, and may be the result of tx handling fractional values.

**Comment by Arno-Enslin** [comment]
I am using makeotfexe instead of makeotf.py now. And the input for makeotfexe is a t1 font (Unix Type 1) now -- generated with TX. And in the last steps I am using TTX, because the cff tab
le, which is contained in the OTF, that was generated with makeotfexe/makeotf.py cannot be transferred with sfntedit. But this doesn't matter, because the new script is almost as fast as the solution with sfntedit, but the result is closer to the original (with regard to the BlueScale value).

Requires folders Input and Output.

```
@echo off
set "FDK=C:\FDK"
set "Tools=%FDK%\Tools"
set "win=%Tools%\win"
set "PythonDir=%win%\Python\AFDKOPython27"
set "python_exe=%PythonDir%\python.exe"
set "sitepackages=%PythonDir%\Lib\site-packages"
set "fontTools=%sitepackages%\fonttools-3.0-py2.7.egg\fontTools"
set "makeotfexe=%win%\makeotfexe.exe"
set "tx_exe=%win%\tx.exe"
set "ttx_py=%fontTools%\ttx.py"
set "ttx_py_Com=%python_exe% %ttx_py%"

for %%f in (Input\*.otf) do (
%TX_exe% -t1 -dd Output -S -n -a "%%f"
%makeotfexe% -shw -f "Output\%%~nf.t1" -o "Output\%%~nxf"
%ttx_py_Com% -t "CFF " -d Output "Output\%%~nxf"
del "Output\%%~nf.t1"
del "Output\%%~nxf"
%ttx_py_Com% -m "%%f" -d Output "Output\%%~nf.ttx"
del "Output\%%~nf.ttx"
)
```

**Comment by Arno-Enslin** [comment]
-S is the default sub option of -t1 and -cff.

And in TX "-S" means "No Subroutinization", while "-S" means in makeotfexe.exe and makeOTF.py "Subroutinization". This should become harmonized.

I think, this means, that there is actually **no way,** to keep the original subroutinization of a font, if you only want to dehint a font with the AFDKO.

By the way, I get a warning in case of Garamond Premier Pro (used as test font), if I turn on subroutinization:

makeotfexe [WARNING] subr stack depth exceeded (reduced)

TX produces the same warning message, if subroutinization is turned on (with +S).

**Comment by Arno-Enslin** [comment]
I just have noticed, that autohint.px/autohintexe desubroutinizes. So you have to involve makeotf, if you want to have subroutines.

**Comment by twardoch** [comment]
It’s quite logical. CFF subroutines really are just chunks of data, they include runs of charstrings, which can just one or a few segments, hintmasks, movetos etc. If you autohint, hintmasks are added to the glyph, which may mean that a continuous subroutine that spanned several segments and was used in several glyphs is now interrupted by some hintmask in one glyph but not in another. The Adobe autohinter does not work on the level of CFF or the Type 2 charstrings but on entire glyphs, and uses the intermediate .bez format, so each CFF glyph is converted from the subroutine-based charstring form into the .bez format, then hints are added, and it is incorporated back into the CFF. 

It might be possible to write a dehinter in fontTools/Python that keeps subroutines (one that removes ALL hints from the font, not on a per-glyph basis), but I doubt it can be easily done for adding hints.

**Comment by readroberts** [comment]
1) Autohint and subroutines. What Adam said: If you hint, you have to re-subroutinize. 

2) TTX vs sfntedit. You cannot expect exactly the same CFF out of makeotf and TTX. TTX optimizes the CFF, and may do so differently than makeotf. However, I have not yet seen a case were the result is functionally different. <Encoding name="StandardEncoding"/> and <Encoding></Encoding> mean the same the thin; the latter takes slightly less space.  

3) <BlueScale value="0.03750000149"/> vs <BlueScale value="0.0375"/>. I cannot reproduce this: When the source pfa font has <BlueScale value="0.0375"/>, then it remains teh case through makeotf, , subroutinization with 'tx' , folsing back in with sfntedit, and decompiling and recompiling with 'ttx'. Can you provide source data that produces this problem, and the steps you followed? 

4) sfntedit fails to add CFF to OTF. I can't imagine how sfntedit could change the CFF.  Can you provide source data and the steps that produces this problem?

I agree that the options are confusingly different between the tools.I have never changes them because there is a 16 year history of test and build scripts that may or not depend on the current values. Legacy support is often a pain.

**Comment by readroberts** [comment]
5) About "[WARNING] subr stack depth exceeded". Yes, subroutines can only be called to a recursion depth of 10.  (e.g subr 1 calls subr 2, subr2 calls subr 3, subr 3 calls subr 4.... subr 9 calls subr 10.) There is no way to tell this by top-level inspection of the font - you have execute every glyph charstring, and count the subr call depth. 'tx' does this, and will warn if there is problem.

**Comment by Arno-Enslin** [comment]
@ readroberts

With regard to #3 and #4:

Test font: SourceSansPro-Regular.otf

```
TX.exe -t1 -dd Temp -n -a Input\SourceSansPro-Regular.otf
Copy Input\SourceSansPro-Regular.otf Output
makeotfexe.exe -shw -f Temp\SourceSansPro-Regular.t1 -o Temp\SourceSansPro-Regular.otf
sfntedit.exe -a CFF=Temp\SourceSansPro-Regular.otf Output\SourceSansPro-Regular.otf 
```

Check font in Output -- it is invalid:

[Test.zip](https://github.com/adobe-type-tools/afdko/files/224704/Test.zip)

But if I use TTX instead of sfntedit it works.

**Comment by miguelsousa** [comment]
The `autohint` tool in this repo is in maintenance mode. Any feature requests should be made towards [psautohint](https://github.com/adobe-type-tools/psautohint).
