### ISSUE TITLE
[checkoutlinesufo] restore_contour_order fails in some situations

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/afdko#1291]
In some outlines like the glyph in tests/checkoutlinesufo_data/input/contour-restore.ufo `checkoutlinesufo` fails to restore contour order because of the way the contours overlap by a single point. 

Run
`checkoutlinesufo -e --all contour-restore.ufo`

and the result is

`AssertionError: Failed assertion: duplicated start point on contour 3 at 616, 597 of glyph cid51107.`

This stops the entire process, but we should never fail here. The main purpose of `restore_contour_order` is to attempt to keep compatibility the same across masters, but that's not always going to be possible, especially when removing overlaps.  If we can't restore contour order then we should just report it.

**Comment by frankrolf** [comment]
Related to #790, perhaps?

**Comment by punchcutter** [comment]
Maybe related, but all of the files attached to #790 seem to work fine with the current `checkoutlinesufo`
