### ISSUE TITLE
mistake in language system tag reports confusing error message

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1292]
This is from a workshop exercise today:
One student implemented the locl feature in the following way (notice `latin` not `latn`):

```
feature locl {
	script latin;
		language TRK;
			sub i by i.dot;
} locl;
```

The error message reports a missing semicolon, which is not really the case:
```
syntax error at "n" missing ";" [/Users/fgriessh/Desktop/FDKABK/Exercise 3 - simple family/Instances/Regular/../../family.fea 9]
```

**Comment by khaledhosny** [comment]
It is expecting a semicolon, but found an `n`, and is explicitly saying so. The message is a bit cryptic but not wrong.

**Comment by frankrolf** [comment]
Exactly. It’s not that the semicolon is not missing, which is slightly misleading – especially to a beginner.

A remark:
I filed this issue live in class as an example on _how to file an issue_ – it may well be too much trouble to fix it.

**Comment by frankrolf** [comment]
Closing since I would not really know how to solve this without creating lots of overhead.
