### ISSUE TITLE
MakeOTFUserGuide needs update

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#130]
I have not completely checked it, but at least this is not true anymore:

> The FontMenuNameDB file is used to specify font menu-naming information. **A sample version of**
> **this file can be found at FDK/Tools/SharedData/.**

> The source font is not required to have any glyphs that are named in the GlyphOrderAndAliasDB file. **There is a sample version of this file at the folder FDK/Tools/SharedData/.**

**Comment by readroberts** [comment]
Thanks, will fix. I do see all the notes, and appreciate your attention to detail:  I just often don't the time to interrupt and chase down all the issues, especially since I only get to work on the FDK somewhat sporadically.  I am doing some FDK work this week, but will do much more in the summer.

**Comment by readroberts** [comment]
Fixed.
