### ISSUE TITLE
makeotf: errors out if UFO lib.plist is not present

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1305]
Trying to compile UFO folder as:
```
PS C:\projects\wavefont> makeotf -f wavefont.ufo -o font/wavefont.otf
Command '['tx', '-dump', '-0', 'C:\\projects\\wavefont\\wavefont.ufo']' returned non-zero exit status 6.
```
Is there some specifics to compiling UFOs?

**Comment by frankrolf** [comment]
Nothing wrong here – there seems to be a problem with the UFO source data.
I don’t know what would return exit status 6, but what does `tx -dump -0 font.ufo` do?

**Comment by dy** [comment]
Ok, I had comments in plist file as
```plist
<!-- For windows!-->
    <key>openTypeOS2WinAscent</key>
    <integer>1500</integer>
```
Which resulted in 
```
tx.exe: (ufr) Encountered end of buffer before end of glyph.openTypeOS2WinDescent</key>
    <integer>0</integer>

    <key>openTypeNameVersion</key>
    <string>Version 1.000</string>
  </.

```

So that was probably XML parser issue.

**Comment by dy** [comment]
In fact just encountered less clear error.
Having a font created by fontforge and exported as UFO.
```
 makeotf -f ./test.ufo/ -o font/test.otf
Command '['tx', '-dump', '-0', 'C:\\projects\\wavefont\\test.ufo']' returned non-zero exit status 3.

tx -dump -0 ./test.ufo/
Failed to read lib.plist
tx.exe: --- ./test.ufo/
tx.exe: (ufr) source stream error
```

**Comment by frankrolf** [comment]
This error helps me more.
FontForge does not write lib.plist, I don’t know why.

https://github.com/adobe-type-tools/afdko/issues/1130#issuecomment-623180851

**Comment by dy** [comment]
`lib.plist` is optional at least in [UFO3](https://unifiedfontobject.org/versions/ufo3/lib.plist/):

> This file is a place to store authoring tool specific, user specific or otherwise arbitrary data for the font. It is optional. If it is not defined in the UFO, there is no lib data.

So that seems to be makeotf issue.

**Comment by frankrolf** [comment]
see #1306
