### ISSUE TITLE
[tx] Clarify which +/- options are default

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#131]
From one of the sub help messages of TX:

> [-cff options: -E, -F, -O, +T, -Z, -b, -d]
> +/-E    optimize for embedding
> +/-F    optimize Family zones
> +/-O    optimize for ROM
> +/-S    subroutinize
> +/-T    optimize charstrings
> +/-Z    do not/do decompose SEAC and dotsection operators
> +/-b    preserve glyph order
> +/-d    enable duplicate hintsubs warnings
> -n      remove hints
> -std    force the output font to have StandardEncoding
> 
> CFF mode writes a CFF conversion of an abstract font. The precise form of the
> CFF font that is written can be controlled to a limited extent by the options
> above. The feature is enabled by the + form of the option and disabled by the 
> - form of the option.

There are more +/- options. The help does not clarify, which of them (+ or -) are default.

**Comment by twardoch** [comment]
“Optimize for ROM” is my favorite.

**Comment by Arno-Enslin** [comment]
For me it is important to know, which options I have to set for keeping the CFF table of the source font (OTF) in original condition, because I only want to use it for dehinting and desubroutinization and -- this seems to be also possible -- for decomposing.

**Comment by kenlunde** [comment]
Unless you're subsetting, as long as you are using the _-cff_ command-line option, meaning that the data remains CFF, glyph order should be unchanged. And, even if you are subsetting, there is an option, _-pg_, for preserving GIDs and their order, which presumably inserts dummy glyphs for the GIDs that are not included in the subset.

(This is one reason why I like CID-keyed fonts: the glyph order is inherent and cannot be changed without changing the underlying glyph-to-CID assignments, which requires using the _mergeFonts_ or _rotateFont_ tool and an appropriate mapping table.)

**Comment by miguelsousa** [comment]
The first line lists the defaults: `[-cff options: -E, -F, -O, +T, -Z, -b, -d]`
I've updated the help to make that more clear.
