### ISSUE TITLE
Composite-like CFF subroutinization

### ISSUE THREAD

**Issue by twardoch** [adobe-type-tools/afdko#132]
@readroberts and others: it would be great if makeOTF supported a method of creating CFF (esp. from UFO) where subroutines in the final font would correspond directly to components, i.e. the font would be "flat" except subrotines would be built from charstrings describing entire glyphs existing in the fonts. 

This would not yield huge compression but could become popular for font development purposes, esp. if such a fonts were "tagged" in some way via some special entry inside CFF. Then tools could check for that and "import" such fonts into other formats by using a special routine that reconstructs components. 

Would that be possible?

**Comment by frankrolf** [comment]
Help me understand: in which scenario would this be helpful?
Font developers usually have access to source files, so why would they want to reverse-engineer a binary font? 
(Unless, of course, they would reverse-engineer someone else’s fonts)

**Comment by twardoch** [comment]
For some tools such as VOLT, the font files are the "sources". And, indeed, for some projects (eg. OFL-licensed) you actually encourage 3rd-party contributions, and your sources may not be the contributors' sources (SFD vs UFO vs Glyphs etc.). 

I'd like to be able to ship fonts that are consumable by the enduser yet retain meaningful semantic information.

**Comment by miguelsousa** [comment]
> your sources may not be the contributors' sources (SFD vs UFO vs Glyphs vs VFB etc.)

I don't get it. With the exception of Source Han, we use UFO as the source format.
The scenario you're presenting doesn't seem like a real-use case.

**Comment by behdad** [comment]
Adam,

This is generally not possible.  Definitely not with hinted fonts.

I've heard @readroberts say a couple of times that they treat subroutines like individual glyphs.  While for some simple purposes that's possible, in general it's not.  You cannot even parse a subroutine into it's operands and operators on its own.  That is because if the subroutine (or any subroutine it calls, recursively) has a hintmask operator, you wouldn't know how many mask bytes follow.  The only way to know that is to have interpretted a specific glyph from the beginning.

For the same reason, you cannot have a hinted component in a subroutine that can be called from multiple glyphs, unless all those glyphs have very similar hints, which in general is not the case.

**Comment by readroberts** [comment]
This is actually not that difficult to imagine. Basically, we would have to revive the seac  composite glyph operator (Behdad is quite right about the problems with hinting of using subrs for components) in a new form that could reference any GID. However, I don't really see the point. CFF is a poor format for storing editable data. It was originally designed pre-OpenType, as a really, really compact format for Type1 data, and holds only the minimal data necessary info for a font. It is missing not only a place to put composite glyph names, but has no place to put any of the huge amount of meta data that you have in FontLab or UFO. I don't see the point of making the effort, when this is so much better done in source font formats like UFO.

**Comment by twardoch** [comment]
Ok. :) Subroutines are actually very much like shapes in FontLab VI. We even contemplated direct conversion of subroutines into shapes when reading CFF, but we found that in most cases, the "logical" setup of subroutines was not useful for further editing. But it could be done easily, actually. 

But you're right, I didn't consider that the hintmasks required to deal with "composite"
(or formerly-composite) glyphs may be different than in the "constituent" glyphs. 

I still miss the ability to store composite information along with cubic outlines. Perhaps something to consider in a future font format.

**Comment by be5invis** [comment]
Subroutinization may be useful if you are going to reduce the file size as more as possible.
So... a `-O` level?

**Comment by readroberts** [comment]
Not in current plans.
