### ISSUE TITLE
Bug in autohint.py/autohintexe in connection with options -hf -a / -hf -r

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#133]
1. Bug in autohint.py/autohintexe in connection with options -hf -a / -hf -r. (Autohint.py does not write the history file.)

I get the following error message:

```
Hinting font C:\FDK_26.03.2016_Batch\Autohint\Output\SourceSansPro-Regular.otf. Start time: Tue Apr 19 01:12:16 2016.
Traceback (most recent call last):
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\autohint.py", line 1368, in <module>
    main()
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\autohint.py", line 1358, in main
    hintFile(options)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\autohint.py", line 1222, in hintFile
    if hasHints and not (options.rehint):
UnboundLocalError: local variable 'hasHints' referenced before assignment
```

2. And maybe another bug with regard to desubroutinization by autohint.py/autohintexe:

I would like to compare the autohinted "dehinted and desubroutinized SourceSansPro-Regular.otf" with the autohinted (rehinted) "original SourceSansPro-Regular.otf".

I have not found a combination of options yet, that have resulted in two font files with the same size. If autohint desubroutinizes, shouldn't be the output the same, regardless whether the input is subroutinized and hinted? At least with the option -a?

Have a look at the input and output files, please:
[Test Autohint.zip](https://github.com/adobe-type-tools/afdko/files/224961/Test.Autohint.zip)

Shouldn't be the output the same, if there is no history file?

If I desubroutinize the output again, both files have the same file size.

[After my test with Garamond Premier Pro,](https://github.com/adobe-type-tools/afdko/issues/129) I thought, that Autohint.py/Autohintexe desubroutinizes. But obviously it is a difference, whether the input is unhinted and desubroutinized or not. If there isn't a history file (and because of the bug there is none, even not  with the option "-hf") , all glyphs in both fonts should become hinted. And if autohint desubroutinizes automatically, the file sizes should be the same.

**Comment by Arno-Enslin** [comment]
With regard to the file
"SourceSansPro-Regular (original).otf"
in the folder
"Output (Autohint option -r [because of bug without history file]"

If you have a look on the cff table, dumped with TTX, you will see, that it contains hex (raw) data from lines 40 till 1773. Raw data like this:

```
          <CharString index="0" raw="1">
            a3d4a0d3 9fd7088f 06a03fa0 43a342aa
            2718fb59 06fb3dfb 9f15e006 caf75c05
            f78306c9 fb5c05e4 06fb72f9 24052d06
            0b   
          </CharString>
```

TTX doesn't seem to be able to decompile the cff table of this font file completely.

If you subroutinize or desubroutinize this font with the help of "TX, makeotf and TTX" [(explained in "this" thread)](https://github.com/adobe-type-tools/afdko/issues/129) and decompile the cff table then, you will see, that the decompiled table does not contain raw data.

**Comment by Arno-Enslin** [comment]
There are a few typographic, orthographic and grammatical mistakes in the help of autohint.py. Because I am finding many of those bugs in the help and usage of the script and exe files, I wonder, what is the best way to report them. By the way, my English is worse. It would be better, if somebody, whose native language English is, would thoroughly check the help and usage of all script and exe files. Or alternatively a thread for only typographic, orthographic and grammatical mistakes.

Or shall I create pull requests for all of these mistakes? The functional bugs are more more important.

**Comment by readroberts** [comment]
Fixed.
