### ISSUE TITLE
[buildcff2vf] 'CompatibilityPen' object has no attribute 'roundNumber'

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/afdko#1333]
This recent commit killed `buildcff2vf` by renaming `roundNumber` to `round`:
https://github.com/fonttools/fonttools/commit/28fae1d95f29f5fc866c439a391ff2ee138842d6#diff-e81ab163899906f7e6e650e554eac56944d24ecbd125ff1aeb049620bae6419c

We need to update `buildcff2vf` to match. 

```
    def make_flat_curve(self, cur_coords):
        # Convert line coords to curve coords.
        dx = self.roundNumber(cur_coords[0] / 3.0)
        dy = self.roundNumber(cur_coords[1] / 3.0)
        new_coords = [dx, dy, dx, dy,
                      cur_coords[0] - 2 * dx,
                      cur_coords[1] - 2 * dy]
        return new_coords
```

**Comment by josh-hadley** [comment]
When that commit gets merged & released, we should be able to detect it when pyupbot picks up the new fontTools. Simple fix when that happens.
