### ISSUE TITLE
Subroutinizing doesn't work in windows

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1355]
Reopening the issue raised in #1319.

After performing
```
cp ./font/wavefont.otf ./font/wavefont.min.otf
tx -cff2 +S +b ./font/wavefont.otf > ./font/table.CFF2
sfntedit -a CFF2=./font/table.CFF2 ./font/wavefont.min.otf
```
from [howto example](https://github.com/adobe-type-tools/afdko/wiki/How-To#cff2) the font is corrupted. 

```
tx -dump -1 wavefont.min.otf 
tx: --- wavefont.min.otf
tx: (cfr) bad INDEX header
```

The problem persists and is reproducible in windows machine.

**Comment by kaydeearts** [comment]
Hi @dy , after looking into this bug I realize it may be an issue with handling `stdout` on Windows. 

As a temporary solution, you can try:
`tx -cff2 +S +b -o ./font/table.CFF2 -f ./font/wavefont.otf`

Let me know if that works for you. In the meantime, we'll be looking into a permanent fix for `stdout` handling on Windows.

**Comment by dy** [comment]
It worked! Thank you @kaydeearts!
Found out that the order of arguments matters:
```
tx -cff2 +S +b -f ./font/wavefont.otf -o ./font/table.CFF2 
```
doesn't work.
Providing you 2 files: one generated with stdout, the second is with your method.
[wavefont.zip](https://github.com/adobe-type-tools/afdko/files/6475559/wavefont.zip)

**Comment by miguelsousa** [comment]
@dy try without the `-o`

    tx -cff2 +S +b -f ./font/wavefont.otf ./font/table.CFF2

**Comment by dy** [comment]
@miguelsousa  tried, that failed:
```
tx: --- ./table.CFF2
tx: (cfr) source stream error
```
