### ISSUE TITLE
non-free files/licenses

### ISSUE THREAD

**Issue by onlyjob** [adobe-type-tools/afdko#136]
* `FDK/Tools/Programs/makeotf/makeotf_lib/build/hotpccts/featgram.g`
 * `FDK/Tools/Programs/public/lib/config/standard/linux.mak`
 * `FDK/Tools/Programs/public/lib/config/linux/pentium/*`

~~~~
 All information contained herein is the property of Adobe
 Systems Incorporated. Many of the intellectual and technical
 concepts contained herein are proprietary to Adobe, are protected
 as trade secrets, and are made available only to Adobe licensees
 for their internal use. Any reproduction or dissemination of this
 software is strictly forbidden unless prior written permission is
 obtained from Adobe.
~~~~

--- 

 * `FDK/Tools/Programs/CID_font_support/Sample input/UniJIS-UCS2-H`

~~~~
and that the contents of this file are not altered in any
way from its original form.
~~~~

---

 * `FDK/Technical Documentation/MSFontValidatorIssues.htm`
 * `FDK/Technical Documentation/WinWeights.html`

~~~~
No modification, editing or other alteration of this document is allowed;
~~~~

---
 * `Documentation/CommandLineHowTo.pdf` 

~~~~
Except as permitted by such license, no part of this publication may be
reproduced, stored in a retrieval system, or transmitted, in any form
or by any means, electronic, mechanical, recording, or otherwise,
without the prior written permission of Adobe Systems Incorporated.
~~~~

---

Many files contain `Copyright XXXX Adobe Systems Incorporated. All Rights Reserved.` but no license grant.

**Comment by HinTak** [comment]
I think only the first set are essential but need a rewrite for portability, so GPL-fanatics should just drop all listed files above.

**Comment by HinTak** [comment]
I think most of these should be removed:

```grep -R 'Patents Pending' afdko/*
```

**Comment by readroberts** [comment]
The incorrect copyrights have been changed to simple copyright. These are covered and are compatible with the Apache 2.0 license for the entire AFDKO.
