### ISSUE TITLE
[Question] How to use mergeFonts to remove a glyph? 

### ISSUE THREAD

**Issue by tamcy** [adobe-type-tools/afdko#138]
Hello,

From [this page](https://blogs.adobe.com/CCJKType/2009/02/using_afdko_to_build_opentype_1.html), `mergeFonts` can be used to *"merge multiple fonts, add/remove glyphs, and change glyph names"*. However, I am unable to figure out how to use the tool to remove a glyph from a file (seems not mentioned anywhere in the doc).

I can somewhat achieve this with the following steps:
1. Exports the to-be-removed glyphs to a temporary file via `tx`.
2. Clears the glyphs with a font editor.
3. Merge them back with `mergeFonts`.

However, it doesn't really "remove" the glyph - the slots are still there, albeit now empty. And this sounds circuitous.

My question is: what is the real/correct way to remove a glyph with `mergeFonts`? Thank you!

**Comment by kenlunde** [comment]
@tamcy: Are you working with a name- or CID-keyed source font?

Keep in mind that these AFDKO tools operate only on CFFs, CIDFont resources, and name-keyed Type 1 fonts, and if you specify an OpenType font (aka 'sfnt' resource), the output will not be an OpenType font, but rather one of the formats listed previously.

With that said, _mergeFonts_ is the ideal tool for merging glyphs from multiple fonts, and as part of this process it can exclude a glyph from one source font so that the same glyph (same name of CID) in another source font, such as a corrected version, will be used in the merge (aka destination) font.

If you simply want to exclude a glyph, use the _tx_ tool and its _-gx_ command-line option, with the name of the glyph, or its CID if it's a CID-keyed font, as its argument.

**Comment by tamcy** [comment]
@kenlunde Thanks for your reply. Let me try to elaborate it further.

I am aware of the output format of the `mergeFonts` tool. As you know, I am using the source files (CID font resource) of Source Han Sans to build a new font. When there are glyphs that need to be modified to suit my need, I mainly followed [this article](https://blogs.adobe.com/CCJKType/2012/02/simplifying-cidfont-glyph-corrections.html) you wrote, which involves the following steps:

1. Use `tx` to export the glyphs-to-modify from the CID font resource to a .pfa file;
2. Fix them;
3. Merge the fixed glyphs back with `mergeFonts`. This produces a new CID font resource;
4. Use `makeotf` to create a new .otf file.

So far, so good. Then I found I want to remove some glyphs. For instance, the CID font of Source Han Sans language specific version (e.g. `cidfont.ps.OTC.TC`) contains glyphs of all regions for the same codepoint. This is not needed in my use case, so I wanted to keep only those that are actually mapped by the CMap file to save some space. As it is stated that `mergeFonts` is capable of removing glyphs, I thought that it'd be nice to tell `mergeFonts` to skip the glyphs I do not want, so I tried something like this:

```
mergefonts -gx 2946 final_new_cidfont.ps updated_glyphs.ps cidfont.ps.OTC.TC
```

Which doesn't work as I have thought. Swapping `-gx` with `-g` also doesn't make `final_new_cidfont.ps` to only include the glyph with CID 2946, so I should have misinterpreted its use (I have to admit I am not sure what's going on here). Hence my question.

**Comment by readroberts** [comment]
Note that the '-gx' option applies only to the first source font. For all the rest, if you want to filter out glyphs, you need to provide a glyph alias file that specifies the set of glyphs that should be copied from the following source font file. If the glyph '2946' that you want omitted is in the first source file, then mergeFonts is not working right. I can't immediately reproduce the problem, so if this is the case, then please provide the source fonts, and I will take a look at what is going on inside mergeFonts.

**Comment by kenlunde** [comment]
@tamcy: In addition to what @readroberts wrote, I suggest that you always prefix CID references with a slash (they are otherwise treated as GID references, which will differ from CIDs if CIDs do not equal GIDs in the first merge font), and that you transpose the merge fonts, because the _-gx_ command-line option applies only to the first one (_cidfont.ps.OTC.TC_):

`% mergefonts -gx /2946 final_new_cidfont.ps cidfont.ps.OTC.TC updated_glyphs.ps`

**Comment by tamcy** [comment]
@readroberts 

Exactly. The glyph I'd like to exclude is in the last source, i.e. `cidfont.ps.OTC.TC` in my example. IIUC, the order cannot be changed in my case because of the "first one wins" strategy of `mergeFonts` (I want all glyphs in `updated_glyphs.ps` replace those in `cidfont.ps.OTC.TC`). So I just tried breaking it into two commands:

```
mergefonts final_new_cidfont.ps updated_glyphs.ps cidfont.ps.OTC.TC
mergefonts -gx 2946 final_new_cidfont_sans_2946.ps final_new_cidfont.ps
```

It seems to work as I want.

**Comment by tamcy** [comment]
@kenlunde Copy that, thanks! I'll remember to add the slash from now on.

But wouldn't the transposed argument result in the `updated_glyphs.ps` file not replacing the glyphs of `cidfont.ps.OTC.TC` with the same CIDs (due to the first one wins strategy)?

**Comment by kenlunde** [comment]
@tamcy: You're right. If the "first one wins" strategy of _mergeFonts_ adversely affects your intentions, it generally means that you need to start employing mergeFonts mapping files that explicitly specify the glyphs to extract from a merge font, or to use _tx_ to subset the resulting font (the reult should be the same as using _mergeFonts_).

**Comment by tamcy** [comment]
@kenlunde Thanks.

>use tx to subset the resulting font (the reult should be the same as using mergeFonts).

Just for curiosity do you mean `tx` can achieve effectively the same as the following command?
```
# Reads input.ps, throws away CID 2946, writes to output.ps
mergefonts -gx /2946 output.ps input.ps
```
If yes, can you provide an example to sort of "translating" it to the `tx` command? I actually tried, but no success.

**Comment by kenlunde** [comment]
`% tx -t1 -gx /2946 output.ps input.ps`

**Comment by tamcy** [comment]
@kenlunde It works! What I forgot is the `-t1` switch. Thanks a lot! 

Things are clear now, so I'll close this issue. Thanks again for the help.

**Comment by kenlunde** [comment]
🍻
