### ISSUE TITLE
makeotf error!?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#1408]
Makeotf 3.6.2 can compile a feature file, but makeotf 3.7.1 can not compile the feature file?
![图片](https://user-images.githubusercontent.com/5868202/132099404-9dcf0143-b1ff-4a05-a505-0f1010ab8687.png)

**Comment by frankrolf** [comment]
Would it be possible for you to share the feature file in question?

**Comment by mhjy** [comment]
[Oyun_Feature_Common.txt](https://github.com/adobe-type-tools/afdko/files/7135605/Oyun_Feature_Common.txt)
[Oyun_fina.txt](https://github.com/adobe-type-tools/afdko/files/7135606/Oyun_fina.txt)
[Oyun_fina_FVS.txt](https://github.com/adobe-type-tools/afdko/files/7135607/Oyun_fina_FVS.txt)
[Oyun_Group.txt](https://github.com/adobe-type-tools/afdko/files/7135608/Oyun_Group.txt)
[Oyun_init.txt](https://github.com/adobe-type-tools/afdko/files/7135610/Oyun_init.txt)
[Oyun_init_FVS.txt](https://github.com/adobe-type-tools/afdko/files/7135611/Oyun_init_FVS.txt)
[Oyun_isol_FVS.txt](https://github.com/adobe-type-tools/afdko/files/7135612/Oyun_isol_FVS.txt)
[Oyun_medi.txt](https://github.com/adobe-type-tools/afdko/files/7135613/Oyun_medi.txt)
[Oyun_medi_FVS.txt](https://github.com/adobe-type-tools/afdko/files/7135614/Oyun_medi_FVS.txt)
[Oyun_MVS.txt](https://github.com/adobe-type-tools/afdko/files/7135615/Oyun_MVS.txt)
[Oyun_nameinfo.txt](https://github.com/adobe-type-tools/afdko/files/7135616/Oyun_nameinfo.txt)
[Oyun_OS2_Table_Common.txt](https://github.com/adobe-type-tools/afdko/files/7135617/Oyun_OS2_Table_Common.txt)

**Comment by mhjy** [comment]
Oyun_font.GOADB and Oyun_QaganTig_Shine_PS.ttf
[Rule_Oyun_Shine.zip](https://github.com/adobe-type-tools/afdko/files/7135634/Rule_Oyun_Shine.zip)

**Comment by mhjy** [comment]
[Text25914（new）.zip](https://github.com/adobe-type-tools/afdko/files/7135650/Text25914.new.zip)

**Comment by punchcutter** [comment]
There's a problem reading the inline comments like in the name table. It's showing up for me with messed up encoding like this, but encoding doesn't seem to be the problem...

```
		nameid 0 1 "";
		nameid 0 3 "";


		nameid 7 "Oyun Traditional Mongolia Version 2.001";   #…Ã±Í
		nameid 7 1 "Oyun Traditional Mongolia Version 2.001";
		nameid 7 3 "Oyun Traditional Mongolia Version 2.001";

		nameid 8 "\5185\8499\53E4\5927\5B66\8BA1\7B97\673A\5B66\9662 Collage of Computer Science Inner Mongolia University http://ccs.imu.edu.cn  Email:1020753800@qq.com";   #¬Ù…Ã
		nameid 8 1 "\5185\8499\53E4\5927\5B66\8BA1\7B97\673A\5B66\9662 Collage of Computer Science Inner Mongolia University http://ccs.imu.edu.cn  Email:1020753800@qq.com";
		#nameid 8 3  "\5185\8499\53E4\5927\5B66\8BA1\7B97\673A\5B66\9662 Collage of Computer Science Inner Mongolia University. http://ccs.imu.edu.cn  Email:1020753800@qq.com";
		
		nameid 9 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";    # Unicode   …Ëº∆ ¶
		nameid 9 1 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";      # Macintosh(Mac Roman)
		nameid 9 3 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";      # Windows

		nameid 10 1 "";   #√Ë ˆ
		nameid 10 3 "";

		nameid 11 1 "http://ccs.imu.edu.cn ";   #¬Ù…ÃÕ¯’æ
		nameid 11 3 "http://ccs.imu.edu.cn";

		nameid 12 1 "http://ccs.imu.edu.cn ";   #…Ëº∆ ¶Õ¯’æ
		nameid 12 3 "http://ccs.imu.edu.cn";

		nameid 13 1 "";   #–Ìø…–≠“È
		nameid 13 3 "";

		nameid 14 1 "http://ccs.imu.edu.cn";   #–Ìø…Õ¯’æ
		nameid 14 3 "http://ccs.imu.edu.cn";

```
It will build if you remove all of the comments to have this:


```
		nameid 7 "Oyun Traditional Mongolia Version 2.001";
		nameid 7 1 "Oyun Traditional Mongolia Version 2.001";
		nameid 7 3 "Oyun Traditional Mongolia Version 2.001";

		nameid 8 "\5185\8499\53E4\5927\5B66\8BA1\7B97\673A\5B66\9662 Collage of Computer Science Inner Mongolia University http://ccs.imu.edu.cn  Email:1020753800@qq.com";
		nameid 8 1 "\5185\8499\53E4\5927\5B66\8BA1\7B97\673A\5B66\9662 Collage of Computer Science Inner Mongolia University http://ccs.imu.edu.cn  Email:1020753800@qq.com";
		
		nameid 9 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";
		nameid 9 1 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";
		nameid 9 3 "Email: 1020753800@qq.com Designer:  Email: 1020753800@qq.com";

		nameid 11 1 "http://ccs.imu.edu.cn ";
		nameid 11 3 "http://ccs.imu.edu.cn";

		nameid 12 1 "http://ccs.imu.edu.cn ";
		nameid 12 3 "http://ccs.imu.edu.cn";

		nameid 14 1 "http://ccs.imu.edu.cn";
		nameid 14 3 "http://ccs.imu.edu.cn";

```

Also, totally unrelated, but in the name table you have "Collage" instead of "College".

**Comment by iterumllc** [comment]
On initial examination it appears that your comments are not UTF-8 encoded.

The old feature-file parser handled comments in a somewhat ad-hoc way. The new parser requires that the entire file be encoded as UTF-8. (Strings have needed to be UTF-8 for some time and the rest of the spec uses 7-bit-ASCII characters, but this requirement was not spelled out when it comes to comment characters. We'll do that in a future revision.)

I'm afraid that just by looking at your files I can't tell the intended encoding of the comments. If you give some more information about the comments and your preferred text editor I might be able to help you convert everything to UTF-8.

**Comment by iterumllc** [comment]
(Once the comments are fixed there is a remaining issue of empty strings, which are currently causing an error. This is probably something that will be changed in an upcoming release, either to make empty strings a warning or to accept them without any message. You can temporarily work around this problem by adding a space to the empty strings.)

**Comment by mhjy** [comment]
I alway use VS2019 or NotePad.

**Comment by mhjy** [comment]
I have removed it to comment, but the error still comes out.

**Comment by josh-hadley** [comment]
Hi @mhjy  -- you might have missed the other part of @punchcutter's reply, which is to remove the empty name string entries like these:
```
		nameid 0 1 "";
		nameid 0 3 "";
```
(and others with "" as the string)

Currently, `makeotfexe` will error out on these. I've created #1411 which is a request to issue a warning instead of an error for such cases.

**Comment by mhjy** [comment]
All the fea file must  use UTF-8 format.
