### ISSUE TITLE
FDK environment variable

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#141]
I am controling the FDK with the help of batch files. So it would not be necessary to set the path to the FDK as environment variable.

If I for example command:

C:\FDK\Tools\win\Python\AFDKOPython27\python.exe C:\FDK\Tools\SharedData\FDKScripts\autohint.py -h

in my batch file and the environment variable is not set, I am asked to reinstall the FDK, because TX was not found (as far as I remember).

But this means, that you cannot use different versions of the FDK parallel, doesn't it?

Can't you specify relative pathes in the tools, so that they haven't to search for TX for example?

Or better: A kind of variables container file, in which all pathes are defined?

I have such a container in my batch file package. It is called FDKvars.bat. And this batch file is called by all other batch files.

**Comment by readroberts** [comment]
autohint.py will call 'tx' in a number of workflows, so it can't safely run if 'tx' can't be found. You are correct that every script which uses 'tx' or another tool could reference by a path relative to the current script.  However, doing that leads to some extra work if the location of 'tx' or of the calling scripts ever changes. I would think it is simpler to just override the PATH variable in your batch file by adding the desired FDK path to the beginning of the PATH string. Then you don't need to reference the absolute path in all the other lines:
set PATH=C:\FDK\Tools\win;%PATH%
autohint -h

**Comment by Arno-Enslin** [comment]
Thank you! That's a much better solution. But I set PATH additionally only in FDKvars.bat. In other words: This variable is only for the tools, that search for another script by themselves. For the commands in my batch files I keep the settings of absolute pathes.
