### ISSUE TITLE
With regard to FontLab macros in Public release 2.5 65314

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#143]
@ Read Roberts

You seem to have forgotten to include [the modules](https://github.com/adobe-type-tools/python-modules/tree/830e514f56ea4bea86e454dc47fbe648272e7da5).

Autohint.py does not work with some of the scripts contained in the modules.

**Comment by Arno-Enslin** [comment]
By the way, there seems to be an unbelievable mess now with the macros.

Today I was not able to make autohint.py work. This drives me crazy and for today I give up. And imagine, that I belong to those people, who are meanwhile a bit experienced with the AFDKO.

Would you have a look into the content of the folder "Tools/FontLab" from one of the old public releases, in which this folder was yet contained, please? I mean the orders of the folders and subfolders and their content.

Some of the scripts, that are needed for autohint.py seem to be in the AFDKO folder Shared Data/FDK scripts now.

Are you really sure, that you have fixed the bug in the autohint macro?

Somehow all this looks untested before release.

However, I try it again tomorrpw or on weekend. For today I am too frustrated. Sorry.

**Comment by Arno-Enslin** [comment]
There is a link ["Modules @ 830e514"](https://github.com/adobe-type-tools/python-modules/tree/830e514f56ea4bea86e454dc47fbe648272e7da5) in [adobe-type-tools/fontlab-scripts](https://github.com/adobe-type-tools/fontlab-scripts). BezChar.py contained in that tree direfctory is not the fixed one. The fixed BezChar.py is in the [master.](https://github.com/adobe-type-tools/python-modules).

And that is the reason for the error message, which I got.

Please change the link of "Modules @ 830e514" to the master modules directory.

However, I assume, that you will public release an update of the AFDKO soon, correct? Because in the public release the modules directory is empty.

Although this was a bit annoying: Thank you very much, that you have fixed the bug, which I hated the most! :-)




The folder "modules" with the bug fixed BezChar.py, that is necessary for autohint.py is there:

https://github.com/adobe-type-tools/python-modules

**Comment by Arno-Enslin** [comment]
There is one thing, which I don't understand yet: Is there a way to implement a check box for de-/activation of the generation of flex hints in the macro? You can do this from the command line, but actually not in the macro.

**Comment by readroberts** [comment]
For adding the no-flex option to the autohint macro, you just need to add some code to add the autohintexe option to the command line. Search AutoHint.py for all occurrences of "noHintSub", and duplicate the logic, changing the string to "noFlex".  When you copy and edit the if-else statement at line 436, change the string " -n" to + " -nf". Incidentally, I see that there is a bug here, as the "noHintSub" argument changed from " -n" to " -ns" sometime in the last 10 years.

The FontLab Macros were missing from the first copy of FDK 2.5 65314 that I pushed out to the Adobe web site. Unfortunately, although I pushed out a correct version a few minutes later, propagating updated files throughout the Akamai server network can take hours to a day or so. I will in any case have to push a new version in the next day, which will have a new file name, and will not have this problems

**Comment by Arno-Enslin** [comment]
> I see that there is a bug here, as the "noHintSub" argument changed from " -n" to " -ns" sometime in the last 10 years.

I also have seen that. But are you sure, that this is a bug? Aren't these arguments for autohintexe.exe, but not autohint.py? Autohintexe.exe has an option "-n" (no multiple layers of coloring). Is this the same as no hint substitution?

But have a look onto the class ACOptions in the macro AutoHint.py:
**self.noHintSubstitions = 0**
self.beVerbose = 1
**self.noHintSub = 0**

Is this intended?

--------------------------------------------

> Search AutoHint.py for all occurrences […]

Thanks! I will try that.

**Comment by readroberts** [comment]
You are right about  the '- ns' argument - I was looking at the arguments for the command-line autohint, not for autohintexe. No that I look at both, I see that adding an option to turn off flex in the AutoHint.py macro is not so simple, as it calls autohintexe directly, and the flexOK option is passed to autohintexe in the fontinfo file, not in the command line. You would need to check if the new option is true, and then append the required key-value to the fontinfo text after line 330, before the fontinfo text is written to to a temporary fontinfo file. The key pair is "FlexOK true" or "FlexOK false" .

**Comment by Arno-Enslin** [comment]
The default is true. So I don't need "else", correct?

```
if options.noFlex:
	?.append("FlexOK")
	?.append("false")
```

But I don't know, what I shall write in front of "append".

I assume, that the temprary fontinfo file from which you talk, is named n.fi, where n is a number.

There are also fontinfo files with the extension .nnn, fontinfo.000 for example. But this seems to be generated by BezChar.py. I am not sure. Remember, that I only draw conclusions by looking at the code, but I am not a Python programmer.

Well, you wrote, that you actually have not much time …
-----------------------------

I will check, if the actual options really work. A few years ago the option noHintSub was ignored by the script.

**Comment by Arno-Enslin** [comment]
Maybe also BezChar.py has to be modified, because "FlexOK true" is appended by BezChar.py

```
fontinfo.append("FlexOK")
fontinfo.append("true")
```

I assume, that FlexOK=true/false had to be send from Autohint.py to the function "GetACFontInfoFromFLFont" in BezChar.py, because that function is "called" by Autohint.py, before it writes the n.fi file.

**Comment by Arno-Enslin** [comment]
Don't forget to copy the file plistlib.py from SharedData/FDKScripts to FontLabMacros/System/Modules. Modules should be a subdirectory of the directory "System" in the FontLab Macros directory. And please check, if the directory FDKScripts contains more scripts, which formerly were in the FontLab Macros directory.

I never have used the other AFDKO Macros before, at least I cannot remember. But the Macro Autohint.py needs the scripts AdobeFontLabUtils.py, BezChar.py and plistlib.py -- all three files in FontLabMacros/System/Modules. If these files are in FontLabMacros/Modules the Macro Autohint.py does not work.

And for the future I would rename the macro Autohint.py to Autohint_FL_Macro.py because of the command line autohint.py. Otherwise users may think, both files are the same except from the first letter (A/a).

I still wonder, how you were able to test Autohint.py with the others scripts missing or in the wrong directory.

For the unleikely case, that you need the FiontLab directory from one of the old public releases of the AFDKO for the reconstruction of the directories and subdirectories, let me know, because I have collected many of the public releases of the AFDKO:

_AFDKO 1.6 build 6148 [TTX 2.0b1]
_AFDKO 2.0 build 21 [TTX 2.0b2]
_AFDKO 2.0 build 26 [TTX 2.0b2]
_AFDKO 2.5 21340 [TTX 2.2]
_AFDKO 2.5 21898 [TTX 2.2]
_AFDKO 2.5 58807 [TTX 2.3]
_AFDKO 2.5 60418
_AFDKO 2.5 62754 (May 14 2014)
_AFDKO 2.5 63209
_AFDKO 2.5 63782
_AFDKO 2.5 63882
_AFDKO 2.5 64655
_AFDKO 2.5 64958

**Comment by Arno-Enslin** [comment]
[Autohint.py and BezChar.py modified.zip](https://github.com/adobe-type-tools/afdko/files/288041/Autohint.py.and.BezChar.py.modified.zip)

Looks as if this works. And except from yours I had no help. It probably could be cleaned up. But if this works, I am bit proud. Because I have learned by comparing code.

**Comment by Arno-Enslin** [comment]
Mmh.

FlexOK true / FlexOK false seems to be written into the n.fi file (where n is a number) as it should. But if the generated font contains flex hints is dependent from FontLab FontInfo / Hinting Settings / Additional hinting parameters / Automatically generate Flex hints in T1 and OT-PS fonts.

I am not yet sure, if FontLab deletes the flex hints, which were created by the macro,  and if FontLab creates its own flex hints then, or if it keeps the flex hints, which were created by the macro. At least the generated font contains no flex hints, if the option "Automatically generate Flex hints in T1 and OT-PS fonts" is unchecked.

I have to test that.

**Comment by Arno-Enslin** [comment]
[Hinting and Hinting modules [bugfixed and with Flex-Option].zip](https://github.com/adobe-type-tools/afdko/files/288561/Hinting.and.Hinting.modules.bugfixed.and.with.Flex-Option.zip)

I have cleaned the code of my flex option supplements. And I have fixed the bug in the original Autohint.py (and naturally also in the version with the flex option). Now you can suppress hint substitutions.

I will test now, if the option "No Flex" makes sense, because it may be, that FontLab simply cannot store flex hints in a vfb file, but is only able to generate flex hints on the fly, when it generates Type 1 or PS flavored OTF.

If I come to the conclusion, that the flex option indeed makes sense, I will propose, that you replace the original Autohint.py and BezChar.py with the flex option versions.

If it does not make sense, I will create a pull request for the bugfixed version of the original Autohint.py.

But for the case, that you don't want to wait with the updated public release, I propose, that you replace the original Autohint.py with my bugfixed version of the original Autohint.py.

**Comment by Arno-Enslin** [comment]
Here my test:

Test font: Adobe Garamond Pro Regular

1. Speed

Speed without flex hints: 38.9 seconds
Speed with flex hints: 36.2 seconds
Difference: 2.7 seconds

So the Macro is faster, if it lets Autohintexe.exe create flex hints. Unexpected result.
The default of the original BezChar function "GetACFontInfoFromFLFont" is "FlexOK true". And this is with regard to the speed good.

2. Flex hints in the generated OTF

I have tested glyphs "E" and "T" only.

For the moment I attach the decompiled CharStrings only. Tomorrow I will compare them. (It's not easy.) And then I will edit this post.

[E and T.zip](https://github.com/adobe-type-tools/afdko/files/288613/E.and.T.zip)

**Comment by Arno-Enslin** [comment]
It is impossible to autohint a font with flex hints in FontLab with Autohint.py with the same result as from the command line, because FontLab is obviously unable to store the flex hints, that Autohint.py creates

And some of the regular hints, that autohintexe creates, can be different, if you suppress flex hints. If autohintexe runs with flex hints activated, it seems to prepare some of the regular hints for the flex hints.

In my opinion the macro is only useful, if your font shall not contain flex hints. Otherwise it is better to autohint the font from the command line.

And instinctivly I would say, that, if you want to generate a font in FontLab with flex hints and the autohint macro, you should let run the modified macro with no-flex option activated. And the you let FontLab create the flex hints.

But because you cannot turn of flex hint generation in the original macro dialog, I propose to replace the original Autohint.py and BezChar.py with the files, in which I have added the no-flex option.

**Comment by miguelsousa** [comment]
The FontLab macros are no longer part of the AFDKO. They were moved to https://github.com/adobe-type-tools/fontlab-scripts and any issues should be reported there.
