### ISSUE TITLE
Generating CFF2 tables

### ISSUE THREAD

**Issue by tkacvins** [adobe-type-tools/afdko#1437]
I read the `makeotf` docs but did not see if you can force `CFF2` over `CFF1`.  I am guessing if one provides a multiple master `Type 1` input, then `CFF2` will be used, otherwise the default is `CFF1`.  I just want to experiment some with `CFF2` data for a third party tool I am working with, and though that generating a `CFF2` table via `makeotf` would be a nice way of getting that kind of data.  Or do I need to use something like `FontLab` to get a `CFF2` based `OTF` font?

**Comment by khaledhosny** [comment]
`tx` can convert `CFF` to`CFF2`.

**Comment by tkacvins** [comment]
OK, I generated an OTF with a `CFF ` table, than ran `tx -cff2 +S font.otf > font.cff2`.  Then i used `sfntedit -a CFF2=font.cff2 font.cff2` followed by `sfntedit -d 'CFF ' font.otf`.  The results do not look correct at in the font preview feature of `macOS Big Sur 11.16.1`.  My suspicion is that the `cmap` table is off, but I don't know how to diagnose this further.  I am attaching the font in question.  If you have any recommendations as to what I did wrong. I'd appreciate hearing it.

[cmbx10_cff2.otf.zip](https://github.com/adobe-type-tools/afdko/files/7678074/cmbx10_cff2.otf.zip)
.

**Comment by khaledhosny** [comment]
You need to pass `+b` to `tx` to keep the original glyph order.

**Comment by tkacvins** [comment]
Perfect!  Thank you so much!

**Comment by tkacvins** [comment]
The above hint got me on my way.
