### ISSUE TITLE
Contextual decomposition bug?

### ISSUE THREAD

**Issue by ohbendy** [adobe-type-tools/afdko#144]
It seems there might be a bug preventing a contextual one-to-many substitution. This error message is generated when trying to compile in Glyphs:
<img width="845" alt="screen shot 2016-06-19 at 18 56 46" src="https://cloud.githubusercontent.com/assets/12471463/16179853/750ea9ea-366a-11e6-8e6f-aa857388c9c5.png">
I get the same error whichever feature this lookup is in.

**Comment by miguelsousa** [comment]
You need to define the one-to-many substitution in a standalone lookup, and then use that lookup contextually. Here's an [example from the specification](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html):

```
lookup CNTXT_LIGS {
     substitute f i by f_i;
     substitute c t by c_t;
 } CNTXT_LIGS;
 
lookup CNTXT_SUB {
     substitute n by n.end;
     substitute s by s.end;
 } CNTXT_SUB;
 
feature test {
     substitute [a e i o u] f' lookup CNTXT_LIGS i' n' lookup CNTXT_SUB;
     substitute [a e i o u] c' lookup CNTXT_LIGS t' s' lookup CNTXT_SUB;
 } test;
```

**Comment by ohbendy** [comment]
Ah, this is expected behaviour? I hadn't seen anything suggesting a one-to-many substitution could only be contextual by chaining lookups that way. Thanks Miguel, good to know there's a way to do it.
