### ISSUE TITLE
macOS universal binaries for AFDKO?

### ISSUE THREAD

**Issue by tkacvins** [adobe-type-tools/afdko#1453]
I do believe that macOS on M1 silicon systems supports running Intel based based Python modules (the ones that are built from C/C++ source, using the Python C API, or use cython, or ctypes, etc...), but I wanted to know if there were any plans on making the binaries in the pip packages universal binaries.

**Comment by josh-hadley** [comment]
Yes, we've been [working on this](https://github.com/adobe-type-tools/afdko/tree/drop-py3.6-add-py3.10) as well as adding Python 3.10 support (and dropping 3.6 support), running into some issues with the build system that we hope to work out shortly. If you have any suggestions to help get things working, we'd be glad to entertain them.

**Comment by tkacvins** [comment]
@josh-hadley Thanks for working on this.  I have Xcode, but don't yet have access to an M1 silicon machine to test what is built.

**Comment by miguelsousa** [comment]
@tkacvins A pre-release build was added in #1461. Anyone can try it out by running,

    pip3 install -U afdko --pre

**Comment by tkacvins** [comment]
> @tkacvins A pre-release build was added in #1461. Anyone can try it out by running,
> 
> ```
> pip3 install -U afdko --pre
> ```

Unfortunately, `tx` is not a universal binary:

```
(afdko_env_2) athena:~ tjk$ file /Users/tjk/afdko_env_2/bin/tx
/Users/tjk/afdko_env_2/bin/tx: Mach-O 64-bit executable x86_64
```

This is after running `pip3 install -U afdko --pre`

**Comment by tkacvins** [comment]
Of note, the `venv` I have set up is with the universal binary `Python` from `python.org`, not the macOS stock `python3`, which on my Intel based MacBook Pro is an `x86_64` executable.  In case that makes any difference for the version of `afdko` that is `pip` installed

**Comment by miguelsousa** [comment]
Interesting. Thanks for checking.

**Comment by miguelsousa** [comment]
Perhaps we need to add the `universal2` wheel as well.

**Comment by miguelsousa** [comment]
I checked the binaries inside the wheels today on my **Intel** Mac, and AFAICT they have the correct stuff.
<img width="1652" alt="tx_arm64" src="https://user-images.githubusercontent.com/2119742/150181088-81b86984-c9bf-4970-b443-5b54868bbba8.png">
<img width="1652" alt="tx_x86_64" src="https://user-images.githubusercontent.com/2119742/150181102-3eed7a49-8212-4636-8b0b-73ccd2ecfec6.png">

**Comment by tkacvins** [comment]
`file $(which tx)` shsould return something like

```
(afdko_env_2) athena:~ tjk$ file $(which tc)
/Users/tjk/afdko_env_2/bin/tx: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Users/tjk/afdko_env_2/bin/tx (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Users/tjk/afdko_env_2/bin/tx (for architecture arm64):	Mach-O 64-bit executable arm64
```
Indicating `tx` is indeed a universal binary, but on my Intel MacBook Pro, running Big Sur 11.6.3, `file $Which tx)` returns just this
```
(afdko_env_2) athena:~ tjk$ file $(which tx)
/Users/tjk/afdko_env_2/bin/tx: Mach-O 64-bit executable x86_64
```

**Comment by miguelsousa** [comment]
Pre-release universal wheel available at https://pypi.org/project/afdko/3.8.0b0/#files

**Comment by tkacvins** [comment]
@miguelsousa - worked perfectly, thank you!

**Comment by josh-hadley** [comment]
[v3.8.0 Release](https://github.com/adobe-type-tools/afdko/releases/tag/3.8.0) is out that addresses this, closing now.
