### ISSUE TITLE
[tx/UFO] replace homemade XML parser with libxml2 for UFO

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#1468]
http://xmlsoft.org/

**Comment by miguelsousa** [comment]
[We've thought about it](https://github.com/adobe-type-tools/afdko/issues/475) back in the distant year of 2018 😁

**Comment by kaydeearts** [comment]
Renamed this title to be UFO-specific as that was our priority within this project. I made an SVG-parsing specific issue here: https://github.com/adobe-type-tools/afdko/issues/1567

This project has now been completed with the PRs referenced above.
