### ISSUE TITLE
[makeotfexe] Unable to execute on Windows after updating to 3.8.0

### ISSUE THREAD

**Issue by tamcy** [adobe-type-tools/afdko#1473]
Hi,

I am seeing the following error messages when trying to run `makeotfexe` on Windows after updating to 3.8.0, complaining about missing `libstdc++-6.dll` and `libgcc_s_seh-1.dll`:

![afdko380-makeotfexe-error-2](https://user-images.githubusercontent.com/959433/155270077-1847e9bb-9ee1-48a7-8e92-28b697c28909.png)
![afdko380-makeotfexe-error-1](https://user-images.githubusercontent.com/959433/155270080-778a2889-34c1-404f-962d-f773d081c9a7.png)

While it might be possible to download and copy these files into the PATH manually, I doubt if the package is meant to work this way, so I am reporting here.

Some obvervations:
- Other tools seems fine.
- Incidentally I've downloaded and tried 3.8.0b0 before, which doesn't exhibit such an error.
- The file size of `makeotfexe.exe` grew significantly in 3.8.0. It was around 1.3MB, now it's 2.6MB.

**Comment by tamcy** [comment]
@josh-hadley Thanks for the help! I can verify that the issue has been resolved on my Windows 10 with Python 3.8.3 using the command you provided (which installs `afdko-3.8.1a0`).

**Comment by josh-hadley** [comment]
@tamcy -- great, thank you for testing and confirming. We will be making a 3.8.1 final release soon but for now you can continue using the pre-release version.

**Comment by josh-hadley** [comment]
AFDKO 3.8.1 has been released which fully resolves this issue. You can update to that with `pip install --update afdko`.
