### ISSUE TITLE
makeotf: bug about feature file (build 65322)

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#149]
The font project directory tree as below:

```
Project/
    Regular/
        generate.cmd // to execute makeotf and other commands
        fontinfo
        font.pfa
    feature
    feature.vert
```

Following contents are in the 'feature' file:

```
include (..\table_vert);
...
```

My last FDK was build 64655, it runs smoothly. On build 65322, makeotf will prompt:
`makeotfexe [FATAL] include file <..\feature.vert> not found [..\feature 1]`

I edited the 'feature' file to:

```
include (table_vert);
...
```

But another Python error will be prompted:
`NameError: global name 'familyFilePath' is not defined`

So I modified the code of 'MakeOTF.py', start at line 1460, from:

```
for file in includeList:
    apath = os.path.abspath(file)
    if not os.path.exists(apath):
        fdir = os.path.dirname(familyFilePath)
        apath = os.path.join(fdir, file)
        foundVert = checkIfVertInFeature(apath)
        if foundVert:
            break

return foundVert
```

Replaced by:

```
for file in includeList:
    apath = os.path.join(os.path.dirname(featurePath), file)
    foundVert = checkIfVertInFeature(apath)
    if foundVert:
        break

return foundVert
```

It can finally work properly, and will not prompt the false warning with `vert` (Issus #148).

**Comment by miguelsousa** [comment]
Duplicate issue #158
