### ISSUE TITLE
Consider SEQUITUR (Nevill-Manning) or Re-pair algorithm in subroutinization.

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#150]
The SEQUITUR is an algorithm that forms a CF Grammar from an input string in linear time. I think it can be used in CFF subroutinization with some slight modifications:
1. SEQUITUR is used to compress one string, but CFF CharStrings are multiple characters. Solution: in the two-component searching part, when any one in them is ENDCHAR, than add it directly to rule _S_.
2. The recursion depth and subroutine quantity limit. May be work-arounded by expanding some subroutine calls into their expanded form.

**Comment by miguelsousa** [comment]
@blueshade7 is this worth exploring or is the current subroutinizer good enough?

**Comment by readroberts** [comment]
This sounds to me like an interesting idea, but not compelling enough for me to spend time on in the near future. If anyone wants to volunteer the time to investigate this, I am all for supporting them.
