### ISSUE TITLE
[OT Feature File Specification] Paragraph 6.b.iii. — Typo obscures meaning

### ISSUE THREAD

**Issue by alex-phil** [adobe-type-tools/afdko#1507]
Please take a look at the following paragraph of the OpenType Feature File Specification. The sentence indicated in my screenshot should obviously end with the expression “[are set to] 0.” But that seems to trigger the creation of a numbered list, thereby obscuring the meaning of the entire context. Please review.

http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6biii-subtable-breaks

<img width="1037" alt="Subtable-breaks" src="https://user-images.githubusercontent.com/93643547/167316506-1a00cc43-70b7-469c-a957-66d031b6e604.png">

**Comment by miguelsousa** [comment]
@josh-hadley The change didn't fix it. Perhaps some copy editing is required: "set to 0." → "set to 0 (zero)."

<img width="1094" alt="Screen Shot 2022-05-09 at 10 41 11" src="https://user-images.githubusercontent.com/2119742/167466936-4418e626-ae32-4927-a1b6-3627f569c490.png">

**Comment by josh-hadley** [comment]
Merged & confirmed fix in Pages site: https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6.b.iii

**Comment by alex-phil** [comment]
Thank you for fixing the text.
