### ISSUE TITLE
Will the outline and glyphs lost when converting Type1 font to OTF font?

### ISSUE THREAD

**Issue by Firestar-Reimu** [adobe-type-tools/afdko#1513]
Will the outline and glyphs lost when converting Type1 font to OTF font?

according to https://fontforge.org/docs/faq.html#faq-outline-conversion

type1 and otf both use cubic splines, so I wonder outline, glyphs, ligatures, lookups and features will lost when converting Type1 font to OTF font.

or, **what will lost when converting Type1 font to OTF font**

**Comment by skef** [comment]
Type1 fonts do not have "lookups" or "features" in the OpenType sense. They contain glyphs in an *encoding*. Support for ligatures, when present, is through the encoding (such as Adobe Latin 2). 

A tool that claims to be able to convert from Type1 to OTF should be able to convert all the outlines, which (if the OTF is CFF-based) have similar storage formats). Unicode has slots for the limited set of ligatures that are available in the older encodings so they should be present in the converted font but font-consuming software may not make use of them without adding a `liga` feature and associated lookups.

**Comment by frankrolf** [comment]
At the risk of commenting on a very old issue – when converting a Type 1 font to OTF (requested method not specified), you should not lose any outlines or glyphs.

I will close this issue because the original question is a little vague, please re-open if you have a concrete example in mind :-)
