### ISSUE TITLE
Document current glyph name syntax

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#152]
According to [§2.f.i of the OpenType Feature File syntax](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#2.f.i), glyph names must not contain hyphens. However, @readroberts wrote in https://github.com/fonttools/fonttools/issues/559#issuecomment-224007849 that makeotf has been changed to accept glyph names with `- + * : ~ ^ !`. This was done so that makeotf could support workflows where features get compiled on fonts that have “development” glyph names. Could the spec be amended to reflect what’s currently accepted? The spec might still want to contain a warning that when a font uses these characters, it will contain invalid PostScript and Type 1 names.

**Comment by brawer** [comment]
@readroberts, mind updating §2.f.i of the AFDKO spec?

**Comment by readroberts** [comment]
Done. v1.20 [6 Feb 2017]: Updated glyph name rules in section 2.f.i glyph name to allow additional characters for development names. Added rule for disambiguating range from glyph name that contains a hyphen.

**Comment by brawer** [comment]
Thank you! Mind pushing the change, or tell the new wording of the spec? Currently, the [master](https://github.com/adobe-type-tools/afdko/blob/master/FDK/Technical%20Documentation/OpenTypeFeatureFileSpecification.html) is still on version 1.19.
