### ISSUE TITLE
Value for underlinePosition differ in <post> and <CFF>

### ISSUE THREAD

**Issue by supertype-de** [adobe-type-tools/afdko#1531]
I'm generating .otf from RoboFont and found that my value for postscriptUnderlinePosition is correcly applied in the `CFF` table but not in the `post` table. I expected `-90` in `post` but got `-55`. The value for `underlineThickness` is correctly applied in both tables.
Wrong `underlinePosition`, correct `underlineThickness` (data from ttx)
```
<post>
    <underlinePosition value="-55"/>
    <underlineThickness value="70"/>
</post>
```
Correct `underlinePosition`, correct `underlineThickness` (data from ttx)
```
<CFF>
    <UnderlinePosition value="-90"/>
    <UnderlineThickness value="70"/>
</CFF>
```

**Comment by supertype-de** [comment]
@josh-hadley , this issue was really just a misunderstanding then. Thank you for your explanation.

**Comment by josh-hadley** [comment]
You're welcome – it was a bit of an adventure 😸 . While investigating this, I did note a possible issue in RoboFont: an RF-generated UFO seems to use the underlinePosition value from the post table for `postscriptUnderlinePosition`. So in a cycle of OTF -> UFO -> OTF the `makeotf` conversion of the value will happen each time. I'm not sure whether this is an actual problem for RF users, maybe @typemytype has some thoughts on that.
