### ISSUE TITLE
[makeotfexe] Only first ligature caret in first ligature is used

### ISSUE THREAD

**Issue by taejo** [adobe-type-tools/afdko#155]
With this feature file
```
table GDEF {
    LigatureCaretByPos f_f_i 1 2;
    LigatureCaretByPos f_i 1;
} GDEF;
```
`makeotf` issues the following warning
```
makeotfexe [WARNING] <Untitled2> GDEF Ligature Caret List Table. Glyph 'f_f_i' gid '3'.
 A glyph can have at most one ligature caret device  statement and one of either
 ligature caret by position or ligature caret by index statetment. Skipping entry for format '1'.
```
and outputs a GDEF table which only has a single caret for `f_f_i` and none for `f_i`:
```
  <GDEF>
    <Version value="0x00010000"/>
    <LigCaretList>
      <Coverage Format="1">
        <Glyph value="f_f_i"/>
      </Coverage>
      <!-- LigGlyphCount=1 -->
      <LigGlyph index="0">
        <!-- CaretCount=1 -->
        <CaretValue index="0" Format="1">
          <Coordinate value="1"/>
        </CaretValue>
      </LigGlyph>
    </LigCaretList>
  </GDEF>
```

Unless I am completely misunderstanding the spec, there should be two coordinates for `f_f_i` and one for `f_i`, instead of one and none respectively.

**Comment by taejo** [comment]
I wasn't able to understand the code that produces the warning exactly, but this code in commit `a06b6f61` is clearly wrong:

+                    if (((lge->caretTables.array[j].format == 1) &&
+                         (lge->caretTables.array[j].format == 2))
+                        ||
+                        ((lge->caretTables.array[j].format == 2) &&
+                         (lge->caretTables.array[j].format == 1)))

**Comment by behdad** [comment]
cc @brawer

**Comment by miguelsousa** [comment]
@cjchapman I've created branch `gdef-bug155` that contains tests that capture the current output.
I think you'll also need to consult these:
* [GDEF section in feature file syntax spec](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.b)
* [GDEF table spec](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#gdef-header)
