### ISSUE TITLE
How to use the unicode U11660-1166D in font?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#1564]
I add the Mongolian Supplement (11660-1166D) in my font, and use AFDKO to compile the font. The AFDKO return the message bellow:
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'null'. Only the first ('0000') will be used. Additional Unicode value: 00000000
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'space'. Only the first ('00000020') will be used. Additional Unicode value: 0020
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'exclam'. Only the first ('00000021') will be used. Additional Unicode value: 0021
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'quotedbl'. Only the first ('00000022') will be used. Additional Unicode value: 0022
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'numbersign'. Only the first ('00000023') will be used. Additional Unicode value: 0023
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'dollar'. Only the first ('00000024') will be used. Additional Unicode value: 0024
makeotf [Warning] Source TTF font contains multiple Unicode values for glyph 'percent'. Only the first ('00000025') will be used. Additional Unicode value: 0025
。。。。。。。。

if I remove the Mongolian Supplement (11660-1166D) from my font, the result is ok.

**Comment by punchcutter** [comment]
How are you adding the Mongolian Supplement? What commands and tools are you using for this? What are the sources?

**Comment by mhjy** [comment]
I use the FontCreator and add the Mongolian Supplement glyaph to the ttf file. after I use the  makeotf to compile the OpenType feature .

**Comment by mhjy** [comment]
this is my  ttf file.
[Oyun_QaganTig_Shine_PS.zip](https://github.com/adobe-type-tools/afdko/files/9714785/Oyun_QaganTig_Shine_PS.zip)

**Comment by punchcutter** [comment]
Why don't you add everything in FontCreator? You can add the OpenType features and everything else you need in FontCreator and you don't need to use makeotf separately.

**Comment by mhjy** [comment]
Because feature is very complex. Also, there are other functions that can't be used by FontCreator. Maybe I'm not good with FontCreator yet.

**Comment by mhjy** [comment]
Because the my feature is very complex. Also, there are other functions that can't be used by FontCreator. Maybe I'm not good with FontCreator yet.

**Comment by punchcutter** [comment]
FontCreator can really do a lot so I'd be surprised if it can't do what you need.

**Comment by mhjy** [comment]
the is my correct  ttf file with OpenType feature.
[OyunQaganTig.zip](https://github.com/adobe-type-tools/afdko/files/9714866/OyunQaganTig.zip)

**Comment by mhjy** [comment]
I develop 90 font file that they use same feature。if I write the feature use the fontcreator, it more difficult to modify the feature in every font .

**Comment by punchcutter** [comment]
Ah, I checked your TTFs and it seems that the only problem is all glyphs have two Unicode values assigned, but they are all identical. Like 0x189a and 0x0000189a which has no reason to be there. Something must have happened when adding the Supplement glyphs since they must be in the full range like 0x00011667 and cannot be represented the other way. So I don't think there's any problem except that maybe FontCreator added the extra field and makeotf doesn't like it because it's redundant.

**Comment by mhjy** [comment]
1、CMAP of without 11660-1166C:
    <cmap_format_4 platformID="0" platEncID="3" language="0">
    </cmap_format_4>
    <cmap_format_0 platformID="1" platEncID="0" language="0">
    </cmap_format_0>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
    </cmap_format_4>
2、CMAP of with 11660-1166C:
    <cmap_format_4 platformID="0" platEncID="3" language="0">
    </cmap_format_4>
    <cmap_format_12 platformID="0" platEncID="4" format="12" reserved="0" length="1852" language="0" nGroups="153">
     
      <map code="0x11660" name="uni11660"/>
      <map code="0x11661" name="uni11661"/>
      <map code="0x11662" name="uni11662"/>
      <map code="0x11663" name="uni11663"/>
      <map code="0x11664" name="uni11664"/>
      <map code="0x11665" name="uni11665"/>
      <map code="0x11666" name="uni11666"/>
      <map code="0x11667" name="uni11667"/>
      <map code="0x11668" name="uni11668"/>
      <map code="0x11669" name="uni11669"/>
      <map code="0x1166a" name="uni1166A"/>
      <map code="0x1166b" name="uni1166B"/>
      <map code="0x1166c" name="uni1166C"/>
    </cmap_format_12>
    <cmap_format_0 platformID="1" platEncID="0" language="0">
    </cmap_format_0>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
    </cmap_format_4>
    <cmap_format_12 platformID="3" platEncID="10" format="12" reserved="0" length="1852" language="0" nGroups="153">

      <map code="0x11660" name="uni11660"/>
      <map code="0x11661" name="uni11661"/>
      <map code="0x11662" name="uni11662"/>
      <map code="0x11663" name="uni11663"/>
      <map code="0x11664" name="uni11664"/>
      <map code="0x11665" name="uni11665"/>
      <map code="0x11666" name="uni11666"/>
      <map code="0x11667" name="uni11667"/>
      <map code="0x11668" name="uni11668"/>
      <map code="0x11669" name="uni11669"/>
      <map code="0x1166a" name="uni1166A"/>
      <map code="0x1166b" name="uni1166B"/>
      <map code="0x1166c" name="uni1166C"/>
    </cmap_format_12>

**Comment by mhjy** [comment]
1、CMAP of without 11660-1166C:
    <cmap_format_4 platformID="0" platEncID="3" language="0">
    </cmap_format_4>
    <cmap_format_0 platformID="1" platEncID="0" language="0">
    </cmap_format_0>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
    </cmap_format_4>

**Comment by mhjy** [comment]
2、CMAP of with 11660-1166C:
    <cmap_format_4 platformID="0" platEncID="3" language="0">
    </cmap_format_4>
    <cmap_format_12 platformID="0" platEncID="4" format="12" reserved="0" length="1852" language="0" nGroups="153">
     
      <map code="0x11660" name="uni11660"/>
      <map code="0x11661" name="uni11661"/>
      <map code="0x11662" name="uni11662"/>
      <map code="0x11663" name="uni11663"/>
      <map code="0x11664" name="uni11664"/>
      <map code="0x11665" name="uni11665"/>
      <map code="0x11666" name="uni11666"/>
      <map code="0x11667" name="uni11667"/>
      <map code="0x11668" name="uni11668"/>
      <map code="0x11669" name="uni11669"/>
      <map code="0x1166a" name="uni1166A"/>
      <map code="0x1166b" name="uni1166B"/>
      <map code="0x1166c" name="uni1166C"/>
    </cmap_format_12>
    <cmap_format_0 platformID="1" platEncID="0" language="0">
    </cmap_format_0>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
    </cmap_format_4>
    <cmap_format_12 platformID="3" platEncID="10" format="12" reserved="0" length="1852" language="0" nGroups="153">

      <map code="0x11660" name="uni11660"/>
      <map code="0x11661" name="uni11661"/>
      <map code="0x11662" name="uni11662"/>
      <map code="0x11663" name="uni11663"/>
      <map code="0x11664" name="uni11664"/>
      <map code="0x11665" name="uni11665"/>
      <map code="0x11666" name="uni11666"/>
      <map code="0x11667" name="uni11667"/>
      <map code="0x11668" name="uni11668"/>
      <map code="0x11669" name="uni11669"/>
      <map code="0x1166a" name="uni1166A"/>
      <map code="0x1166b" name="uni1166B"/>
      <map code="0x1166c" name="uni1166C"/>
    </cmap_format_12>

**Comment by punchcutter** [comment]
I don't think there's anything to be done here. Those cmaps came from somewhere else and I don't see a problem with afdko.

**Comment by mhjy** [comment]
I have solved the problem:
(1)using FontCreator to export the .ttf(No.1) file (cmap table  include the format 4 and 12)
(2)using TTX -t cmap to export the .ttx file.
(3)using makeotf to complite the .ttf(nO.1) file and .fea, ganerate the .ttf(No.2) file include OpenType featrue, but missing format=12 cmap table.
(4)using TTX -m complite the cmap .ttx file to .ttf(No.2).
