### ISSUE TITLE
tx error with Blues

### ISSUE THREAD

**Issue by BlackFoundry** [adobe-type-tools/afdko#157]
Issue when trying to compile a font that has no PostScript 'Blues' but has 'Other Blues':

makeotf [Note] Converting source font 'font.otf' to temporary Unix Type1 font file 'font.otf.tmp'.
makeotf [Error] Failed to convert input font 'font.otf' to temp file 'font.otf.tmp' with tx.
tx converting to T1 font: <tx: --- font.otf
tx: (cfr) invalid DICT array size
tx: fatal error
None

Unable to compile at all.
Could the error message be cleared?
Would it be possible to skip the error by clearing the 'Other Blues' if 'Blues' is empty ?

thanks,
Jérémie

**Comment by kenlunde** [comment]
From Section 5.3, _BlueValues_, on page 37 of the Black Book:

> The **BlueValues** array is required in the **Private** dictionary. If no alignment zones are necessary, use an empty array for the value of **BlueValues**:
> 
> `/BlueValues [ ] def`

**Comment by BlackFoundry** [comment]
Thank you !

**Comment by kenlunde** [comment]
🍻
