### ISSUE TITLE
[compareFamily] ValueError: invalid mode: 'rU' when running on Python 3.11

### ISSUE THREAD

**Issue by colinmford** [adobe-type-tools/afdko#1583]
I get the following traceback when trying to run `compareFamily` on Python 3.11:

```
Traceback (most recent call last):
  File "/Users/colinmford/MyProject/.venv/bin/compareFamily", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/colinmford/MyProject/.venv/lib/python3.11/site-packages/afdko/comparefamily.py", line 5013, in main
    fp = open(kAGD_TXTPath, "rU")
         ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```
The line in question: https://github.com/adobe-type-tools/afdko/blob/d380b726e7a2e10e88b74a486255a716bd8c4ae6/python/afdko/comparefamily.py#L5013

The `U`, Universal line endings, was deprecated with Python 3.4. I believe the default behavior now takes care of newlines by default without having to specify... so depending on your target Python versions, this can probably just become:

```python
fp = open(kAGD_TXTPath, "r")
```

LMK if you want a pull request — I'm unsure if you are targeting Python 3.11 yet or still need to support Python < 3.4.

**Comment by frankrolf** [comment]
Thanks Colin!
Confirming this issue on 3.11 (had to make the jump from 3.9!)

When fixing this, the example code in agd.py also should be fixed:
https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/agd.py#L8-L16

**Comment by josh-hadley** [comment]
@colinmford we aren't targeting 3.11 just yet as we have other dependencies that we need to confirm are updated for 3.11 and test.

That said, I don't think we need to wait for overall 3.11 support to take a fix for this specific problem, since it's been deprecated for quite a while already -- as long as the fix doesn't break anything in the versions we do support (3.7 through 3.10).

**Comment by colinmford** [comment]
@frankrolf @josh-hadley Thanks! Small PR #1584 ready for you guys.
