### ISSUE TITLE
[comparefamily] doSingleTest4 "Warning: Version string is not greater than 1.0000 for Font" - Typo + why?

### ISSUE THREAD

**Issue by colinmford** [adobe-type-tools/afdko#1592]
Besides the obvious — the error message has 4 decimal places in `1.0000` instead of the usual 3, probably a typo? — I was wondering, what is the reason for this warning? Fonts aren't allowed to be version 1.000?

See line 1613 for context.

https://github.com/adobe-type-tools/afdko/blob/184ae00ce34709dbb03c2847576f79d41da57fb3/python/afdko/comparefamily.py#L1612-L1613

**Comment by colinmford** [comment]
Should line 1612 be `if ver < 1.0`? Or is it only allowed to have fonts with version 1.001 and higher?

**Comment by frankrolf** [comment]
From a conversation with Read Roberts:
```
#### 4. Version name string matches release font criteria and head table value.

In 1998, the CFF rasterizer had heuristics built in so that that fonts would not work if the version number is less than 1. 
Release font criteria:  
- DEVELOPMENT should not be in name string  
- version number must be greater than 1 (i.e. 1.001 or bigger)     
```

**Comment by colinmford** [comment]
> In 1998, the CFF rasterizer had heuristics built in so that that fonts would not work if the version number is **less than** 1.

This I can understand. What I don't get is the next stipulation:

> - version number must be greater than 1 (i.e. 1.001 or bigger) 

Surely this should be _greater than **or equal to** 1,_ in that case, if the CFF rasterizer cannot accept values _less than_ 1. There is a whole number between "less than 1" and "greater than 1"! 

Also — is this still an issue? I've never run into a situation where the issue was a font whose version I had set to 1 or below.

Regardless, if you want to keep this as it is for some legacy reason, you can just close this issue. I would still like to fix that typo, but it's probably not worth the hassle.
