### ISSUE TITLE
Minor formatting issue

### ISSUE THREAD

**Issue by alex-phil** [adobe-type-tools/afdko#1603]
The following paragraph

http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6hv-specifying-contextual-positioning-with-in-line-mark-attachment-positioning-rules

exhibits a minor formatting issue. The HTML specifies an ordered list with the first item being a table. Probably not intended. Thank you for taking a look.

**Comment by josh-hadley** [comment]
Note that the referenced PR closed this issue, but the results in HTML won't be available until this gets merged to `master` (i.e. next release which triggers rebuild of the documentation).
