### ISSUE TITLE
Windows DLL not found error while running compareFamily test

### ISSUE THREAD

**Issue by Eigi** [adobe-type-tools/afdko#1608]
I have just installed version 3.9.2 from PyPI. When I run the compareFamily test I get this error message:
![image](https://user-images.githubusercontent.com/5278420/216325238-3f5234bf-8a1b-4187-bda8-8f10842f2e58.png)
Which translates to English: libxml2-2__.dll not found. Reinstalling the application may solve the problem.
... which it does not!

Downgrading afdko to version 3.9.1 helps.

I use the afdko with python 3.9 64-bit on Windows 10.

Best
Eigi

**Comment by kaydeearts** [comment]
Hi @Eigi , thanks for submitting this issue! Could you try installing the newest [AFDKO pre-release v3.9.3a](https://github.com/adobe-type-tools/afdko/releases/tag/3.9.3a)? It's intended to fix this problem. If it works fine, please let me know and we'll do a new release on it. 

Thanks!

**Comment by Eigi** [comment]
Sorry for being late,

Yes, it does solve the issue. 
Thank you very much.

Eigi
