### ISSUE TITLE
Doesn't add scripts path into env variables automatically on MacOS

### ISSUE THREAD

**Issue by Goooler** [adobe-type-tools/afdko#1610]
Follow the [installation](https://github.com/adobe-type-tools/afdko#installing), with an error see https://github.com/Goooler/Sarasa-Gothic/actions/runs/4095064299/jobs/7061722575

```sh
WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/Users/runner/Library/Python/3.11/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts psautohint and psstemhist are installed in '/Users/runner/Library/Python/3.11/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts buildcff2vf, buildmasterotfs, charplot, checkoutlinesufo, comparefamily, digiplot, fontplot, fontplot2, fontsetplot, hintplot, makeinstancesufo, makeotf, otc2otf, otf2otc, otf2ttf, ttfcomponentizer, ttfdecomponentizer, ttxn and waterfallplot are installed in '/Users/runner/Library/Python/3.11/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed afdko-3.9.3 appdirs-1.4.4 booleanOperations-0.9.0 brotli-1.0.9 defcon-0.10.2 fontMath-0.9.3 fontParts-0.11.0 fontPens-0.2.4 fontTools-4.38.0 fs-2.4.16 lxml-4.9.2 mutatorMath-3.0.1 psautohint-2.4.0 pyclipper-1.3.0.post4 six-1.16.0 tqdm-4.64.1 ufoProcessor-1.9.0 ufonormalizer-0.6.1 zopfli-0.2.2
```

You can repro this at https://github.com/Goooler/Sarasa-Gothic/commit/ceaa67c2e691c21c74ae373559972b2ed8211f06.

**Comment by Eigi** [comment]
This is the way how pip works. This behavior can't be changed by python package like afdko or any other package.
Best
Eigi

**Comment by Goooler** [comment]
But I see [MkDocs](https://github.com/mkdocs/mkdocs) works in the same workflow.

**Comment by josh-hadley** [comment]
@Goooler if you drop `--user` from https://github.com/Goooler/Sarasa-Gothic/actions/runs/4095064299/workflow#L29 does that change anything (I noticed your install of `MkDocs` does not use that directive).

**Comment by Goooler** [comment]
> @Goooler if you drop `--user` from https://github.com/Goooler/Sarasa-Gothic/actions/runs/4095064299/workflow#L29 does that change anything (I noticed your install of `MkDocs` does not use that directive).

It works now, thanks! If we should update readme to avoid something like this?
