### ISSUE TITLE
Push v1.20 of feature file spec

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#163]
According to https://github.com/adobe-type-tools/afdko/issues/152#issuecomment-277862653 there’s a v1.20 of the [Feature File Syntax](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html) but the live document (and its [source](https://github.com/adobe-type-tools/afdko/blob/master/FDK/Technical%20Documentation/OpenTypeFeatureFileSpecification.html)) is currently still at v1.19. Many thanks in advance for pushing out the new version.

**Comment by readroberts** [comment]
I see that I pushed it out to only  the variable font support branch. I just added it to the master branch as well.

**Comment by brawer** [comment]
Thank you! Not sure if you’ve noticed already, but the [web site](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html) is still at version 1.19.

**Comment by justvanrossum** [comment]
March 24, 2018, the website is still at 1.19. Can this _please_ be fixed?

**Comment by readroberts** [comment]
I kept putting this off because we've been always been  'a few weeks away'  from making a full PyPi release of the AFDKO, at which point an overhaul of the Adobe afdko web page would happen anyway. However, it has been many months, so I just went ahead and made this point fix.

**Comment by frankrolf** [comment]
@readroberts At this moment, the pip version of the FDK only supports > 10.12, I think keeping the download available and recent is a good thing.

**Comment by justvanrossum** [comment]
I don't see version 1.20 at https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html, though.

**Comment by tshinnic** [comment]
Erg, still not at [that page](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html)

And mentioned in FontTools source since Feb 11, 2017
at https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/feaLib/parser.py#L231

Ooo, [afdko/docs/OpenTypeFeatureFileSpecification.html](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.html) says v1.23 !

Soo, we should ignore Adobe's site in favor of published here?

**Comment by miguelsousa** [comment]
@cjchapman are you able to update the document on adobe.com?

**Comment by readroberts** [comment]
This is now an outdated direct link. The page it used to be on is at: https://www.adobe.com/devnet/opentype/afdko.html, which points users to the github afdko site as overriding all the legacy afdko stuff on the Adobe site.

We can can override this by restoring the link to the feature file spec  to devnet/opentype/afdko.html, and pointing it at the afdko github site, or by asking IT to redirect it. I suggest having IT just redirect it to the devnet/opentype/afdko.html page - this would create one less long-term dependencies.

**Comment by cjchapman** [comment]
I have submitted a request for our IT folks to redirect this:
https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html
to this:
https://www.adobe.com/devnet/opentype/afdko.html
which then directs folks to the latest docs on GitHub.

Apparently that redirect will take 1-2 weeks to go into effect for reasons outside of my control.

In the meanwhile, I've changed the offending page to say:
>You have reached a deprecated webpage.
Please see AFDKO page for more information.

with a link back to https://www.adobe.com/devnet/opentype/afdko.html.

**Comment by cjchapman** [comment]
Per discussion with @miguelsousa, I've asked IT to cancel the redirect request and changed the wording of this page:
https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html
to:
>The OpenType feature file syntax specification is now hosted at
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html
