### ISSUE TITLE
[makeotf] wrong codepoint assignment

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1641]
I just installed afdko 3.9.4 in the context of a workshop, and `makeotf` seems to write arbitrary code points for a very simple exercise (attached). The project is built without GlyphOrderAndAliasDB, the resulting code point assignment looks like this:

<img width="1465" alt="Screenshot 2023-04-17 at 14 20 32" src="https://user-images.githubusercontent.com/2049645/232496318-0d8eb358-8a17-491e-9c6e-b95012120151.png">
<img width="1530" alt="Screenshot 2023-04-17 at 14 20 41" src="https://user-images.githubusercontent.com/2049645/232496328-ad0049ff-cf9d-452c-8528-ddb7180f6c6f.png">

[font.ufo.zip](https://github.com/adobe-type-tools/afdko/files/11250622/font.ufo.zip)

`makeotf -r` for Source Serif Regular looks like this:
<img width="1464" alt="Screenshot 2023-04-17 at 14 17 32" src="https://user-images.githubusercontent.com/2049645/232496824-ac86f8ad-c894-4e57-9fe2-be7720a680c0.png">

**Comment by frankrolf** [comment]
This does not happen with afdko 3.9.3.

**Comment by miguelsousa** [comment]
Do the codepoint assignments change every time the fonts are built, or do they stay the same?

**Comment by frankrolf** [comment]
The codepoint assignments were staying consistent I believe. Also, every student had the same result (space = A).
