### ISSUE TITLE
AFDKO 3.9.5 incompatible with FontTools > 4.39.3. Any plans to support FontTools 4.39.4?

### ISSUE THREAD

**Issue by fmotion1** [adobe-type-tools/afdko#1660]
Getting this error:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
afdko 3.9.5 requires fontTools[lxml,ufo,unicode,woff]<=4.39.3, but you have fonttools 4.39.4 which is incompatible.`

Did I do something wrong or is Akido just incompatible with FontTools 4.39.4?

**Comment by kaydeearts** [comment]
Oops! GitHub automatically resolved this issue, but it isn't resolved just yet. @fmotion1 thank you for submitting this issue! We've fixed our requirements.txt and a pre-release will be available in a few minutes (it's processing and I'll update my comment once it's done).

Once the pre-release is out:
Could you install the pre-release and see if that resolves the issue? We'll issue an actual release next week.

**Comment by kaydeearts** [comment]
Hi @fmotion1, this should now be resolved in the new [FDK release 3.9.6](https://github.com/adobe-type-tools/afdko/releases/tag/3.9.6). I'll close this as completed, but please re-open this issue to let us know if you run into this again!
