### ISSUE TITLE
[buildcff2vf] returns 0 when no vf is built

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1667]
`buildcff2vf` can identify when glyphs are not 100% compatible. In that case, I get a message  `The input set requires compatibilization. Please try again with the -c (--check-compat) option.` – and the program ends – with return value 0.

Is it wrong to expect a non-zero return value here?

**Comment by josh-hadley** [comment]
Non-zero return seems reasonable for this (and should be fairly simple to implement).
