### ISSUE TITLE
[uforead] uforead fails to set advance width when height is also defined in the glif file

### ISSUE THREAD

**Issue by punchcutter** [adobe-type-tools/afdko#1669]
In a glif file that has both advance height and width defined like `<advance height="1000" width="1000"/>` uforead fails to read the width and sets it to 0. If `width` comes first then it gets read. We need to check for `height` as well. Right now we can just ignore it because width is more important, but correctly using `height` is something that can be dealt with later (more info in https://github.com/fonttools/fonttools/pull/2704 about using advance height from UFO to set vmtx/VORG). 

https://github.com/adobe-type-tools/afdko/blob/c02a68d03b0097b763dd5bca181a5877b2c9d4e5/c/shared/source/uforead/uforead.c#L1685

**Comment by hatchzo** [comment]
I saw the same problem, when `height` value comes first, as in `<advance height="1000" width="1000"/>`, `width` value is ignored.

**Comment by kaydeearts** [comment]
Resolved by #1720.
