### ISSUE TITLE
[spec] Malformed example in section 6.b.i

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#167]
In [section 6.b.i](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#6.b.i), the OpenType Feature File Syntax specification has the following example:

```
  position T <-60> a <-40 0 -40 0>;
```

This is invalid syntax; makeotf correctly rejects it. Instead, the example should say:

```
  position T -60 a <-40 0 -40 0>;
```

**Comment by readroberts** [comment]
Fixed on Nov 7 2017
