### ISSUE TITLE
psstemhist -g no longer supports GIDs, lacks support for hyphenated glyph names

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1680]
This morning I found out that `psstemhist` does not support hyphenated glyph names.
I thought to myself – well, I’ll just use GIDs then! Also no longer supported. 😩

`psstemhist -g a,a-cyr hyphen_test.ufo`
```
WARNING: glyph ID <cyr> in range a-cyr from glyph selection list option is not in font. <hyphen_test.ufo>.
ERROR: Selected glyph list is empty for font <hyphen_test.ufo>.
```
(stupid but understandable)

---

`psstemhist -g 3 hyphen_test.ufo`
```
WARNING: glyph ID <3> from glyph selection list option is not in font. <hyphen_test.ufo>.
ERROR: Selected glyph list is empty for font <hyphen_test.ufo>.
```
(bug)

---

`psstemhist -g 1-4 hyphen_test.ufo`
```
WARNING: glyph ID <1> in range 1-4 from glyph selection list option is not in font. <hyphen_test.ufo>.
ERROR: Selected glyph list is empty for font <hyphen_test.ufo>.
```

Example project attached.

[hyphen_test.ufo.zip](https://github.com/adobe-type-tools/psautohint/files/10221575/hyphen_test.ufo.zip)

**Comment by skef** [comment]
Fixed by #1703
