### ISSUE TITLE
[otfstemhist] cannot specify glyphs with dashes in name

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1698]
I have a Thai font for which I’d like to analyze stem information. The Thai glyph names look like this:

```
koKai-thai
khoKhai-thai
khoKhuat-thai
khoKhwai-thai
khoKhon-thai
khoRakhang-thai
```
etc.

When running `otfstemhist -g koKai-thai,khoKhai-thai my_font.ufo`, I get

```
WARNING: glyph ID <koKai> in range koKai-thai from glyph selection list option is not in font. <xxx Thai Traditional-Regular>.
WARNING: glyph ID <khoKhai> in range khoKhai-thai from glyph selection list option is not in font. <xxx Thai Traditional-Regular>.
ERROR: Selected glyph list is empty for font <xxx Traditional-Regular>.
```

I assume this is because the dashed glyph names coincide with otfstemhist’s glyph range parsing. Not blaming otfstemhist, the same bug exists in psstemhist.

**Comment by skef** [comment]
Apparently forgot to reference this in #1703 , but it's fixed (we check for a glyph with the hyphen in the name first).

**Comment by madig** [comment]
Installing afdko from the develop branch, I still get the same bug when trying to use otfautohint's `-g` or `-x` switches. Should this have been fixed as well?

**Comment by skef** [comment]
@madig -- did you confirm that the font file you're hinting retained the glyph names in the post table? They're often omitted.

**Comment by madig** [comment]
Oh duh, of course. Sorry for the noise.
