### ISSUE TITLE
Clarify license of FDK/Tools/Programs/public/lib/source/t1write/*.txt

### ISSUE THREAD

**Issue by bastien-roucaries** [adobe-type-tools/afdko#172]
Hi,

Some txt file are all right reserved and thus not free

Moreover, apache license is not really nice for t1. Some fonts exist under gpl2 and thus incompatible with apache2.

Identically for some proprietary fonts.

Could you relicense to more liberal license this code (MIT/BSD3 for instance).

Thank you

**Comment by miguelsousa** [comment]
> Could you relicense to more liberal license this code (MIT/BSD3 for instance).

No. Thanks for asking.

**Comment by bastien-roucaries** [comment]
For instance this one:
https://github.com/adobe-type-tools/afdko/blob/e424a1fe3a12838dd7a8c6287d24399f3b1eb648/afdko/Tools/Programs/public/lib/source/t1write/t1write_flexothers.txt

**Comment by davelab6** [comment]
If Debian can't package FDK, can it use fontmake?

**Comment by bastien-roucaries** [comment]
@davelab6 No fontmake does not use /OtherSubrs

**Comment by miguelsousa** [comment]
@bastien-roucaries I've submitted #334 which should address your questions.
