### ISSUE TITLE
use TTX tools to  compile a otf file

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#1721]
I use the command 'ttx -f -m abc.otf abc.ttx' . but only ganerate a abc.ttf file. why?

**Comment by mhjy** [comment]
why it didn't ganerate 'abc.otf' file?

**Comment by punchcutter** [comment]
Your ttx file must have come from a TTF. It depends what's in the file, but if it's not TTF specific (like glyf) then you just need to change the header of the ttx file from

`<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.43">`
to
`<ttFont sfntVersion="OTTO" ttLibVersion="4.43">`

**Comment by punchcutter** [comment]
Also, ttx is from fonttools and maintained there: https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/ttx.py

**Comment by mhjy** [comment]
My steps are:
1,   Using FC(FontCreater) build the font file, and export to a otf file ( abc.otf)
2,  Using ttx tools dump a .ttx file(abc.ttx)     comand:     ttx -q -f -t name -t head abc.otf
3,  Modified some values in the .ttx file(abc.ttx)  
4,  Using ttx tools compile the new .ttx file.   comand:      ttx -f -m abc.otf abc.ttx 

which step is wrang?

**Comment by mhjy** [comment]
after the commang 'ttx -q -f -t name -t head abc.otf', the head of .ttx file is :
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.38">
  <name>
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      2018 Inner Mongolia GLT Font Software L.L.C. All rights reserved.
    </namerecord>.............................................

ttx cann't dump  <ttFont sfntVersion="OTTO" ttLibVersion="4.43">????

**Comment by mhjy** [comment]
![image](https://github.com/adobe-type-tools/afdko/assets/5868202/07c863c9-1da0-4a1a-b2d8-5f8791cf95a3)

**Comment by punchcutter** [comment]
You have it set to TrueType in Outline Format. That will make a TTF even if the extension is otf.

**Comment by mhjy** [comment]
FC exporting file is not a real otf file, only the extension name is otf??

**Comment by punchcutter** [comment]
That's what it looks like. If Outline Format is set to TrueType then it should be a TTF font.

**Comment by mhjy** [comment]
I know. Thanks
