### ISSUE TITLE
Reordering of ligature substitution rules is considered harmful

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#1727]
The Feature File Specification [§5.d](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5d-gsub-lookuptype-4-ligature-substitution), states that:

> A contiguous set of ligature rules does not need to be ordered in any particular way by the font editor; the implementation software must do the appropriate sorting. So:
> 
> ```
> sub f f     by f_f;
> sub f i     by f_i;
> sub f f i   by f_f_i;
> sub o f f i by o_f_f_i;
> ```
> will produce an identical representation in the font as:
> 
> ```
> sub o f f i by o_f_f_i;
> sub f f i   by f_f_i;
> sub f f     by f_f;
> sub f i     by f_i;
> ```

There are several issues with this:
1. It is very surprising to users, since the code has one order and the binary silently gets a different order, and the order matters as it controls which substitution is applied first,
2. There is no way to prevent this automatic re-ordering, other than splitting each substitution to its own lookup which is wasteful and unnecessary,
3. The sorting algorithm is undocumented, so there is no clear way to verify that implementations are implementing it compatibly.

I think this sorting should be deprecated and dropped, or if back-compatibility is a concern, have a way to disable it.

**Comment by frankrolf** [comment]
I remember a time where the mantra “longer ligatures first” was important. I only found out about the re-ordering when trying to demonstrate this problem in one of my workshops.

I can see how this behavior might be considered a theoretical problem, but I think the benefits outweigh this concern. It seems natural for users to write shorter substitutions first.

That said, do you have a practical example where this re-sorting would cause actual harm?

FWIW, the sorting algorithm seems to be here: 
https://github.com/adobe-type-tools/afdko/blob/develop/c/makeotf/lib/hotconv/GSUB.c#L1730-L1768

**Comment by khaledhosny** [comment]
> FWIW, the sorting algorithm seems to be here:
> https://github.com/adobe-type-tools/afdko/blob/develop/c/makeotf/lib/hotconv/GSUB.c#L1730-L1768

This sorts by length and GID, which is double bad. Sorting by legnth is understandable, though misguided, but sorting by GID makes no sense.

> 3. The sorting algorithm is undocumented, so there is no clear way to verify that implementations are implementing it compatibly.

Case in point, FontTools only sorts by length https://github.com/fonttools/fonttools/blob/fa59ada1b557bc304c592a2ca91c6b99ff6d241d/Lib/fontTools/otlLib/builder.py#L1570

**Comment by Lorp** [comment]
Is the sort by glyphId simply to ensure consistent results between different sort algos?

**Comment by khaledhosny** [comment]
I don’t think there is any point in sorting by GID, as it changed the meaning of the code and is far more worse than sorting by length since that one is at least potentially desirable.

**Comment by Lorp** [comment]
Right, I was assuming the sort by GID was a secondary sort after the sort by length. Still, that could be confusing if you have some equal-length subs that you need to happen in sequence.

**Comment by anthrotype** [comment]
> FontTools only sorts by length

Well, actually it sorts by length first and secondarily sorts alphabetically by the ligature component glyph names.
fra-rs I believe sorts by length and then GID, similar to makeotf if I understand correctly.
I can see situations where the sorting is undesirable altogether. Ideally once should be able to opt out. For the default behavior I suppose we should stick to one officially documented ordering.

**Comment by anthrotype** [comment]
Thanks Colin for clarifying the non-issue. We should not be talking about ordering of ligatures in general (as they appear in the feature.fea) but the order within a given _ligature set_ keyed by first glyph, with each ligature set always necessarily sorted by the glyphID as per OpenType spec (no matter what FEA or font developer say).
I agree that _not_ ordering longer ligatures ahead of shorter ones may lead to some becoming unreachable -- why even bother having a f_f_i ligature if f_f would always match first?! So it makes sense to keep sorting ligature within a set by the length of ligature components.
I also now see that even for different ligatures of equal length (within a set), it doesn't really matter which order they appear, either they will match the input string or they will not. So for these the only reason for specifying some order is consistency across implementations. We can sort by GID (like makotf and fea-rs do), by glyph name (like fonttools does), or _not_ sort these (equal length ligatures with same first glyph) but keep in the same order as written in the FEA. I think overall the latter is the least effort for anybody so +1 to this.
