### ISSUE TITLE
CFF subroutinizer generates some unused subroutines

### ISSUE THREAD

**Issue by mashabow** [adobe-type-tools/afdko#173]
As I reported in https://github.com/adobe-fonts/source-han-sans/issues/162 before, AFDKO's subroutinizer seems to generate some unused subroutines. Note that these subroutines are totally harmless, just redundant, and subroutinized font works pretty well.

The new subroutinizer (not released yet) might also have the same problem. See https://github.com/adobe-fonts/source-han-serif/issues/35.

**Comment by behdad** [comment]
Where can I read about this new subroutinizer?

**Comment by kenlunde** [comment]
I briefly wrote about it [here](https://blogs.adobe.com/CCJKType/2017/03/cff-subroutinization-improvements.html).

**Comment by twardoch** [comment]
@kenlunde are there plans to also put the new subroutinizer into makeotfexe?

**Comment by kenlunde** [comment]
That would certainly be nice, and something that @readroberts should consider.

**Comment by anthrotype** [comment]
https://blogs.adobe.com/CCJKType/2017/03/cff-subroutinization-improvements.html

> the next release of AFDKO will include a version of the tx tool that includes this new and improved subroutinizer.

So, has the code been released somewhere in this repository already? I might be interested in making a wrapper similar to psautohint to call this new subroutinizer from python, and maybe add that to fontmake, as an alternative to compreffor.

cc @kenlunde @miguelsousa

**Comment by anthrotype** [comment]
In the release notes for "FDK. v2.5 April 3 2017 change number 65781", I read that

https://github.com/adobe-type-tools/afdko/blob/3db84547a81abcfdc7246cef74d4a210c09dec4a/afdko/FDKReleaseNotes.txt#L98

So if this is it, perhaps it is already here somewhere. I'm not familiar with the afdko code base. Can someone point me to the relevant public headers, so I can start digging?

**Comment by miguelsousa** [comment]
@anthrotype I believe the code is in the latest `tx`. The work was done by @blueshade7, so he may have something to say.

**Comment by anthrotype** [comment]
thanks!

**Comment by kenlunde** [comment]
Yes: -no_futile
