### ISSUE TITLE
[makeotfexe] FontMatrix values not compiled precisely enough, causing wrong UPM values down the line

### ISSUE THREAD

**Issue by justvanrossum** [adobe-type-tools/afdko#174]
This commit: https://github.com/adobe-type-tools/afdko/commit/8afb11dc28cd155d9a0b895124ffc0aa57849787 (specifically, this line: https://github.com/adobe-type-tools/afdko/blob/6eec25f5ac7090be83a852ef90ac5bf81c2975dc/FDK/Tools/Programs/public/lib/source/cffwrite/cffwrite_dict.c#L233) is causing UPM values to be changed when converted to FontMatrix values and back. For example 2048 turns into 2049, and 3000 turns into 3003. `1/2048` cannot be stored precisely enough with only 8 places (six decimals):
```python
>>> int(round(1.0/round(1.0/2048, 6)))
2049
>>> int(round(1.0/round(1.0/3000, 6)))
3003
```

**Comment by justvanrossum** [comment]
See also: https://twitter.com/monokromfonts/status/852240198444437510

**Comment by miguelsousa** [comment]
Thanks @justvanrossum. @readroberts will get it fixed.

**Comment by readroberts** [comment]
Agreed.

**Comment by readroberts** [comment]
@justvanrossum  Hi Just; Can you reproduce this? I agree that six decimal places after the period is not enough, as you show in the Python examples, but the ctuDtostring() function uses 8. When I do multiple round trips UFO->t1->cff and back with a UPM of 2048 or 3000, I do not see any problem.

**Comment by justvanrossum** [comment]
I cannot reproduce in RF3.2, so I guess this has been fixed one way or another. I can still reproduce in RF 1.8.4 so the issue did exist at some point.

**Comment by justvanrossum** [comment]
I think it got fixed as part of https://github.com/adobe-type-tools/afdko/commit/8afb11dc28cd155d9a0b895124ffc0aa57849787, which predates my issue...
