### ISSUE TITLE
broken AFDKO download link!

### ISSUE THREAD

**Issue by nanife** [adobe-type-tools/afdko#175]
I can't get into the FDK download link. is it broken?
in url below,
_http://www.adobe.com/devnet/opentype/afdko.html_
there are no download links.
I downloaded it two days ago, but I can't do it again now.
what happened???

**Comment by readroberts** [comment]
I also see that the link is broken, as well as many other problems on the page.  Nothing has changed in the data being published, so this must be a server problem.  I have reported this issue, and trust that it will be fixed soon.

**Comment by miguelsousa** [comment]
@nanife the downloads are also available at https://github.com/adobe-type-tools/afdko/releases/latest

**Comment by nanife** [comment]
Thanks, Read Roberts and Miguel Sousa!
