### ISSUE TITLE
Little error in documentation for FEA name table blocks

### ISSUE THREAD

**Issue by cmyr** [adobe-type-tools/afdko#1765]
The documentation says,

> Note that IDs 2 and 6 (Family, Subfamily, Unique, Full, Version, and FontName) are reserved by the implementation and cannot be overridden; doing so will elicit a warning message and the record will be ignored.

([source](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#:~:text=Note%20that%20ids,ignored))

the docs say "2 *and* 6", but then lists six different ids.

experimenting shows that in fact the range of ids [1, 6) (inclusive) are rejected by afdko.

**Comment by khaledhosny** [comment]
This have been already brought up before in #1457

**Comment by cmyr** [comment]
Thanks, closing as a dupe
