### ISSUE TITLE
[tx] Segmentation fault: 11 occurs when trying to get a font dict from a PostScript file

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-type-tools/afdko#178]
I've tried the following command against Source Han Serif.
`tx -t1 -decid -usefd 13 -fd 13 ./Regular/OTC/cidfont.ps.OTC.J SHSerif-fd13.ps`
An error occurs saying
`--- subset:`
`SRC font	./Regular/OTC/cidfont.ps.OTC.J`
`SRC glyphs	65535`
`DST font	SHSerif-fd13.ps`
`DST glyphs	48030`
`1350-1383,1828-1863,2440-48488,59762-59870,60423-61039,61064-62248`
`Segmentation fault: 11`
The file can be downloaded from [cidfont.ps.OTC.J](https://github.com/adobe-fonts/source-han-serif/blob/master/Regular/OTC/cidfont.ps.OTC.J)

However, if I run tx against a generated OTF font, it completes successfully.
`tx -t1 -decid -usefd 13 -fd 13 /Library/Fonts/SourceHanSerif-Regular.otf SHSerif-fd13.ps`

**Comment by jimmymasaru** [comment]
Moreover, this issue only happens for font dict 13 which contains a large number of ideographs.

**Comment by readroberts** [comment]
I will look at this in the next day or two.

**Comment by miguelsousa** [comment]
```
$ tx -t1 -decid -usefd 13 -fd 13 cidfont.ps.OTC.J SHSerif-fd13.ps
--- subset:
SRC font	cidfont.ps.OTC.J
SRC glyphs	65535
DST font	SHSerif-fd13.ps
DST glyphs	48068
1350-1383,1828-1863,2440-48488,59762-59870,60423-61039,61064-62248,64747-64784
```

**Segmentation fault** no longer happening with the current build. Don't know when it got fixed.
