### ISSUE TITLE
[tx] -n switch does not remove hints if the output is t1 or cff

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-type-tools/afdko#180]
The following commands have no difference in their output.
`tx -t1 -g /3605 /Library/Fonts/SourceHanSerif-Regular.otf 3605.ps`
`tx -t1 -n -g /3605 /Library/Fonts/SourceHanSerif-Regular.otf 3605-nohint.ps`
However, these commands do have differences. Hints are removed by the latter.
`tx -6 -g /3605 /Library/Fonts/SourceHanSerif-Regular.otf`
`tx -6 -n -g /3605 /Library/Fonts/SourceHanSerif-Regular.otf`

**Comment by kenlunde** [comment]
Confirmed.

**Comment by readroberts** [comment]
Will fix soon.

**Comment by miguelsousa** [comment]
I've tested the commands with the most recent release (`2.7.1rc`) and the hints are removed. Don't know when it got fixed.
