### ISSUE TITLE
Linux build enters into infinite loop

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#182]
Building current master on Linux enters into infinite loop because there are no build files in `FDK/Tools/Programs/public/lib/build` for the newly added `nameread` and `varread` libs.

Probably be the files were unintentionally not checked in, if not I can send a PR adding the Linux files only as I can’t test the others.

**Comment by readroberts** [comment]
Please update and verify that this is fixed for you. I see that a number of build files for varread and nameread libraries were omitted.

**Comment by khaledhosny** [comment]
Builds fine now, thanks.
