### ISSUE TITLE
How to subset a CID keyed OTF font using tx and makeotf tool?

### ISSUE THREAD

**Issue by legokangpalla** [adobe-type-tools/afdko#183]
I'm writing a simple script to subset OTF fonts. It runs ok so far but then I encountered error when subsetting a CID keyed font. 

Original script:
Let's say original font is NanumBrush.otf and I want to just keep ampersand character.
> tx -t1 -g ampersand NanumBrush.otf temp.ps
> makeotf -f temp.ps -o NanumBrushSubset.otf

But the same won't work for CID keyed font, so I did some googling and saw this documentation: http://blogs.adobe.com/CCJKType/files/2012/10/atypi2012-afdko-hattori.pdf

So I tried the following

> tx -t1 -decid -g /0,/123 NanumBrush.otf temp.ps
> tx -t1 -decid -usefd 0 -g /0,/123 NanumBrush.otf temp.ps

and makeotf runs and produces otf files, but their cmaps are empty and I can't use them.

I also tried
> tx -afm temp.ps AFM

This gave me an afm file and I found that my font is CharacterSet Adobe-Korea1-0 which is KSCpc-EUC-H?
So I tried

> tx -t1 -g /0,/123 NanumBrush.otf temp.ps
>makeotf -f temp.ps -o NanumBrushSubset.otf -ch KSCpc-EUC-H

and I'm getting errors.

makeotf [Warning] Could not find default features file at 'None'. Font will be built without any layout features.
makeotf [Warning] Could not find FontMenuNameDB file. Font will be built with menu names derived from PostScript name.
No feature path at None
Traceback (most recent call last):
  File "C:\FDK-25-WIN.b65322\Tools\SharedData\FDKScripts\MakeOTF.py", line 2624, in <module>
    main()
  File "C:\FDK-25-WIN.b65322\Tools\SharedData\FDKScripts\MakeOTF.py", line 2616, in main
    setMissingParams(makeOTFParams)
  File "C:\FDK-25-WIN.b65322\Tools\SharedData\FDKScripts\MakeOTF.py", line 1647, in setMissingParams
    if os.path.exists(featPath) and not foundVert:
  File "C:\FDK-25-WIN.b65322\Tools\win\Python\AFDKOPython27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by miguelsousa** [comment]
Have you tried [pyftsubset](https://github.com/fonttools/fonttools)? There's a good chance it does what you need.

**Comment by legokangpalla** [comment]
I tried it and really wish I could use it...alas the script is temporary and it needs to be compiled as a library and integrated into our cross platform api in C/C++. ADFKO is the only C library I found that does subsetting so I'm afraid I'm stuck with it.

**Comment by kenlunde** [comment]
@legokangpalla: So many things are being done wrong at wo many levels, it's difficult to know where to begin.

First, keep in mind that _makeotf_ needs information to build the 'cmap' table. For CID-keyed fonts, this means supplying a UTF-32 CMap resource, which explicitly maps UTF-32 code points to CIDs. For name-keyed fonts, the glyphs either need to be named according to standard conventions, such as "space" for the space (U+0020) character, or named according to their Unicode code point, such as "uni0020" for the space character.

When you executed the `tx -t1 -decid -usefd 0 -g /0,/123 NanumBrush.otf temp.ps` command, the resulting font should include glyphs named ".notdef" and "cid123." The glyph named "cid123" is meaningless to _makeotf_ without special treatment. You would need to use either _mergeFonts_ or _rotateFont_ to rename the glyph. In fact, both of those tools are able to subset fonts and rename glyphs. The former can subset like _tx_, but you first need to use _tx_ to convert from CID-keyed to name-keyed, then run _mergeFonts_ with a mapping file to rename the glyphs. The latter requires a mapping file that can both subset the font and rename its glyphs. It's a bit more complicated than that, so I encourage you to read [Adobe Tech Note 5900](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5900.RFMFAH_Tutorial.pdf).

About running `makeotf -f temp.ps -o NanumBrushSubset.otf -ch KSCpc-EUC-H`, there seems to be two problems. One is that it seems that you need to supply a minimal "features" file. The following contents should suffice:

```
table head {
  FontRevision 1.000;
} head;
```

The other is that the "-ch" command-line option is for specifying a Unicode CMap resource. "KSCpc-EUC-H" is not such a beast. That would be an appropriate CMap resource as the augment for the "-cm" command-line option. Try using "UniKS-UTF32-H" instead.

BTW, the glyph for [Adobe-Korea1-2](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5093.Adobe-Korea1-2.pdf) CID+123 should look like U+300B 》.

**Comment by legokangpalla** [comment]
Thank you so much @kenlunde it works like a charm! I just had to supply the features file.
