### ISSUE TITLE
otf2otc complains about `You must specify more than one input font.`

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#184]
But, a TTC with only one sub-font is valid.

**Comment by kenlunde** [comment]
Just out of curiosity, what is the benefit—or valid use case—for an OpenType Collection with only one font instance (aka sub-font)?

**Comment by be5invis** [comment]
@kenlunde When you are automating something you would find it really annoying.
ps. Does otf2otc support sharing identical tables among **some** (not all) of the input OTFs?

**Comment by kenlunde** [comment]
About your P.S., you will need to elaborate. The _otf2otc_ tool allows a particular sfnt table to be forcibly shared with all of the font instances by specifying it as the argument of the "-t" command-line option. Other than that, it determines which tables can be shared and which ones cannot.

**Comment by be5invis** [comment]
@kenlunde The situation is: We have like four fonts, ABCD, where `A` and `B`'s `glyf` are identical, and `C` and `D`'s `glyf` are identical. We'd like to build the font using standard `otf2otc` call. So, could `otf2otc` ensure that, the result only contains two `glyf` data instead of four?

**Comment by kenlunde** [comment]
If `A` and `B`'s 'glyf' tables are binary identical, with the same being true of those for `C` and `D`, then the resulting OpenType Collection will include only two 'glyf' tables.

**Comment by be5invis** [comment]
@kenlunde That would be great.
ps. Is there any plan for `otf2otc` to support taking TTC as **input**: break it into OTFs internally and build a larger TTC?

**Comment by kenlunde** [comment]
Enhancing `otf2otc` to accept OpenType Collections as input would be something for @readroberts  to consider. For my own uses, I simply pre-process the input (and non-Collection) OpenType fonts to build larger OpenType Collections. See the [Source Han & Noto CJK Super OTC](https://github.com/adobe-fonts/source-han-super-otc) for an example.

**Comment by readroberts** [comment]
otf2otc is a pretty simple Python script. Both allowing only one OTF as input and allowing an OTC as input would be very little work, and I can see that this would be useful.

**Comment by be5invis** [comment]
@readroberts I've moved that into #185.

**Comment by miguelsousa** [comment]
This has been supported since June 2017. It got implemented by this commit: 73e28f58d03ac428a4cad78228ec91d7b0bef588
