### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by alanondra** [adobe-type-tools/afdko#192]
Running an elevated command prompt in the FDK directory and executing "FinishInstallWindows.cmd" returns the response:

	The system cannot find the path specified.

I'm running Windows 7 x64 Pro, and I've installed Python 2.7.10 and set up `PYTHONPATH` to comply with requirements.

**Comment by miguelsousa** [comment]
Since version 2.7.0 (released on May 9, 2018) the FDK is installable via `pip` and `FinishInstallWindows.cmd` is no longer used.
