### ISSUE TITLE
Feature File Specification says UseMarkFilteringSet not supported as of 2008

### ISSUE THREAD

**Issue by NorbertLindenberg** [adobe-type-tools/afdko#197]
The OpenType Feature File Specification describes the UseMarkFilteringSet flag as “a new lookup flag which is proposed for OpenType spec 1.6” and says “The drawback to this lookupflag is that as of Nov 2008, there are not yet any programs that support it.”

It’s October 2017, the current OpenType Specification version is 1.8.2, useMarkFilteringSet is part of it, and I find this flag quite well supported in HarfBuzz, CoreText, and the engine used by Edge (DirectWrite? UniScribe?). Is there any rendering system left that doesn’t support the flag?

The description should remove “new”, “proposed for OpenType spec 1.6”, and the entire last sentence, unless there are any rendering systems known not to support the flag in 2017 that need to be called out here.

**Comment by readroberts** [comment]
Thanks for the report. Fixed Nov 7 2107.
