### ISSUE TITLE
Release with Variable Font Support

### ISSUE THREAD

**Issue by traviskochel** [adobe-type-tools/afdko#200]
Is there a release/package that supports variable font generation? I've run across this link a few times but it doesn't seem to be working http://www.adobe.com/devnet/opentype/afdko/AFDKO-Variable-Font-Support.html 

It's mentioned here: https://github.com/adobe-fonts/adobe-variable-font-prototype

I've tried the most recent release from this github repo, but it doesn't seem to have the `buildMasterOTFs` and `buildCFF2VF` commands called [here](https://github.com/adobe-fonts/adobe-variable-font-prototype/blob/master/buildFont.sh#L8-L9?)

Is the best option just to pull the master branch and build it manually?

**Comment by cjchapman** [comment]
Yes, there is a release that supports variable font generation now. We've had issues with broken links (due to changes in our web infrastructure) that we're in the process of resolving. This link should work for you now:  
http://www.adobe.com/devnet/opentype/afdko/AFDKO-Variable-Font-Support.html

**Comment by traviskochel** [comment]
Thanks
