### ISSUE TITLE
TT font output by makeOTF as CFF with .ttf extension

### ISSUE THREAD

**Issue by frodebohelland** [adobe-type-tools/afdko#205]
I have a set of hinted truetype fonts that makeOTF exports as CFF fonts with a .ttf extension. I’ll happily provide files, but I can’t upload them here. I wonder what might cause this, and how I can troubleshoot? This only happens with the italics fonts in my family. The romans behave as expected. I’m wondering if there perhaps is some PS outline in there somewhere, that causes makeOTF to interpret the fonts as CFF, or if there might be some info in a table that causes this.

**Comment by benkiel** [comment]
Is there a space in the file name? This was a bug, fixed a bit ago.

**Comment by frodebohelland** [comment]
Yes, “Fontname-Normal Italic”! That was it. Thanks, Ben.
