### ISSUE TITLE
fontTools version can contain str info

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/afdko#206]
see https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/buildCFF2VF.py#L901

in this case Im running a "cutting edge version" so it has the extension `dev0`
a quick fix:

```python
from fontTools import varLib, version as fontToolsVersion

parts  = fontToolsVersion.split('.')
parts = [int(part) for part in parts if part.isdigit()]
print parts
```

**Comment by anthrotype** [comment]
fonttools uses a version string which conforms to PEP 440
https://www.python.org/dev/peps/pep-0440/

the canonical way to parse PEP440 versions is to use `pkg_resources.parse_version()` (`pkg_resources` is part of setuptools, which comes with most python distros).

http://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utilities

```python
from pkg_resources impor parse_version
import fontTools

assert parse_version(fontTools.version) >= parse_version("3.19")
```

**Comment by readroberts** [comment]
Thanks!
