### ISSUE TITLE
[autohintexe] Remove path checks

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#207]
autohint has several checks for path quality: sharp angles, line nearly vertical and horizontal, flat curves. These are duplicates of functions in checkOutlines, and are not up to date. Rather than fixing them, they should be removed. The hint related checks and consequent warnings will be left in place.

**Comment by miguelsousa** [comment]
@khaledhosny do you know if psautohint still has these checks?

**Comment by khaledhosny** [comment]
No idea, was this done by the Python or the C library?

**Comment by khaledhosny** [comment]
I’m removing these checks, started with the smoothness one, but they don’t seem to be just checks, they affect the final hinting of some fonts. Do we want to evaluate the result of removing them or leave them for now?

**Comment by miguelsousa** [comment]
The [path checks were disabled in the **psautohint** codebase](https://github.com/adobe-type-tools/psautohint/commit/2fea4521b1cff70193de586f7092f22f191bfdd4#diff-b0ec47544241956de98596de3b6c5695). The **autohintexe** used by the afdko tools comes from that repo. So this is done.
