### ISSUE TITLE
stemHist finds different stem lists on Windows than on Mac.

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#210]

**Comment by frankrolf** [comment]
It’s even better than that. Lists for the same source UFO differ across Macs.

**Comment by miguelsousa** [comment]
@frankrolf do you have any test fonts to reproduce this?

**Comment by frankrolf** [comment]
[font.ufo.zip](https://github.com/adobe-type-tools/afdko/files/1939204/font.ufo.zip)
The attached UFO is the one I use for an exercise explaining the use of `stemhist`.
It’s common that the bottom values for p and q are not found on my machine, while they are found on students’ computers.
This is the example command:
`stemhist -a -g a-z,A-Z,zero-nine font.ufo`

In general, the resulting report files slightly differ from machine to machine.

**Comment by miguelsousa** [comment]
@khaledhosny I've built `autohintexe` from the psautohint repository, and I'm getting the same results as above. Shall I open a new issue, or do you want to track it as part of https://github.com/adobe-type-tools/psautohint/issues/71?

**Comment by khaledhosny** [comment]
Tracking in adobe-type-tools/psautohint#71 is fine.

**Comment by khaledhosny** [comment]
Can you try with the autohintexe binary from https://ci.appveyor.com/project/adobe-type-tools/psautohint/build/1.0.627 (check the artifacts of the relevant build)?

**Comment by miguelsousa** [comment]
@khaledhosny with that build the Win output is now the same as the Mac. But I think the extra lines in the Win output were correct.

**Comment by khaledhosny** [comment]
The changes I did in this branch are fixing undefined behavior issues related to bit shifting and integer overflow, so I don’t know what output is correct, it is just now that the compiled code does not rely on any undefined behavior (which with some compilers and aggressive optimizations, can result in code being optimized away in unexpected ways). We should now debug this and see why these extra lines are missing.

**Comment by miguelsousa** [comment]
@khaledhosny is this fixed?

**Comment by khaledhosny** [comment]
I still need to find out whether the old Windows output was the correct one, but the inconsistency between platforms should be fixed.

**Comment by miguelsousa** [comment]
OK. The reason why I think the extra lines in the Windows output were correct is because `HStem _ top 738.000000` entries are generated for other lowercase glyphs with ascenders, like `l` and `h`, for example.

**Comment by khaledhosny** [comment]
I’m rather lost here. So far, this seems to be caused by [`PruneHVals()`](https://github.com/adobe-type-tools/psautohint/blob/1b57818b5a8d13416362a56056c78280538c1477/libpsautohint/src/merge.c#L215) pruning one hint val in the `b` glyphs that it does not prune on the `d` glyph, though there top and bottom points look rather identical. Specifically, [this condition](https://github.com/adobe-type-tools/psautohint/blob/1b57818b5a8d13416362a56056c78280538c1477/libpsautohint/src/merge.c#L301) is true the second time it gets executed in the `b` glyph but not in the `d` glyph. But I’m having hard time deciphering what this code is trying to do.

**Comment by miguelsousa** [comment]
@khaledhosny can you add a unit test for `PruneHVals()` ? That may help to confirm that the bug is really in there.

**Comment by khaledhosny** [comment]
We don’t currently have the infrastructure to add unit tests for functions deep inside the C library like this one.

**Comment by miguelsousa** [comment]
This issue has been eluding you for weeks. Is that not a strong enough motivation to get C unit testing off the ground?

**Comment by khaledhosny** [comment]
It is not that I don’t like having unit tests, it is that I’m not sure it is as easy as it sounds. The code uses global variables a lot and most of the active state; the parsed paths, the hints, and what not are all in global variables, so I’m not sure how this all will be possible to cleanly test single functions. Based on experience, it is going to be a multi-week small project if not more.

**Comment by miguelsousa** [comment]
Got it, thanks. I'll work with the latest version and log any issues I find. Is version 1.9.0 stable?

**Comment by khaledhosny** [comment]
1.9.0b2 should be stable, if you can give it a try and if everything is OK I can cut a final release.

**Comment by miguelsousa** [comment]
Added a test case using the font and command provided and the CI is green. Closing as fixed.
