### ISSUE TITLE
Clean up documentation and output across all tools

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#211]
Remove unnecessary warnings. Unify display of help files & options. Goal: as little output as possible (it is often hard to spot an issue if the output is thousands of lines long, for instance when building a family). Revise options to be the same between programs, when possible.
Some specific examples from autohint:
**autohint** format & clean up the output - information about internal calls such as `Calling updateLayerContents` are not very informative - add line breaks before start & end time. - The tabs don’t make much sense and should be replaced by newlines. - There are many lines of duplicated information.

**Comment by frankrolf** [comment]
Closing this global issue in favor of more specific ones (like #1692).

In addition to this, `autohint` has been superseded by `psautohint`, which has been superseded by `otfautohint` – the output of those tools has been improved.
