### ISSUE TITLE
Move FDK install directory from ~/bin to /usr/bin

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#212]
Frank Griesshammer has noted that many people are confused by that ~/bin folder added by the FDK installer on the Mac, and tend to delete it. Although was good reason for this when the FDK was first developed, along with the FDK having its own copy of the Python interpreter, this is not longer the case.  I am about to repackage the FDK so that it will use the default Python27 interpreter on the system, and can by installed via setup tools. It will be installed as a Python site-packages module, and the commands will be instantiated in the python bin directory, like pyftsubset, ttx, and ufonormalizer.

**Comment by anthrotype** [comment]
Good. That means if the user does `sudo /usr/bin/python -m pip install afdko`, they will go to `/usr/bin` where the system python is, or if they use the homebrew python or the Python.org python (which don't need to `sudo`), the scripts will go to the global `/usr/local/bin`, or if they pass `--user` option to pip install, the scripts will go to the user's scripts folder (on Linux `~/.local/bin/`, on Mac ~/Library/Python/X.Y/bin (I think?), Windows somewhere else in the user's profile folders), or finally if installing inside a virtual environment, they'll go to the venv's bin or Scripts folder.

It's important that all these scenarios are supported (like with a regular python package) and that you don't make any assumptions about users wanting the scripts, e.g., in /usr/bin.

I'd argue that that is the worse location for them to be. That is a location reserved for operating system tools, not for user-installed scripts. Any OS update can wipe those out, or they may risk breaking other OS features.

I strongly recommend not to rely on the system python but install a third-party python distribution (if you don't want to use homebrew or compile youself with pyenv, then just grab the official GUI installers from python.org).

**Comment by readroberts** [comment]
Agreed. My intent is to have the AFDKO install as a normal Python third-party module, with no assumptions about what python is used - user gets to decide.

**Comment by benkiel** [comment]
> I strongly recommend not to rely on the system python but install a third-party python distribution (if you don't want to use homebrew or compile youself with pyenv, then just grab the official GUI installers from python.org).

@anthrotype I get that from the perspective of someone who is doing development on many things, but in my experience with type designers who are just installing tools (FDK and FontTools) to do simple things, I can't recommend this — it leads to a lot of frustration and broken things on OS X. Just in case someone who falls into the "not development, but type designer" camp reads this...

**Comment by anthrotype** [comment]
The introduction of SIP protection since El Capitan onwards prevents even root user to edit files under /System folder (which is where the python framework and its site-packages folder is located). This has made it more difficult to install third party python modules as root on the Apple python (and _rightly_ so).
Apple python has an "Extras" folder on its sys.path which contains various third party packages, most of which are super ancient. Attempting to pip upgrade even with sudo them will fail. 
The system python is there only because it's used by some internal OSX tools.
I'm so looking forward to when the legacy python clock ticks, and Apple will have no choice but remove it altogether, or finally support a modern python (cf. Linux distros).

**Comment by benkiel** [comment]
Agreed, but I've also spent good amounts of time on email and phone with folks sorting out installs of things because of odd installs of other pythons...

**Comment by anthrotype** [comment]
I know you pain :)

**Comment by frankrolf** [comment]
I welcome every effort to modernize the FDK. As it stands, the `~/bin` folder is just confusing.

**Comment by readroberts** [comment]
I need some advice on turning the AFDKO into a Python package. My main issue is with the C command line scripts. I would like them to be directly available to users, in a directory on the environment variable PATH list, and to avoid have to wrap them inside a Python script subprocess call.  I'd like the C programs to end up in the same directory as the console scripts. My first attempt is to reference them in the setup.py::setup() as items in the data_files list, and to specify( in the same list) that they should go to 'os.path.join(sys.prefix, 'bin')' on the Mac. This works when the package is installed with "python setup.py install", but when installed from a wheel, the C programs end up in site-packages + sys.prefix.  Does anyone know of a better way to accomplish my goal?
Another issue is Manifest.in vs data_files. I notice that the fonttools setup.py both lists all the non-script files in the setup.py, and also lists them all in Manifest.in. Do you really need to have both? Does one override the the other in different environments?
Finally, I notice that when I force installing the fonttools wheel with 'pip install --only-binary=fonttools fonttools', what ends up in site-packages is a directory tree, rather than the sing;e wheel file that I get when I install my test wheel. Can anyone tell me how to make that happen?

**Comment by readroberts** [comment]
Cosimo contributed quite a lot of time to resolving my issues. I now have a working prototype.  I learned of lot of background info, but had a couple of specific take-aways.
1) the most appropriate setup() keyword for installing executable programs is 'scripts'. 'data_files' is pretty much deprecated, and produces different results with different distribution formats. Use of 'scripts' may not be stable over time, as it is somewhat old - use of the entry_points keyword arg is encouraged instead - and was not intended for use files that were not Python scripts. 
2)  For data files that will end up in the distribution, it is better to not use package_data, and instead to use the MANIFEST.in file with the setup() keyword 'include_package_data=True'.
3) When the package is compressed with the zip file format ( default with egg and wheels), relative paths to data files won't work. You can force the package to NOT be zipped with  with setup() keyword ' zip_safe=False,', although Python will do this automatically if it notices references to '_file__' or Python extension files.  You can use the module 'package_utils' to safely load stuff from within a zip file.
4) Be wary of versions of pip left over from other installations of python on your system. The safest way to to call pip is to call the module from the Python that you are using, e.g. instead of 'pip  <args.', say python -m pip <args>'.
5) My original reason for not building the C command-line programs as Python extension modules is outdated. It used to be that every time Python changed a minor version, you had to update the Python headers for the extension module and recompile, and it would then work only with that exact Python version. Cosimo has been working with Ctypes to develop a wrapper for some of the fonttools extensions, that would let you write your functions as regular dynamic libraries, and they could be called by any Python version. I plan to eventually copy this code and make some of the afdko C programs be Python extensions again.

**Comment by miguelsousa** [comment]
@readroberts @cjchapman the way the tools are now packaged resolved this issue, yes?

**Comment by cjchapman** [comment]
@miguelsousa, yes, I think we can close this now.

**Comment by miguelsousa** [comment]
Resolved with the new packaging work.
