### ISSUE TITLE
CompareFamily. Update the vertical metrics check.

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#213]
CompareFamily checks for an arrangement of vertical metrics (ascent/descent/linegap) that made sense 10 years ago (and still makes sense in an ideal world). 

However, between web apps, mobile apps, and changing expectations in desktop apps, following these rules leads to poor baseline positioning and clipping in ever more places. The Adobe Type Dept is moving to a new set of rules that we think is safer.  

1) set LineGap to 0 for OS/2.sTyopLineGap, hhea.linegap, and vhea.vertTypoLineGap.
2) By default, accept the distance from the baseline to the FontBBox top and bottom as being the OS/2 winAscent and OS/2 winDescent. Most font tools set these fields with this rule. OS/2 winAscent may need to be manually overridden in case there are glyphs with exceptionally tall features. OS/2 winDescent cannot be less than 0.
3) Set the hhea ascent/descent the same as OS/2 winAscent and winDescent (except that hhea.descent is the negative of OS/2 winDescent).
4) Set OS/2  sTypoAscender and sTypoDescender to the desired typographic values, but with an adjustment to sTypoDescender to make up for setting  OS/2 sTypoLineGap to zero. This is usually sTypoDescender = sTypoAscender - UPM.

**Comment by miguelsousa** [comment]
`comparefamily` is due to be deprecated in favor of `fontbakery` which already reports the current best practices regarding vertical metrics values.
