### ISSUE TITLE
UFO3 compatibility

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#218]
It is desirable to make at least the general font building tools UFO3 compatible:
- [X] `tx` (#452, #455; further support requested in #475)
- [X] `makeotf` (#481)
- [x] `checkOutlinesUFO` (#482)
- [x] `autohint` (#526)
- [x] `makeinstancesufo` (#689)

`checkOutlinesUFO` already supports UFO3 somewhat, I think only the `save` method needs re-thinking – if would be good to deduce if the incoming file is UFO 2 or 3.

**Comment by frankrolf** [comment]
Probably the first tool to work on would be `tx`.
Currently, `makeotf` run on a UFO3 file returns
```
tx: (ufr) Warning: discarding token '<array/', in fontinfo.plist file. Context: 'ines</key>
	<array/>
	<key>italicAngle</key>
	<real>0.0</real>
	'.
tx: (ufr) Encountered end of buffer before end of glyph.
	<real>0.0</real>
	.
tx: fatal error
>
Done.
```
Related: what kind of XML reader is `tx` using? UFO2 and 3 are not very different from each other.

**Comment by frankrolf** [comment]
UFO3 is now the official file format for Robofont, which gives this bug a somewhat higher urgency. I would love to see us not fall behind on this.

**Comment by miguelsousa** [comment]
The AFDKO is behind in many things, UFO3 is just one of them. We need to make other improvements before adding support for UFO3.

**Comment by miguelsousa** [comment]
Done!
