### ISSUE TITLE
python3 plans

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/afdko#231]
now there is a mixture of script that support both py2 as py3 others aren't upgraded yet

are there any plans todo so?

**Comment by miguelsousa** [comment]
Yes, the plan is to upgrade most of them. I don't say "all" because some may get deprecated.

**Comment by typemytype** [comment]
I just converted the ones RoboFont requires... this is already a big start!!

**Comment by miguelsousa** [comment]
Indeed. Thanks!
