### ISSUE TITLE
pip installation fails on the dependencies

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#235]
Running `pip install --extra-index-url https://pypi.org --index-url https://test.pypi.org/simple afdko` will fail on the dependencies (ufonormalizer, fontMath, fonttools, ufoLib, booleanOperations, etc). I had to install them separately.
It would be good to know if:
1. is this cause because **afdko** is in `**test**.pypi.org` and the dependencies aren't?
2. is the install command missing an option to get the dependencies installed from `pypi.org`?

BTW, I first created a virtual environment. To do so run these commands:
(These assume that python, pip and virtualenv are already installed)
1. `python -m virtualenv fdk-test`
2. `source fdk-test/bin/activate`

**Comment by anthrotype** [comment]
there's a `/simple` after `pypi.org`:

```diff
- pip install --extra-index-url https://pypi.org --index-url https://test.pypi.org/simple afdko
+ pip install --extra-index-url https://pypi.org/simple --index-url https://test.pypi.org/simple afdko
```

still, i wouldn't recommend telling users to install from test.pypi.org. Just tag pre-release (alpha or beta) and upload to the real pypi.

**Comment by miguelsousa** [comment]
> still, i wouldn't recommend telling users to install from test.pypi.org. Just tag pre-release (alpha or beta) and upload to the real pypi.

yeah, that sounds like a better way to get things going. @cjchapman can you make this change?

**Comment by anthrotype** [comment]
a `pre` release is one with `a1` or `b2` or `rc1` appended to the version string, e.g. "2.7.0rc1" means the first release candidate for version 2.7.0
use PEP 440 as reference, so pip will parse it correctly:
https://www.python.org/dev/peps/pep-0440/

by default pip install will only install stable releases; to install pre-releases you pass the `--pre` option.

**Comment by cjchapman** [comment]
Just to be clear: I just updated the readme as a quick fix, we'll plan on making a pre-release on the main pypi.org site later.

**Comment by miguelsousa** [comment]
@cjchapman I'm going to close this issue and open a new one for that.
