### ISSUE TITLE
syntax error at "}" missing ";"

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#236]
Attempting to build [Source Code Regular](https://github.com/adobe-fonts/source-code-pro/tree/master/Roman/Instances/Regular) will fail with the following message,
```
syntax error at "}" missing ";" [font.ufo/../../../../familyTables.fea 3]
```

There's clearly a semicolon at https://github.com/adobe-fonts/source-code-pro/blob/master/familyTables.fea#L2

I can get around this issue by adding a semicolon to https://github.com/adobe-fonts/source-code-pro/blob/master/Roman/Instances/familyVersion.fea#L2 but that shouldn't be required, I think.

**Comment by cjchapman** [comment]
I think this is working as intended. If I understand the ANTLR grammar in `featgram.g` correctly, it replaces everything in the line `include (../../familyVersion.fea);` _including the semicolon_ with the contents of `familyVersion.fea`, which, in this instance, does not include a `;`, hence the error message. I suspect that if you were importing a multi-line file (i.e. for some other kind of table), this behavior might be less surprising. :-)

**Comment by mashabow** [comment]
Just for reference: #114

**Comment by duncanbaynes** [comment]
You should be able to proceed with the build if you remove the semi colon from line 2 of source-code-pro/familyTables.fea like this:

```
table head {
        include (../../familyVersion.fea)                   # No semi colon at the end of this line
} head;
```

**Comment by miguelsousa** [comment]
Sure, but the correct is to have the semicolon at the end of the include and the current version of makeotf enforces it.

**Comment by duncanbaynes** [comment]
Yeah, makes sense.
