### ISSUE TITLE
Unnecessary truncation of the Format 4 'cmap' subtable

### ISSUE THREAD

**Issue by kenlunde** [adobe-type-tools/afdko#242]
When building CID-keyed fonts with a large number of mappings that result in a large number of segments in the Format 4 'cmap' subtable, _makeotf_ seems to give up too easily and issues the following warning:

`makeotfexe [WARNING] <Format4Test-Regular> cmap{plat=3,script=1,lang=0}: cmap format 4 subtable was truncated to 2 segments, due to overflow with non-truncated version`

However, if the resulting 'cmap' table is dumped using _ttx_ and the mappings are manually added, a well-formed Format 4 'cmap' subtable seems to result. See the "commands.txt" file in the [Format4Test.zip](https://github.com/adobe-type-tools/afdko/files/1636667/Format4Test.zip) ZIP file for more details and the steps to reproduce and manually fix using a test font based on [Adobe-CNS1-7](https://github.com/adobe-type-tools/Adobe-CNS1/).

**Comment by kenlunde** [comment]
The anonymously-authored [restore_bmp_cmap.py](https://github.com/adobe-type-tools/afdko/files/1650594/restore_bmp_cmap.py.zip) script represents a second method of creating a well-formed Format 4 'cmap' subtable for affected fonts.

**Comment by miguelsousa** [comment]
Fixed via #276
