### ISSUE TITLE
[autohint] conflict problem when run simultaneously

### ISSUE THREAD

**Issue by kawabata** [adobe-type-tools/afdko#244]
Looking at autohint.py
````python
	# temp file names for input and output bez files, and for the fontinfo file.
	tempBaseName = os.path.join(tempfile.gettempdir(), "fdkautohint")
	tempBez = tempBaseName + ".bez"
	tempBezNew = tempBez + ".new"
	tempFI = tempBaseName + ".fi"
````

This seems fixed name temp file is created, causing conflicts when multiple
autohint programs run simultaneously.  It may be better create the temp file name
with proper procedure (e.g. use tempfile) .

**Comment by miguelsousa** [comment]
I totally agree.

**Comment by typemytype** [comment]
I did not fix this while porting to py3, tried to keep the original behaviour 

see https://github.com/adobe-type-tools/afdko/blob/f1c4511eaf6ae99fe784c516f16a3b8ae6a995c9/afdko/Tools/SharedData/FDKScripts/autohint.py#L1063-L1066

**Comment by miguelsousa** [comment]
Confirm that this does not happen in `psautohint`.
