### ISSUE TITLE
AFDKO linux directory not properly installed by "setup.py".

### ISSUE THREAD

**Issue by kawabata** [adobe-type-tools/afdko#245]
Installing AFDKO to linux wtih
```` sy
sudo python setup.py install
````
does not install "./afdko/Tools/linux" to proper place.

I had to run
`````sh
cp -pr ./afdko/Tools/linux /usr/local/lib/python2.7/dist-packages/afdko-2.6.24-py2.7.egg/afdko/Tools/linux

`````

to make AFDKO properly work.  I coudlnt' figure out why, but for just in case,
I will file the report.

Regards,

**Comment by cjchapman** [comment]
I tried `sudo python setup.py install` on my Linux VM and it seems to correctly install now.
