### ISSUE TITLE
Rewrite MakeOTF.py

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#249]
After going thru the process of doing some light cleanup to `MakeOTF.py` it became very clear to me that this script is in dire need of a rewrite. The main goals of this rewrite are:

- [ ] Streamline the script to 50% LOC or less
- [ ] Support Python 3.x (in addition to 2.7)
- [ ] Implement tests
- [ ] Use `argparse`
- [ ] Use `logging` (instead of `print`)

The way I'd like to go about it is to start from scratch a script named `makeotf_new.py` and build it gradually. Once this script has feature-parity with `MakeOTF.py` it will be renamed and replace the old one. I will define the first milestone for us to work on.

**Comment by kenlunde** [comment]
Another goal of this rewrite should be to integrate the latest-and-greatest subroutinizer in `tx` that takes seconds or minutes to subroutinize large CJK fonts, instead of the current hours or days.

**Comment by miguelsousa** [comment]
@kenlunde that sounds like a different goal. `MakeOTF.py` is just a wrapper for `makeotfexe`. I think that you should open a separate issue to get that enhancement into `makeotfexe`.

**Comment by cjchapman** [comment]
I suggest:
- [ ] replace uses of `eval()` with cleaner/clearer alternatives
- [ ] replace uses of `exec()` with cleaner/clearer alternatives
- [ ] specify expected exception types (i.e. no bare `except` statements)

**Comment by miguelsousa** [comment]
@cjchapman I agree with those. My expectation is that by rewriting it from scratch we'll use cleaner/clearer alternatives from the start.

**Comment by miguelsousa** [comment]
Address #280 #281 #282

**Comment by miguelsousa** [comment]
Enough has happened to `makeotf.py` since that it makes more sense to keep improving it.
Two of the original goals (Py3 and tests) have been addressed, and there's #861 to track the shifting to `argparse` and `logging`.
