### ISSUE TITLE
Create & upload Linux package to PyPI

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#251]

**Comment by miguelsousa** [comment]
Partially completed by #286

**Comment by miguelsousa** [comment]
Finished via #315.

**Comment by anthrotype** [comment]
technically we have only uploaded the source distribution package, which can be pip installed on linux (as well as on mac or windows) provided one has the compiler toolchain installed on the system.
It'd still be nice to also have a manylinux1 binary wheel package that can be installed on most Linux distros without needing to compile from source.

**Comment by miguelsousa** [comment]
Oh, thanks for the explanation. [Your comment on #315](https://github.com/adobe-type-tools/afdko/pull/315#issuecomment-382479615) gave me the impression that this was done.
