### ISSUE TITLE
Fix inconsistency of use of regionCount variable in tx.varread.varread.c

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#272]
The function tx.varread.varread.c:var_getIVSRegionIndices() takes a variable named regionCount. In some call chains, this is set to the itemVariationDataSubtable region index count, and in others it is set to the RegionList index count. In all cases, it  should be set to the RegionList index count, and the variables in this file which are named 'regionCount' should be renamed to reflect whether they contain the RegionList index count, or the data subtable region index count. See:
https://github.com/adobe-type-tools/afdko/blob/master/afdko/Tools/Programs/public/lib/source/varread/varread.c#L949

**Comment by miguelsousa** [comment]
Fixed via #397
