### ISSUE TITLE
tx and -cff command

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#278]
I’m testing tx to subroutinize fonts. As a test, I used this:
```
tx -cff +S original.otf compressed.cff
sfntedit -a CFF=compressed.cff original.otf compressed.otf
sfntedit -f compressed.otf
```
The `original.otf` was generated by `makeOTF`. The `compressed.otf` produced a slightly bigger CFF table. 

But, the bigger problem is, that is changes the glyph order in the .cff file. Why is that? Is there a way to prevent this?

**Comment by schriftgestalt** [comment]
And why is the `+S` command not mentioned when you run `tx -h` or `tx -u`?

**Comment by schriftgestalt** [comment]
I changed the topic as the problem has nothing to do with the `+S` option. Just calling `tx -cff font.pfb/otf` is causing the problem already.

**Comment by kenlunde** [comment]
I have never seen such behavior, but then again, I have only dealt with CID-keyed fonts when it comes to using _tx_ to produce CFFs from a source font. It might be useful to attach an example font the exhibits this behavior, along with something that demonstrates that the glyph order has changed.

About the `+S` command-line option producing a subroutinized CFF that is slightly larger than the one produced by _makeotf-, that is actually expected, partly because the latest subroutinizer in _tx_ is nearly three orders of magnitude faster than the one in _makeotf_. The speed is noticed when building fonts with a large number of glyphs, like the ones that I typically produce. For fonts with few glyphs, not so much. As an example, the 65,535-glyph _Source Han_ fonts take anywhere from half a day to slightly over a day to _makeotf_-subroutinize on my MacBook Pro, but only a minute or two when using the latest _tx_.

**Comment by schriftgestalt** [comment]
I just made an empty font in Glyphs and did `tx font.otf`
```
tx: --- /Library/Application Support/Adobe/Fonts/Tests/CFFtestfont-Regular.otf
tx: (cfr) /BlueScale useless (ignored)
tx: (cfr) /BlueFuzz useless (ignored)
tx: (cfr) /BlueValues missing: FD[0]
## Filename /Library/Application Support/Adobe/Fonts/Tests/CFFtestfont-Regular.otf
## Top Dict
version             "001.000"
Notice              "copyright missing"
FullName            "CFF test font Regular"
Weight              "Regular"
FontBBox            {93,-200,410,800}
FSType              8
sup.srcFontType     CFF (name-keyed)
sup.nGlyphs         67
## FontDict[0]
FontName            "CFFtestfont-Regular"
## Private
BlueScale           0.037
BlueFuzz            0
## glyph[tag] {name,encoding}
glyph[0] {.notdef,-}
glyph[1] {A,U+0041}
glyph[2] {B,U+0042}
glyph[3] {C,U+0043}
glyph[4] {D,U+0044}
glyph[5] {E,U+0045}
glyph[6] {F,U+0046}
glyph[7] {G,U+0047}
glyph[8] {H,U+0048}
glyph[9] {I,U+0049}
glyph[10] {J,U+004A}
glyph[11] {K,U+004B}
glyph[12] {L,U+004C}
glyph[13] {M,U+004D}
glyph[14] {N,U+004E}
glyph[15] {O,U+004F}
...
```

Then I made cff_ `tx -cff font.otf font.cff` and `tx font.cff` I get this result:
```
tx: --- /Library/Application Support/Adobe/Fonts/Tests/CFFtestfont-Regular.cff
tx: (cfr) /BlueScale useless (ignored)
tx: (cfr) /BlueFuzz useless (ignored)
tx: (cfr) /BlueValues missing: FD[0]
## Filename /Library/Application Support/Adobe/Fonts/Tests/CFFtestfont-Regular.cff
## Top Dict
version             "001.000"
Notice              "copyright missing"
FullName            "CFF test font Regular"
Weight              "Regular"
FontBBox            {93,-200,410,800}
sup.srcFontType     CFF (name-keyed)
sup.nGlyphs         67
## FontDict[0]
FontName            "CFFtestfont-Regular"
## Private
BlueScale           0.037
BlueFuzz            0
## glyph[tag] {name,encoding}
glyph[0] {.notdef,-}
glyph[1] {space,-}
glyph[2] {comma,-}
glyph[3] {hyphen,-}
glyph[4] {period,-}
glyph[5] {zero,-}
glyph[6] {one,-}
glyph[7] {two,-}
glyph[8] {three,-}
glyph[9] {four,-}
glyph[10] {five,-}
glyph[11] {six,-}
glyph[12] {seven,-}
glyph[13] {eight,-}
glyph[14] {nine,-}
glyph[15] {A,-}
glyph[16] {B,-}
glyph[17] {C,-}
glyph[18] {D,-}
glyph[19] {E,-}
glyph[20] {F,-}
glyph[21] {G,-}
glyph[22] {H,-}
glyph[23] {I,-}
glyph[24] {J,-}
glyph[25] {K,-}
glyph[26] {L,-}
glyph[27] {M,-}
...
```
When I put the cff back into a font I get this (screenshot from QuickLook):
<img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/174660/36631181-d2e51b10-1973-11e8-9770-23ab64513bd3.png">

**Comment by schriftgestalt** [comment]
and here is the test file: 
[CFFtestfont.otf.zip](https://github.com/adobe-type-tools/afdko/files/1754410/CFFtestfont.otf.zip)

**Comment by kenlunde** [comment]
Found it. Try `tx -cff -h` then you will see _Normally glyphs are sorted to reduce the CFF data size. The +b option forces the original glyph order to be preserved (with the exception of the .notdef glyph which is always assigned glyph index 0)._

**Comment by schriftgestalt** [comment]
Thanks.
I would expect that the `+b` option is the default. I can’t think of a use case where it is save to change the glyph order. Almost all other tables in the font rely on it.

And how does putting the `comma` first save some space in the CFF? Maybe the `cmap` could be effected, but CFF?
