### ISSUE TITLE
[makeotf] PSNameNotSpecified.otf

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#282]
When building an OTF from a UFO without PS name, a zero-kB file named `PSNameNotSpecified.otf` is created. This is unnecessary.
In addition to that, I think `makeotf` could try and create the PS name automatically (from UFO Family/Style Name) if it doesn’t exist.

**Comment by frankrolf** [comment]
I think the deeper problem here is that `makeotf` requires the `postscriptFontName` in a UFO be set. `makeInstancesUFO` no longer requires the ps font name (as per [this commit](https://github.com/adobe-type-tools/afdko/issues/179)), so perhaps it would be a good idea to remove that requirement from makeotf altogether.

**Comment by miguelsousa** [comment]
`makeotf.py` is too messy to try to squeeze in a fallback solution for when `postscriptFontName` is missing in a UFO. So in #451 I simply made **makeotf** behave the same way as when a Type 1 font without `/FontName` is used as input, which is it fails.

I'll definitely try to implement a fallback solution for the rewrite version.
