### ISSUE TITLE
Travis deploy tagged releases to PyPI

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#310]
I'm creating this issue partly to have a place to discuss this.

**Comment by cjchapman** [comment]
@anthrotype (cc: @miguelsousa) I've changed the `.travis.yml` file to have:
```
deploy:
...
  on:
    tags: true
```
...but it seems like just tagging master isn't enough to kick off a Travis build, much less deploy to PyPI. Does Travis need there to be a code commit along with the tag or something?

**Comment by cjchapman** [comment]
(Just to be clear, I tried doing a test tag in GitHub's web interface, and also one from Sourcetree, and neither triggered a build. I've deleted those tags now, but they did show up in GitHub at the time.)

**Comment by benkiel** [comment]
I have this almost working for fontParts (save an error on PyPI upload that has no helpful error message — it could be that PyPI was down, who knows) based on what font tools does. It's somewhat helpful to dig into their travis and setup.py config. 

The one thing I've learned is that Travis will do two builds for a tag, the tagged build and the master build. So it seems like nothing is happening, but actually it's waiting for the master to finish to build the tag.

**Comment by cjchapman** [comment]
@benkiel Thanks, but I looked at https://travis-ci.org/adobe-type-tools/afdko/builds and didn't see anything happening after either of the tags I created.

**Comment by cjchapman** [comment]
@benkiel Also, just to be clear: for fontParts, is Travis doing a build because you created a tag, or do you have to have a code commit with the tag? Can you describe the steps you follow to kick off a release deployment? Thanks!

**Comment by miguelsousa** [comment]
@cjchapman [here's Cosimo's explanation of the setup he did for fontPens](https://github.com/robofab-developers/fontPens/issues/7#issuecomment-362357244). Check if there's something helpful there.

**Comment by benkiel** [comment]
Perhaps it's because you need to specify a pypi server in the travis.yml?

**Comment by cjchapman** [comment]
@benkiel Well, currently I'm getting the message:
>Skipping a deployment with the pypi provider because this is not a tagged commit
...which would seem to be independent of which PyPI server I'm using, but I'll try adding it.

**Comment by cjchapman** [comment]
@benkiel Didn't help. :-(

**Comment by benkiel** [comment]
@cjchapman Yeah, I don't think that's it then. I think that you aren't actually pushing a tag, that's the problem. I have to do `git push --follow-tags` as in @miguelsousa's example above and things work (well, almost, at least the github release happens)

**Comment by benkiel** [comment]
Looking at the build history on Travis, I don't see a tagged build at all.

**Comment by cjchapman** [comment]
The tags are coming through along with the commits, not sure why Travis isn't seeing them:
https://github.com/adobe-type-tools/afdko/tags

**Comment by cjchapman** [comment]
@benkiel The tags are coming through along with the commits, not sure why Travis isn't seeing them:
https://github.com/adobe-type-tools/afdko/tags

**Comment by benkiel** [comment]
Compare to https://travis-ci.org/robofab-developers/fontParts/builds, I'm not seeing any tags (there is a tag icon in the travis list, in the middle bit of info) for the FDK. So, somehow it's not getting the tags and that's the problem

**Comment by cjchapman** [comment]
OK... I tried pushing a commit with a tag using the command line:
```
git push --follow-tags
```
...but I don’t see the tag (`pypi_deploy_test_7`) on GitHub.

**Comment by cjchapman** [comment]
Just to be clear, I do see the tag locally:
```
cchapman-macOS:afdko cchapman$ git tag
2.5.63209
2.5.64655
2.5.64958
2.5.65322
2.6.22
2.6.25
pypi_deploy_test_3
pypi_deploy_test_4
pypi_deploy_test_5
pypi_deploy_test_6
pypi_deploy_test_7
cchapman-macOS:afdko cchapman$ 
```

**Comment by cjchapman** [comment]
Prior to this I was using Sourcetree to push the commits and the tags, and the tags did seem to get through to GitHub, even though Travis did not seem to see them.

**Comment by benkiel** [comment]
That is odd and super frustrating. One difference I have is the branches: all in the Travis config, perhaps that? Seems that something is blocking the tags from hitting Travis

**Comment by miguelsousa** [comment]
This is already working from Travis (#314, #315).
The AppVeyor part is being worked on (#316).

**Comment by miguelsousa** [comment]
Done.
