### ISSUE TITLE
Deploy tagged releases to GitHub

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#317]

**Comment by miguelsousa** [comment]
3531f9ef7f4b65dccfa98a618b53599abfb76ad0 made it work for Mac and Linux 
https://github.com/adobe-type-tools/afdko/releases/tag/2.7.0b1

Now only the Windows wheel is missing.

**Comment by davelab6** [comment]
Nice to have this as an example for other projects :)

**Comment by anthrotype** [comment]
sure, but for python projects there is not much need for publishing the packages on github _in addition_ to pypi.

**Comment by miguelsousa** [comment]
> curious why do you need to deploy to github releases as well as to PyPI?

To give people the option.

> do you know if anybody is relying on the download links from the github releases page?

I don't.

**Comment by miguelsousa** [comment]
ab4c4cf67a345e32ddae9ea0bfd642bf73e04131 completed it for Windows.
