### ISSUE TITLE
[t1write] Remove *.txt files

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#332]
@readroberts can the `*.txt` files at `afdko/Tools/Programs/public/lib/source/t1write` be removed? Asking because there are `*.h` files in the same folder that seem to have the same content, and because I noticed this [comment in the `txUpdate` branch](https://github.com/adobe-type-tools/afdko/commit/2dd4cff100fc371d9c442df6ff0c705eb0671fa6),

> This project has *.txt files that used to be the source for the *.h in-line help files. That was years ago, and we don't even have the tool that built the *.h from the *.txt files anymore. The *.h files are now the master source for the in-line help text.

**Comment by bastien-roucaries** [comment]
@readroberts  Can the all right reserved header on the *.h or the .txt file could improve licensing of this fragment ? They are all right reserved or Apache licensed like afdko ?

Thanks

**Comment by bastien-roucaries** [comment]
@miguelsousa ^
