### ISSUE TITLE
[spot] MacOSX 64-bit build fails to dump any font

### ISSUE THREAD

**Issue by blueshade7** [adobe-type-tools/afdko#335]
Run MacOSX 64-bit **spot** binary as:
```spot MinionPro-Bold.otf```

Result:
```spot [FATAL]: bad input object size [8]```

**Comment by readroberts** [comment]
I can't reproduce this, either the 2012 MinionPro-Bold.otf version 2.115, or with Minion3-Bold.otf version 1.006. Can you check that the spot you are running was built as 64 bit, and point me to the MinionPro-Bold.otf  that you saw this with?

**Comment by readroberts** [comment]
PS. Are you building with the '64bit-support' branch?

**Comment by miguelsousa** [comment]
Fixed via #342
