### ISSUE TITLE
[tx] Fails to dump or convert a CFF2 font if it is not a variable font.

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#353]
A CFF2 font can be a non-variable font, in which case the length of the VariationStore table is 0. tx did not check if the length was 0 before trying to read the table.

**Comment by miguelsousa** [comment]
@readroberts does #351 not address this?

**Comment by readroberts** [comment]
Not completely. . I tried with more fonts, and found other places in the code where non-VF CFF2 fonts crashed with different tx options, or with different fonts.

**Comment by miguelsousa** [comment]
@readroberts can you attach test fonts to this issue, so we can use them when the integration tests are in place?

**Comment by readroberts** [comment]
Yes. I will try to get them done before I leave next week. Note -I  have another commit to add to this PR in a few minutes.

**Comment by miguelsousa** [comment]
@readroberts what's the status of the branch named `tx-fix-issue-353` ?

**Comment by miguelsousa** [comment]
I've deleted branch `tx-fix-issue-353` because @readroberts confirmed that the current code is working as expected. We still need a test case in place before this issue can be closed.

**Comment by miguelsousa** [comment]
Test case added via #504
