### ISSUE TITLE
[tx] Fails to convert to CFF a CFF2 variable font with some non-varying glyphs

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#356]
A glyph which is non-varying in a variable font will be referenced by a VariationStore data item subtable which has a region count of 0. The VF support code assumed that this was an error. I need to correct the title: the conversion to CFF does not fail, but it incorrectly emits an alarming warning "(cfr) out of range region index found in item variation store subtable" for each non-varying glyph.

**Comment by miguelsousa** [comment]
I'll add an option to `runner` to enable saving stderr to a file.

**Comment by miguelsousa** [comment]
Fixed via #476
