### ISSUE TITLE
makeotf wont make TTFs if path to working directory has spaces

### ISSUE THREAD

**Issue by davelab6** [adobe-type-tools/afdko#36]
Mark Simonson mentioned a bug in makeotf on the [robofab list](https://groups.google.com/d/msg/robofab/g1ezLNM5kas/phdpcfaifnYJ) about how it wont make TTFs if path to working directory has spaces

**Comment by readroberts** [comment]
A bug, needs to be fixed.

**Comment by miguelsousa** [comment]
982d672e8539c02af46bfbb196443d6d5a37ba58 may have fixed this. Please confirm.

**Comment by benkiel** [comment]
Tested with v2.0.90, this still happens, at least with a space in the source name.

**Comment by miguelsousa** [comment]
@benkiel by *source name* you mean the name of the font file used as input for `makeotf`?

**Comment by benkiel** [comment]
Yes, the space in the source TTF used as input.

**Comment by miguelsousa** [comment]
@benkiel I think 3a0b40531319504995bb74268b8be56a9edbfdc9 fixes your problem.

**Comment by miguelsousa** [comment]
There were a few other commands with problems. Hopefully the 3rd time is a charm.

**Comment by readroberts** [comment]
Fixed.
