### ISSUE TITLE
[Wish] FEA syntax extension: += and +{ 

### ISSUE THREAD

**Issue by twardoch** [adobe-type-tools/afdko#37]
I’d like to request two extensions of the FEA syntax (given of course this is also implemented in AFDKO): 

# 1. Defining a named class in fragments

## Variant 1.1

When defining named classes, the syntax ```@classname += [glyph1 glyph2...]``` should be permitted, which would allow one to define a named class in multiple fragments. It should allow for the following constructs: 
```
@LNUM += [one two three]; 
@LNUM += [four five six];
```
which would be equivalent to the current: 
```
@LNUM = [one two three four five six];
```
(Optional: the implementation should allow using the ```+=``` operator even if the class name is used for the first time — then it would simply behave as ```=```.)

## Variant 1.2

The same could be achieved in a less-invasive way (without changing the syntax) if the implementation in AFDKO is changed to allow the following: 
```
@LNUM = [one two three];
@LNUM = [@LNUM four five six];
```
Currently, this method produces an error: ```can't define a glyph class in terms of itself```. 

# 2. Defining any ```{}``` construct in fragments

## Variant 2.1

When defining any construct that is enclosed in ```{}``` (```feature```, ```lookup```, ```table```, ```anonymous```), the syntax ```feature smcp +{ definitions } smcp;``` should be permitted, which would allow one to define a construct in multiple fragments. The order of the constructs (lookups) should still by determined by the first occurrence of a construct with a particular name or tag. This should allow for the following constructs: 

```
feature smcp { 
  sub a by a.sc;
  sub b by b.sc;
  ...
  sub z by z.sc; 
} smcp; 

feature liga { 
  sub f i by f_i; 
} liga; 

feature smcp +{ 
  sub ampersand by ampersand.sc;
} smcp; 
```

This would be equivalent either to: 

```
feature smcp { 
  lookup smcp1 { 
  sub a by a.sc;
  sub b by b.sc;
  ...
  sub z by z.sc; 
  } smcp1; 
 lookup smcp2 { 
  sub ampersand by ampersand.sc;
 } smcp2; 
} smcp; 

feature liga { 
  sub f i by f_i; 
} liga; 
```

or preferably to: 

```
feature smcp { 
  sub a by a.sc;
  sub b by b.sc;
  ...
  sub z by z.sc; 
  sub ampersand by ampersand.sc;
} smcp; 

feature liga { 
  sub f i by f_i; 
} liga; 
```
(Whatever is more convenient / makes more sense from the implementation point of view.) 

(Optional: the implementation should allow using ```+{``` even if a construct’s name is used for the first time — then it would simply behave as ```{```.)

## Variant 2.2

The same could be achieved in a slightly less invasive way by adding a new keyword ```append``` which could precede any ```{``` character (similarly to how the ```useExtension``` keyword is used). 

In this variant, the following syntax would be possible: 

```
feature smcp { 
  sub a by a.sc;
  sub b by b.sc;
  ...
  sub z by z.sc; 
} smcp; 

feature liga { 
  sub f i by f_i; 
} liga; 

feature smcp append { 
  sub ampersand by ampersand.sc;
} smcp; 
```

What do you think? Is this feasible? (I’m not sure whether the FEA parser works linearly or not.) 

Adam

**Comment by miguelsousa** [comment]
@twardoch could you provide some situations where it would be useful to have this functionality?

**Comment by twardoch** [comment]
It would be useful when the font developer has a standardized "template" or "master" FEA file(s) for a given glyph set, and the developer includes them via ```include();``` and later extends some feature definitions. In general, it would greatly extend the usefulness of ```include```. One could easily modularize the template FEA files into script-specific portions and append them in sequence. Finally, it would be useful when extending the glyph sets of existing fonts. A tool wouldn't really need to present the developer with the entire existing FEA code. The developer would merely include some "patches". For example, let’s say that I add the glyphs ```uni0273``` (LATIN SMALL LETTER N WITH RETROFLEX HOOK), and ```uni0273.smcp``` to Source Sans Pro. I would merely need to write my ```uni0273.fea``` file as follows: 

```
include(SourceSansPro.fea);
feature smcp append { 
script latn; 
  sub uni0273 by uni0273.smcp; 
} smcp;
```

or

```
include(SourceSansPro.fea);
feature smcp +{ 
script latn; 
  sub uni0273 by uni0273.smcp; 
} smcp;
```

That sort of thing. :)
A.

**Comment by miguelsousa** [comment]
I see. Yeah, that could be useful.

**Comment by behdad** [comment]
I would say, this:

```
feature smcp { 
  sub a by a.sc;
  sub b by b.sc;
  ...
  sub z by z.sc; 
} smcp; 

feature liga { 
  sub f i by f_i; 
} liga; 

feature smcp +{ 
  sub ampersand by ampersand.sc;
} smcp; 
```

should create a lookup for liga, and two lookups for smcp, one of each is applied before the liga lookup and another after.

cc @brawer.

**Comment by readroberts** [comment]
This actually already exists. If you provide multiple definitions of a feature, they are all used. Lookups are added in the order in which they are encountered, as always Each separate definition of a feature generates at least one new lookup - no way to have the separate the definitions for a single feature end up in the same lookup, without a lot of work.  makeotf does generate a warning when you do this, but not an error. No need for special syntax, like 'feature < tag> + {"

**Comment by benkiel** [comment]
Read,

Would it be possible to do something like that for the table definitions? It would be handy to be able to break apart the things like the OS/2 table for the general family things that you might want only in one place, and the font specific things. Say, defining the vertical metrics once for a family, but different Panose values per font.

I also understand that doing this could be a huge headache (what happens if there are multiple entries for the same value in different places), so I don't expect this at all. However, it would be a huge help in setting up FDK mastering for larger families where keeping things in one place only reduces possible errors.

**Comment by readroberts** [comment]
You can accomplish this now by using the feature file include directive. This can contain fragments of definitions, not just whole table or feature definitions. I just checked, and makeotf is fine with a feature file include command that references a file which contains just the Panose definition.

**Comment by benkiel** [comment]
Ah, my apologies. I remember trying this a couple of years ago and didn't get it to work (but perhaps I was trying with the name table). Very good to know, thank you, and apologies for not re-testing.
