### ISSUE TITLE
[makeotfexe] another case of "Unnecessary truncation of the Format 4 'cmap' subtable"

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#400]
@kenlunde and I found another scenario that may be related to: https://github.com/adobe-type-tools/afdko/issues/242

Specifically, when running this command (see the file `command.sh`):
```
makeotf -f cidfont.ps -fi cidfontinfo -ff features -r -nS -omitMacNames -cs 3 -ch UniAKR-UTF32-H -ci Adobe-KR_sequences.txt
```
we got the warning:
```
makeotfexe [WARNING] <Format4TestAKR9-Regular> cmap{plat=3,script=1,lang=0}: cmap format 4 subtable was truncated to 2 segments, due to overflow with non-truncated version
```
~It's not clear if it really is impossible to fit the data into a cmap format 4 subtable, so the purpose of this issue is to remind us to investigate this further.~

UPDATE: Peter Constable mentioned in an email to Ken and me (Chris):
> I don't think the format 4 subtable has any limitation that would prevent encoding as many BMP characters as might be desired: there are 64K BMP characters, and format 4 can accommodate 64K codepoint range segments.

Here's the full output:
```
cchapman-macOS:Downloads cchapman$ cd Format4TestAKR9
cchapman-macOS:Format4TestAKR9 cchapman$ chmod +x command.sh 
cchapman-macOS:Format4TestAKR9 cchapman$ ./command.sh 
makeotf [Warning] Could not find an Adobe CMAP Mac encoding mapping file. If you want a Mac cmap subtable, please specify the Mac CMAP encoding file with the '-cm' option.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
makeotfexe [WARNING] <Format4TestAKR9-Regular> cmap{plat=3,script=1,lang=0}: cmap format 4 subtable was truncated to 2 segments, due to overflow with non-truncated version
 makeotfexe [WARNING] <Format4TestAKR9-Regular> cmap{plat=1,script=3,lang=0}: empty encoding
 makeotfexe [WARNING] <Format4TestAKR9-Regular> Macintosh Adobe CMap not seen
 makeotfexe [NOTE] <Format4TestAKR9-Regular> cmap{plat=0,script=5,lang=0}: Number of default Unicode Variation Sequence values 288
 makeotfexe [NOTE] <Format4TestAKR9-Regular> cmap{plat=0,script=5,lang=0}: Number of non-default UVS values 18
 
 Built release mode font 'Format4TestAKR9-Regular.otf' Revision 1.000
Done.
cchapman-macOS:Format4TestAKR9 cchapman$ 
```

**Comment by cjchapman** [comment]
The data exceeds GitHub's 10MB limit, so let me know if you need it and I'll send it to you directly.

**Comment by cjchapman** [comment]
[Format4TestAKR9.zip](https://github.com/adobe-type-tools/afdko/files/2040704/Format4TestAKR9.zip)

**Comment by cjchapman** [comment]
The problem is that each segment of consecutive Unicodes with consecutive glyphs costs 8 bytes, and each segment with non-consecutive glyphs costs an additional 2 bytes per glyph, so regardless of how large the segment count can theoretically be (e.g. in Peter's comment above), these costs are exceeding the 64K limit imposed on the cmap subtable size when we try to create a cmap format 4 subtable for an Adobe-KR-9 font. That is because the data is severely fragmented -- adjacent Unicodes often have non-adjacent glyph indices due to the grouping of glyph indices by frequency rather than by Unicode in Adobe-KR-9.

**Comment by kenlunde** [comment]
This leaves us in a [_chicken or the egg_](https://en.wikipedia.org/wiki/Chicken_or_the_egg) dilemma, because on one hand, the Format 4 subtable should not be referenced if there is a Format 12 subtable in the same font, but on the other hand, the heuristics on which the Excel and Notepad apps depend require a not-truncated-to-only-the-first-two-segments Format 4 subtable.

**Comment by cjchapman** [comment]
Some additional info, just for future reference -- for the attached font, we get:
4712 segments
14721 glyphs that have to be explicitly listed at the end of the cmap subtable

So the size of the cmap format 4 subtable would be:
16 bytes of header + 8 bytes/segment * 4712 segments +  2 bytes/glyph * 14721 glyphs = 67154 bytes

**Comment by readroberts** [comment]
Do the heuristics in Excel and Notepad require  complete coverage? It would certainly be possible to build a partial coverage format 4 subtable, which is truncated just enough to allow it to build without overflowing.

**Comment by kenlunde** [comment]
No, the heuristics in Excel and Notepad do not require complete coverage, as evidenced by the versions of the two OpenType/CFF fonts that are available in the [latest release](https://github.com/adobe-type-tools/Adobe-KR/releases/latest/) of the Adobe-KR-9 specification whose Format 4 subtables lack mappings for the 8,000+ CJK Unified/Compatibility Ideographs.

**Comment by cjchapman** [comment]
I'm going to close this issue because it's a problem inherent in the specification of the `cmap` format 4 subtable, rather than an AFDKO issue.

We have a work-around for this issue, which @kenlunde documented here:
https://github.com/adobe-type-tools/Adobe-KR#opentype-development

Here's an excerpt from that documentation:
>The two fully-functional example OpenType fonts in the [latest release](https://github.com/adobe-type-tools/Adobe-KR/releases/latest) worked around this issue by tailoring the Format 4 &#x27;cmap&#x27; subtable to exclude the mappings for all CJK Unified Ideographs and CJK Compatibility Ideographs. (The Format 4 &#x27;cmap&#x27; subtable is used only for the purpose of heuristics, and the glyphs for CJK Unified Ideographs and CJK Compatibility Ideographs work correctly because the [Format 12 &#x27;cmap&#x27; subtable](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-12-segmented-coverage) is used for actual rendering of those and other glyphs in the font.)
