### ISSUE TITLE
[makeInstancesUFO] move to ufoProcessor?

### ISSUE THREAD

**Issue by LettError** [adobe-type-tools/afdko#402]
The designspace reader/writer in `mutatorMath.ufo` has been succeeded by [ufoProcessor](https://github.com/LettError/ufoProcessor) and [fontTools.designspaceLib](https://github.com/fonttools/fonttools/tree/master/Lib/fontTools/designspaceLib). 

* `designspaceLib` is the reader and writer
* `ufoProcessor` is a subclass that can generate UFOs with both mutatorMath and varlib.model if necessary. The varlib.model math has some advantages with non-aligned masters, but it can not extrapolate. 

The designspace format has been upped to `4` to reflect some changes in the rule element. I have no plans to update `mutatorMath.ufo`.

**Comment by miguelsousa** [comment]
Thanks for the heads-up. I'll look into it.

**Comment by miguelsousa** [comment]
I've published **ufoProcessor** to PyPI https://pypi.org/project/ufoProcessor/

**Comment by LettError** [comment]
Thank you @miguelsousa!
