### ISSUE TITLE
Installing may downgrade dependencies

### ISSUE THREAD

**Issue by moyogo** [adobe-type-tools/afdko#408]
In `setup.py`, `install_requires` is filled with the content of [`requirements.txt`]( afdko/requirements.txt).
https://github.com/adobe-type-tools/afdko/blob/develop/setup.py#L205
https://github.com/adobe-type-tools/afdko/blob/develop/setup.py#L145-L147

These requirements dependency versions are pinned with version matching, which means some packages may be downgraded to those versions if more recent versions happen to be installed.

Could these be changed to inclusive ordered comparison `>=` or compatible release `~=` instead of version matching `==`?

**Comment by cjchapman** [comment]
@moyogo I'm OK with either approach, but I'm not sure what @miguelsousa's thoughts are (as he's on leave right now), so for now I've submitted a PR to check for compatible releases (`~=`). Once I hear from him, if he's OK with ordered comparison (`>=`), I'll make that change.

In related news, I sent you a collaborator invite. Sorry for not doing this sooner, I had assumed you were already on the list until I tried to add you as a reviewer to the PR.

**Comment by readroberts** [comment]
I think this is a good idea. Definitely for modules like setuptools. I am am ambivalent about the modules related to font tools, as these move quickly, and at any moment may break the afdko. However, I overall favor taking the latest, and taking the work fo keeping up.

**Comment by anthrotype** [comment]
https://packaging.python.org/discussions/install-requires-vs-requirements/

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

For more on “Abstract” vs “Concrete” requirements, see https://caremad.io/2013/07/setup-vs-requirement/.

**Comment by moyogo** [comment]
@cjchapman Thanks!

I think pyup-bot will restore the `==` in its next PR. Maybe these need to be changed when `requirements.txt` is read to fill `install_requires`.

**Comment by anthrotype** [comment]
no, I think pyup bot leaves open ended requirements as they are, unpinned. Only updates those that are `==`

**Comment by miguelsousa** [comment]
I'm fine with unpinning as long as that doesn't block pyup-bot from updating the version numbers.

pyup-bot runs every Monday, we've been issuing pre-release builds regularly, and we're getting closer to having more frequent official releases; so I don't expect the versions of the dependencies to lag that much.

@moyogo can you provide a specific situation where the afdko version requirements are causing a problem?

**Comment by moyogo** [comment]
@miguelsousa It hasn’t caused a problem as such. But in the case there is a bug fix in one of the dependencies, it would be better to not have `pip install afdko` downgrade it in between afdko releases.

**Comment by miguelsousa** [comment]
> It hasn’t caused a problem as such. But in the case there is a bug fix in one of the dependencies

If that happens, just open a new issue with the specific request for the dependency in question, and we'll issue a pre-release build shortly after, which can be installed with `pip install -U afdko --pre`.

I'm fine with unpinning the **dev** dependencies, but my preference is to keep the font-related dependencies pinned.

**Comment by cjchapman** [comment]
@miguelsousa I reset `requirements.txt` to using `==` in the PR.

Do you want `requirements-dev.txt` to use `~=` (as it is now in the PR) or `>=`?

**Comment by miguelsousa** [comment]
@cjchapman `>=` is preferable, I think.

**Comment by cjchapman** [comment]
@miguelsousa Done.

**Comment by anthrotype** [comment]
the problem with the use of `==` is that it makes it impossible to install the afdko in the same environment alongside other tools that share some of the dependencies, e.g. fontmake.
I had to jump the hoops in order to be able to have both the latest fontmake (whose minimum requirements are greater than the latest afdko) and makeotf in the $PATH.
When using entry_points created via setuptools (as in `pip install -e .`), pkg_resources will check that the dependencies are satisfied:
```
pkg_resources.DistributionNotFound: The 'fonttools>=3.27.1' distribution was not found and is required by ufo2ft, fontmake
```
I understand the rationale for pinning in your case, since the afdko is really designed to be used as an "application" for end users, not as a library to import in other libraries/applications, so you would like the tools at each release to produce identical outputs and not change depending on the current versions of the dependencies.
But .. I have no but, really. I think it'd be better to use `~=` or `>=` in setup.py.

**Comment by cjchapman** [comment]
OK, so as of now, `requirements-dev.txt` uses `>=` for everything and `requirements.txt` uses `~=` for everything. I hope that this works out OK for everyone.

**Comment by anthrotype** [comment]
thank you. I just hope the pyup bot won't come later and put them back to `==`. The problem for me was not that you are using pinned versions in the requirements.txt file, but that you reuse the same pinned requirements.txt for the setup.py's `install_requires`. Will see.

**Comment by cjchapman** [comment]
@anthrotype The pyup bot just did an update in https://github.com/adobe-type-tools/afdko/pull/429, and it did use `==`, but it was easy enough for me to edit it and change it to `~=` with GitHub's web-based editor.

**Comment by anthrotype** [comment]
so are you planning to do that manually every week? What's the use of a bot if you have to intervene manually afterwards...
I still think it'd be best to decouple the install_requires from the requirements.txt -- but I think I've explained myself already.

**Comment by cjchapman** [comment]
@anthrotype I think the bot is useful for letting us know which packages are out-of-date. It took me much less time to change `==` to `~=` than it has taken me to compose this comment.

I defer to @miguelsousa on the topic of decoupling `install_requires` from `requirements.txt`.

**Comment by miguelsousa** [comment]
> I still think it'd be best to decouple the install_requires from the requirements.txt

I've read and re-read https://caremad.io/posts/2013/07/setup-vs-requirement/ and I'm still not convinced that decoupling is a good option for the FDK. We have too many dependencies that are updated quite frequently. Leaving the install requirements open is asking for trouble IMO, since it gives no guarantee that all the libraries are going to play well together.

> What's the use of a bot if you have to intervene manually afterwards...

We have to intervene anyway, because a human is required for doing the merge. Re-instating `~=` is negligible overhead. The bot is doing the helpful job of updating the version numbers.

**Comment by anthrotype** [comment]
Allow me to repeat myself but I really dislike that I can't install `afdko` inside an existing virtual environment without the risk of inadvertently downgrading already installed packages (sometimes these may be in-development versions that have not been deployed yet to PyPI).
The afdko is the only python application that I know of that does this exact-version-pinning of its setup.py's `install_requires`. I really wish it specified only open-ended, minimum versions.

**Comment by josh-hadley** [comment]
From discussion with @cjchapman and @miguelsousa , the reasons for strict pinning (with `==`) are no longer relevant, so we'll update `requirements.txt` to use `>=` for whatever we have in there now.

**Comment by anthrotype** [comment]
Thank you!

**Comment by josh-hadley** [comment]
For the record, the relaxing of hard-pinning versions appears to have come back to haunt us on the `ufoProcessor` package, which was recently updated with changes that break AFDKO tests. We will be modifying the requirements.txt for that package to pin to a very narrow range. Should it become necessary, we'll do the same for other packages.
