### ISSUE TITLE
[makeotfexe] error with pos base statements in same lookup referencing different mark classes

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/afdko#416]
the following feature file fails to compile with the latest makeotf:

```
markClass dotbelow-ar <anchor 89 -3> @MC_bottom;
markClass hamzaabove-ar <anchor 141 462> @MC_top;

feature mark {
    lookup mark2base {
        pos base hamza-ar <anchor 225 -3> mark @MC_bottom \
                          <anchor 231 505> mark @MC_top;
        pos base highhamza-ar <anchor 99 799> mark @MC_top;
    } mark2base;
} mark;
```

The error message doesn't make sense to me:

```
$ makeotf -o output.ttf -f NotoSansArabic-SemiBold.ttf -ff NotoSansArabic-SemiBold.fea
...
 makeotfexe [ERROR] <NotoSansArabic-SemiBold> MarkToBase or MarkToMark: A previous statement has already assigned the current mark class to another anchor point on the same glyph 'highhamza-ar'. Skipping rule.  [NotoSansArabic-SemiBold.fea 7]
 makeotfexe [FATAL] <NotoSansArabic-SemiBold> aborting because of errors
 makeotf [Error] Failed to build output font file 'output.ttf'.
```

This is the font to reproduce issue: https://github.com/fonttools/fonttools/files/2098063/markbase-makeotf-issue.zip

I would like to know what is wrong with that feature file snippet, and why it throws a fatal error with makeotf whereas it compiles fine with feaLib:

https://github.com/fonttools/fonttools/issues/1273

This commit seems to be the culprit, but I don't quite understand what's trying to do:
https://github.com/adobe-type-tools/afdko/commit/20af6dd516d5ba1db7df2512b4f5496229c28b3e

**Comment by readroberts** [comment]
I agree that the the error message needs to be fixed. See my comment on Tues July 3 3, https://github.com/fonttools/fonttools/issues/1273, for the history of why makeotfexe does not allow NULL anchors for mark to base and mark to mark.

**Comment by miguelsousa** [comment]
@anthrotype @readroberts so `makeotfexe` is working as expected and this issue can be closed, yes?

**Comment by anthrotype** [comment]
The error message needs to be made clearer
