### ISSUE TITLE
makeotf always exits with 0 (i.e. success)  even when error occurs

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/afdko#417]
The MakeOTF.py script's main() function _does not_ return a non-zero value to the calling shell when an exception occurs and the font was not built successfully. Currently _all_ exceptions are handled and passed, so main always exits successfully:

https://github.com/adobe-type-tools/afdko/blob/56befefb4b3f6daa26d670d05e3c95df4ec32dd5/afdko/Tools/SharedData/FDKScripts/MakeOTF.py#L3063-L3073

in fontmake there's an optional FDKFeatureCompiler that calls makeotf as subprocess. That code is broken for many reasons, one of which is that it attempts to guess whether the build was successful from the messages printed to stdout, because the exit code is meaningless.

**Comment by anthrotype** [comment]
(just realised I forgot an important "does not" in the previous message, so the logic was inverted; I edited the comment)

**Comment by miguelsousa** [comment]
@anthrotype fix done. Just waiting for your review
