### ISSUE TITLE
Different tempfile handling still needed on Windows?

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#430]
@readroberts can you give an insight on why this Windows-specific tempfile code is needed?
https://github.com/adobe-type-tools/afdko/blob/develop/afdko/Tools/Programs/tx/source/tx.c#L682-L695
Was this for older versions of Windows? Commenting it out doesn't seem to have any side effects, as you can see from #426.

**Comment by anthrotype** [comment]
apparently [Appveyor always runs as administrator](https://help.appveyor.com/discussions/questions/1888-running-tests-with-reduced-privileges), that's why tmpfile works there.

See @readroberts comment https://github.com/adobe-type-tools/afdko/issues/20#issuecomment-92968537

**Comment by miguelsousa** [comment]
Thanks Cosimo. That's all we needed to know 😄
