### ISSUE TITLE
Allow any languages under DFLT script

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/afdko#438]
quoting the updated OpenType spec https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2

> a font is permitted to have a 'DFLT' script table with non-default language system tables, and an application may use features associated with one of these if the the 'DFLT' script table is applicable — no script table is present for the specific script, or there is no specific script in the text context — and if one of the particular language systems is specified. Under such conditions, applications should support use of a non-default language system table that is associated with 'DFLT' script if a font includes tables with this configuration.

but the published version of the Adobe Feature File spec still says:

> The only permitted language tag for the 'DFLT script is 'dflt'.

The latter should be changed to match the OpenType spec.

Also see https://github.com/fonttools/fonttools/pull/1278

**Comment by readroberts** [comment]
@anthrotype @msousa I agree that the spec should change to match the updated OpenType spec. Miguel, do you want to do this, or would you like me to do it?

**Comment by miguelsousa** [comment]
@readroberts you do it, since this requires a change to **makeotfexe** as well, I believe. And when you submit the fix please include a test case as well.
