### ISSUE TITLE
Versionned release zip files (and folder) with version major.minor.change

### ISSUE THREAD

**Issue by n7s** [adobe-type-tools/afdko#44]
Please provide versionned release zip files with complete version major.minor.change on the AFDKO website:

Something like, for example, AFDKO-2.50-63782.zip which then expands into a folder called AFDKO-2.50-63782/ would help isolate different versions much better and also make installation easier.

Thanks.

**Comment by davelab6** [comment]
www.semver.org versioning would be great :)

**Comment by readroberts** [comment]
Yep, a good idea. Will do some time soon, as in the next few months.

**Comment by davelab6** [comment]
@readroberts when is the next release due? :)

**Comment by readroberts** [comment]
Just posted it.  The download files have version numbers.

**Comment by n7s** [comment]
Just noticing that the folder is still called FDK when unzipped. Any chance this can be versionned as well, please?

**Comment by n7s** [comment]
Could you also consider tagging the new release in here? Thanks.

**Comment by davelab6** [comment]
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by readroberts** [comment]
Clearly a good idea. Done.

**Comment by davelab6** [comment]
btw you can also attach non-git-managed files to a release, so where you say

> This release was used to build the fully configured and installable version of the AFDKO, "2.5 build 63209, Sep 18 2014" currently available at: http://www.adobe.com/devnet/opentype/afdko.html

you can also make the file available from that release item as an attachment

**Comment by miguelsousa** [comment]
> you can also make the file available from that release item as an attachment

Done. I've also fixed the tag from Sep 18 2014.

**Comment by davelab6** [comment]
@miguelsousa handy, thanks!
