### ISSUE TITLE
autohint  AutoHinting program v1.46 Feb 10 2105

### ISSUE THREAD

**Issue by nlsp** [adobe-type-tools/afdko#45]
The subject says it all. This is the current latest download from the adobe site FDK

FDK. v2.5 March 3 2015 change number 63782 is in the FDKReleaseNotes.txt file. Which of those date is the correct one?

N.

**Comment by miguelsousa** [comment]
The year has been corrected by #43.
Each FDK tool has its own date, and the whole toolkit has its release date. So these differences are expected.
