### ISSUE TITLE
makeotf option description is not accurate (-cs / -cl)

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#459]
option `-cs` / `-cl` described as follows:

> Override the heuristics, and specify the ScriptID / LanguageID for the Macintosh 'cmap' subtable; CID-keyed fonts only.

By my test, the option is not only available for CID-keyed fonts, **also works for name-keyed fonts**.

**Comment by miguelsousa** [comment]
@LIXiangChen thanks for the report, I get the same results.

@readroberts what should be done here? 1. Change the documentation, or 2. change the implementation? I favor 1, because I don't see a reason for limiting those options to CID fonts.

**Comment by readroberts** [comment]
@msousa In the short term, I would  change the documentation. I would, however, prefer to change makeotf to not make Mac cmap tables, which I believe have not been needed for some years, and suppress the related options. However, this will require some time for testing and research to see if it is safe.
