### ISSUE TITLE
Typo in GDEF table docs

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#46]
In http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.b there is a stray LigatureCaret which I think is a typo, and probably was meant to be the (not implemented) `LigatureCaretByDev`.

**Comment by readroberts** [comment]
Correct on all accounts. I will fix this now.

**Comment by khaledhosny** [comment]
Thanks.
