### ISSUE TITLE
[makeinstancesufo] progress bar writes newline for every glyph checked

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#474]
The progress bar of `checkoutlinesufo` (one dot per glyph) is rudimentary, but it has gotten even less useful in version 2.0.3. Now, each dot is followed by a newline character, which makes output entirely insignificant.

```
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
```

Would it be possible to implement a progress bar, as know from `pip` or `homebrew`?

**Comment by miguelsousa** [comment]
I can't reproduce this. What options did you use? This is the output I get using no options:
```
Hbar There is an overlap. 
. 
Hcedilla There is an overlap. 
. . . . . . . . . . . . . . . . . 
Ieukran There is an overlap. 
. . . . . . . . . . . . . . . . . 
K There is an overlap. 
Ka There is an overlap. 
Kabashkir There is an overlap. 
Kadescender There is an overlap. 
Kappa There is an overlap. 
Kcommaaccent There is an overlap. 
Kdotbelow There is an overlap. 
Kje There is an overlap. 
Klinebelow There is an overlap. 
. . . . . . . . . 
Lje There is an overlap. 
. 
Lslash There is an overlap. 
. . . . . . 
NNBS has no contours 
. . . . . . 
Nje There is an overlap. 
. . . . . . 
Obarcyr There is an overlap. 
. . . . . . . . . . . . . . 
Ohorn There is an overlap. 
Ohornacute There is an overlap. 
Ohorndotbelow There is an overlap. 
Ohorngrave There is an overlap. 
```
> Would it be possible to implement a progress bar, as know from pip or homebrew?

I think so.

**Comment by frankrolf** [comment]
I used it in the context of `makeinstancesufo`. I noticed also the progress dots of autohint are differently spaced too, so perhaps `makeinstancesufo` inserts new line breaks?

**Comment by miguelsousa** [comment]
I see. It must have been introduced in #461. I'll fix it.

**Comment by davelab6** [comment]
BTW @felipesanches wrote a fun progress bar for fontbakery that you might like to review :)

**Comment by miguelsousa** [comment]
@davelab6 thanks. I'm planning to implement something more lightweight, like
```
Progress: |██████████████████████████   | 87%
```
