### ISSUE TITLE
Move non-essential scripts out of afdko

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#488]
I propose moving the list of files below out of afdko and into [python-scripts](https://github.com/adobe-type-tools/python-scripts) repo.

* BuildMMFont.py
* checkUFOProcessedLayer.py
* copyCFFCharstrings.py
* kernCheck.py

@readroberts @kenlunde @frankrolf @cjchapman @pauldhunt do you have any objection or further suggestions?

**Comment by kenlunde** [comment]
No objections from me. _copyCFFCharstrings.py_ became less important when we improved the _tx_ subroutinizer to be almost three orders of magnitude faster than the one in _makeotf_.

**Comment by readroberts** [comment]
@msousa fine by me too.

**Comment by cjchapman** [comment]
Fine by me.

**Comment by frankrolf** [comment]
I never used any of the above scripts, so I am fine with moving them.
