### ISSUE TITLE
The online version of the specification is outdated

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#49]
The web page http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html is “last updated 4 Sept 2012”, but there have been at least two fixes to the specification since then but not reflected there.

**Comment by behdad** [comment]
Where is the latest version?

**Comment by khaledhosny** [comment]
`FDK/Technical Documentation/OpenTypeFeatureFileSpecification.html` in this repository.

**Comment by readroberts** [comment]
Fixed in spec version 1.1.9

**Comment by readroberts** [comment]
Sorry, closed wrong issue. Will fix this within a week.
