### ISSUE TITLE
[ttx] <created>/<modified> value format in `head` table

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#507]
I'm not sure the issue should be reported here or the `fonttools` project.

I found that the "day of month" have no leading zero, though, there will be an extra space in front of it, like this:

![qqqqq](https://user-images.githubusercontent.com/8857634/43047906-79dd75b8-8e11-11e8-9616-d2eb44080cf4.png)

I think this should be fixed.

**Comment by miguelsousa** [comment]
Please report it at https://github.com/fonttools/fonttools/issues
