### ISSUE TITLE
set up nightly builds on AppVeyor and Travis to run longer tests

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#527]
### Travis
https://docs.travis-ci.com/user/cron-jobs/
Note: To check whether a build was triggered by cron, examine the `TRAVIS_EVENT_TYPE` environment variable to see if it has the value `cron`.

### AppVeyor
https://www.appveyor.com/docs/build-configuration/#scheduled-builds
Note: `APPVEYOR_SCHEDULED_BUILD` - `True` if the build runs by scheduler

**Comment by miguelsousa** [comment]
This is basically done.

On Travis, a cron build runs every 24 hours, counting from the last manual or automated build. See the builds flagged with the **CRON** label in the [Build History page](https://travis-ci.org/adobe-type-tools/afdko/builds).

On AppVeyor, a scheduled build runs every day at 8AM Pacific (3PM UTC).

The automated builds run all the tests. No conditional build settings were used, despite what the title of the issue suggested.
At this time the afdko's dependencies are pinned, so we shouldn't expect any failures between manual and automated builds. But in a future where we unpin the dependencies, any failures of the automated builds should serve as an indication that work is required somewhere.
