### ISSUE TITLE
The packages should include LICENSE for open source tools

### ISSUE THREAD

**Issue by upsuper** [adobe-type-tools/afdko#54]
I found that the `ttx` included in AFDKO is [an opensource tool with MIT license](https://github.com/behdad/fonttools/blob/master/LICENSE.txt), which requires distributor to include its license with any distribution.

**Comment by readroberts** [comment]
This file actually comes from the third-party repository 'fontTools', and should not be checked in under the afdko-specific sources. I have removed it from this repository.

**Comment by upsuper** [comment]
I meant, the official release of AFDKO package should probably include the license file for ttx.
