### ISSUE TITLE
revisit how we use ANTLR

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#548]
Currently we have an old copy of ANTLR in the makeotf source tree. I think we should switch over to using the latest version, perhaps pulling it down as a git submodule or using a download from their homepage, rather than keeping a copy in our source tree.

Here's ANTLR on GitHub:
https://github.com/antlr

Here's the main ANTLR homepage:
http://www.antlr.org

**Comment by miguelsousa** [comment]
Work on this should not start until #781 is resolved.

**Comment by cjchapman** [comment]
See also the related issue #83.
