### ISSUE TITLE
[tx] mtx option produces wrong {left,bottom,right,top} values for blank glyphs

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#587]
In afdko version 2.7.2,
```
$ tx -mtx t1pfa.pfa 
### glyph[tag] {gname,enc,width,{left,bottom,right,top}}
glyph[0] {.notdef,-,653,{89,0,565,660}}
glyph[1] {a,0x61,504,{52,-12,433,498}}
glyph[2] {negative,-,-4,{0,0,0,0}}
```
```
$ tx -mtx font.ttf
### glyph[tag] {gname,enc,width,{left,bottom,right,top}}
glyph[0] {.notdef,0x42,653,{89,0,565,660}}
glyph[1] {a,0x0041,504,{52,-12,433,498}}
glyph[2] {g2,-,0,{0,0,0,0}}
```
---
In version 2.7.3a6,
```
tx -mtx t1pfa.pfa 
### glyph[tag] {gname,enc,width,{left,bottom,right,top}}
glyph[0] {.notdef,-,653,{89,0,565,660}}
glyph[1] {a,0x61,504,{52,-12,433,498}}
glyph[2] {negative,-,-4,{-9223372036854775808,-9223372036854775808,-9223372036854775808,-9223372036854775808}}
```
```
$ tx -mtx font.ttf
### glyph[tag] {gname,enc,width,{left,bottom,right,top}}
glyph[0] {.notdef,0x42,653,{89,0,565,660}}
glyph[1] {a,0x0041,504,{52,-12,433,498}}
glyph[2] {g2,-,0,{-9223372036854775808,-9223372036854775808,-9223372036854775808,-9223372036854775808}}
```

[test_fonts.zip](https://github.com/adobe-type-tools/afdko/files/2316637/test_fonts.zip)

**Comment by readroberts** [comment]
@miguelsousa @cjchapman This happened in commit fbaac1 on 6/29, when Chris modified absfont_metrics.c::glyphBeg() to initialized the BBox to +-FLT_MAX instead of zero. This is the right thing to do, but we need to check in absfont_metrics.c::glyphEnd() if the values have ever been set, and if not, set them to 0.

**Comment by readroberts** [comment]
This is very simple - much more time will go into writing the tests than fixing the code. I can fix this sometime next week, but Chris will need to do this if you need it earlier.

**Comment by miguelsousa** [comment]
@readroberts thanks for the pointers, we'll get it fixed
