### ISSUE TITLE
Does visual studio 2015 can compile thissource code?

### ISSUE THREAD

**Issue by zouchengjun** [adobe-type-tools/afdko#608]
For the work,i just use vs2015 now.
Dose it use this code currectly?

**Comment by miguelsousa** [comment]
You can compile it with VS 2017. x64 configuration is being added this week.

**Comment by zouchengjun** [comment]
> You can compile it with VS 2017. x64 configuration is being added this week.

Thanks for replying.
There is  no  vs2017 in my pc.I only use vs2015.
Is there a solution to use this code in vs2015.
I googled to find a solution.Just edit the version number in the sln file's head line?

**Comment by miguelsousa** [comment]
> Is there a solution to use this code in vs2015.

I don't know. The solution files are inside the folders named **visualstudio** in the [c folder tree](https://github.com/adobe-type-tools/afdko/tree/develop/c). Try loading them in VS2015.

**Comment by readroberts** [comment]
I don't know either. I suggest trying it. There is a good chance that it will work, as the solution and project files uses only very simple versions of the Visual Studio C settings.  I notice that the *.sln has the setting:
MinimumVisualStudioVersion = 10.0.40219.1
which should mean that it is backwards compatible to Visual Studio 2010.
You might need to edit  'ToolsVersion' number at the top of the *.vcxproj file.
