### ISSUE TITLE
[makeotfexe] CFF's FontBBox is not updated when -gs option is used

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#617]
The `CFF ` table's FontBBox values are not updated when **makeotfexe**'s `-gs` option is used, and this sometimes leads to discrepancies with `head` table's xMax, yMax, xMin, yMin values.

This issue relates to https://github.com/adobe-fonts/source-sans-pro/issues/146

**Comment by readroberts** [comment]
@miguelsousa @cjchapman  This is nontrivial to fix. I will defer working on this until the higher priority tasks are done. 

The FontDict  values are set for good by the call to saveDicts() at makeotf_lib/source/typecomp/parse.c::parseFont() line 1519. The typecomp parseFont() function does not interpret the Type1 charstrings; it simply parses and transforms the Type1 numbers and operator codes to the T2 equivalents, one item at a time, with no context. There is no stack, such that you could look at the x and y values that have been seen when you get to a move-to operator. I think it probably makes more sense to re-write the CFF table after fixing the CFF TopDict FontBBox values in hot.c,  than to add interpreter logic to typecomp/parse.c::parseFont().  Recalculating the BBox is trivial - I can just re-use the hot.c::calcBBox() function, with some fix-up. What will take some time is updating the blob of CFF data in the temp file. This is still not a huge amount of work - half a day to a two days - but certainly isn't 15 minutes.

**Comment by miguelsousa** [comment]
@readroberts thanks for the summary. When I looked at the code I also got the sense that the fix would not be trivial. I've removed this bug from the current sprint.
