### ISSUE TITLE
Build notes refer to booleanOperations fork that does not exist

### ISSUE THREAD

**Issue by codeman38** [adobe-type-tools/afdko#62]
The `FDK Build Notes.txt` file, in its instructions for setting up the Python environment, states:

> 3.3 BooleanOperations support
> This is needed for the checkOutlinesUFO command.
>
> booleanOperations-master: master branch of booleanOperations at:
> https://github.com/typesupply/booleanOperations/tree/ufo3/.

This repository does not appear to exist. The original repo at https://github.com/typemytype/booleanOperations still exists, but it does not have a `ufo3` branch.

**Comment by miguelsousa** [comment]
Fixed via bdd78126831e774215e6bcd4f150684eb8a3d627.
