### ISSUE TITLE
[beztools.py] Traceback in convertBezToT2(bezData) from afdko/python/afdko/beztools.py

### ISSUE THREAD

**Issue by llsmrsll** [adobe-type-tools/afdko#629]
If I use `autohint`, I get an error in case of some glyphs.
It also occurs in the latest(2.8.3a0) `autohint`.
In `convertBezToT2`, when entering `if numHHints> = hintLimit:`, the type of `hintLimit` becomes `float` and problems arise.
Please, can you look at this part?

**Comment by miguelsousa** [comment]
Please provide a test font. It just needs to contain the glyphs that cause the problem.

**Comment by llsmrsll** [comment]
I have made a test font that causes this problem.
https://github.com/llsmrsll/samplefile/blob/master/autohintError__afdko__issue629.otf

Please execute auto hint on font and make sure TypeError occurs in glyph with CFF ID cid00002.

```shell-session
$ autohint -r -o ./output.otf ./autohintError__afdko__issue629.otf
```

This problem occurs in Python 3.

https://github.com/adobe-type-tools/afdko/blob/99eac8404b79b163a9541c413f7428516f37dc72/python/afdko/beztools.py#L1058
