### ISSUE TITLE
cvxx FeatureParams history

### ISSUE THREAD

**Issue by bobh0303** [adobe-type-tools/afdko#63]
Is there a reason that [OpenTypeFeatureFileSpecification.html](https://github.com/adobe-type-tools/afdko/blob/master/FDK/Technical%20Documentation/OpenTypeFeatureFileSpecification.html) says:
> 8.d. UI Label names for Character Variant 'cv01 - cv99') features
> As of the OpenType specification 1.7, UI label names are allowed for Character Variant features. 

when in fact the UI labels were present when cvxx was introduced in [version 1.6](http://www.microsoft.com/typography/otspec160/features_ae.htm#cv01-cv99) of the specification?

**Comment by readroberts** [comment]
Yes, my error. Will  fix.

**Comment by readroberts** [comment]
Fixed in spec version 1.19
