### ISSUE TITLE
Can't install FDK FontLab macros

### ISSUE THREAD

**Issue by skolato** [adobe-type-tools/afdko#64]
Can't instal FDK FontLab macros MAC OSX, Yosemite 10.10.5, FontLab Studio 5.1.4. After sucessfull installation of FDK i can't instal macros. I have following messages. Can somebody HELP please. Thank you.
<img width="584" alt="screen shot 2015-08-22 at 7 34 55 pm" src="https://cloud.githubusercontent.com/assets/13920485/9425136/4d466cca-4905-11e5-8157-a7956b84876e.png">

**Comment by readroberts** [comment]
The FontLab macros were omitted from the last FDK release. For the next one, I will update the Read-Me_First.html file to describe how to get them. At the moment, only way to get them is to download a zip of this repository. The FontLab macros are at: FDK/Tools/Program/FontLab. 'cd' to that directory, and run "installFontLabMacros.py".

**Comment by readroberts** [comment]
The latest version of the scripts are now on GitHub, at https://github.com/adobe-type-tools/fontlab-scripts.
