### ISSUE TITLE
[tx] Bounding box not calculated correctly when start point is on right most edge of bounding box

### ISSUE THREAD

**Issue by benkiel** [adobe-type-tools/afdko#655]
When looking for the answer for why `comparefamily` was incorrectly reporting bogus stems for a typeface, I realized that with a glyph like so:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="guilsinglright" format="1">
  <advance width="0"/>
  <outline>
    <contour>
      <point x="261" y="202" type="line"/>
      <point x="261" y="227" type="line"/>
      <point x="77" y="435" type="line"/>
      <point x="74" y="435" type="line"/>
      <point x="40" y="386" type="line"/>
      <point x="40" y="383" type="line"/>
      <point x="182" y="202" type="line"/>
      <point x="40" y="25" type="line"/>
      <point x="40" y="22" type="line"/>
      <point x="58" y="-5" type="line"/>
      <point x="61" y="-5" type="line"/>
    </contour>
  </outline>
</glyph>
``` 

the bounding box gotten by comparefamily with `tx` from here: https://github.com/adobe-type-tools/afdko/blob/b7b86e18dc433e6c775989369af6862b85bf60d2/python/afdko/comparefamily.py#L974 has the bounding box at 236, not 221 like it should be. This seems consistent with glyphs that have their start point on the right edge.

**Comment by miguelsousa** [comment]
Thanks for the report @benkiel. I've created branch `tx-glyphybboxes-bug655` containing a test case and @cjchapman will have a look at it.

**Comment by benkiel** [comment]
@miguelsousa thank you!
