### ISSUE TITLE
[otc2otf] Add option to specify output path of ttf/otfs being output

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#67]
Considering subfonts in some ttcs may not contain a Postscript name in the `name`, `otc2otf` may rewrite files it already written. Therefore giving an option to specify output paths will be useful, pretty like

``` bash
otc2otf input.ttc -o output-%.ttf
otc2otf input.ttc -o output1.ttf output2.ttf output3.ttf # valid when the quantity of subfonts in input.ttc is 3
```

**Comment by kenlunde** [comment]
I think you meant `otc2otf` not `otf2otc`.

**Comment by be5invis** [comment]
Sorry for typo :(

**Comment by miguelsousa** [comment]
> otc2otf may rewrite files it already written

That was indeed the case before [version 2.0.0](https://github.com/adobe-type-tools/afdko/pull/978). With the new version, any fonts inside the collection that have no `name` table or whose `name` table has no ID 6 will be named according to this format:

    <ttc file name (without the extension)>-font<index>.(otf|ttf)

The test suite includes [two examples](https://github.com/adobe-type-tools/afdko/blob/develop/tests/otc2otf_test.py#L119-L121).
