### ISSUE TITLE
Shebang consistency

### ISSUE THREAD

**Issue by paravoid** [adobe-type-tools/afdko#670]
`python/afdko/autohint.py` and `python/afdko/stemhist.py` have a `#!/bin/env python` shebang, but `/bin/env` doesn't exist in most systems, `/usr/bin/env` does, and is what every other script in afdko is set to. This is a simple fix :)

Moreover, there are 9 scripts in total that have an `[…]env python` shebang. Should this be changed to `#!/usr/bin/env python3` instead?

**Comment by miguelsousa** [comment]
The best might actually be to remove the shebang line from all the Python scripts.
