### ISSUE TITLE
[tx] -dcf fails to print CFF2 global subrs

### ISSUE THREAD

**Issue by blueshade7** [adobe-type-tools/afdko#678]
Global subroutines are not printed by running `tx -dcf <subroutinized cff2 font>`

**Comment by blueshade7** [comment]
Attached a subroutinized subset of AdobeVFPrototype.otf and its "tx -dcf" output as "before.dcf" exhibiting the issue.

[AdobeVFPrototype_subset_gsubrs.zip](https://github.com/adobe-type-tools/afdko/files/2568864/AdobeVFPrototype_subset_gsubrs.zip)

**Comment by cjchapman** [comment]
Fixed by https://github.com/adobe-type-tools/afdko/pull/681
