### ISSUE TITLE
[autohint] Please split the element that goes from X Y to X Y

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#686]
@typemytype reported this problem:

```
.............................................................................................................................................................................
ERROR: OE: Please split the element that goes from 390 -10 to 493 0.
ERROR: OE: Please split the element that goes from 390 -10 to 493 0.
```

This seems to be new, I personally have never seen this output before.
Some files are attached, both UFO and OTF, in which the problem can be reproduced using the latest version available through pip (C program version 1.7. lib version 1.8.1.)

The files are isolated examples, the same output is observed for other glyphs.

[AutohintBug.ufo.zip](https://github.com/adobe-type-tools/afdko/files/2617428/AutohintBug.ufo.zip)

[AutohintBug.otf.zip](https://github.com/adobe-type-tools/afdko/files/2617429/AutohintBug.otf.zip)

The glyph in question looks like this:
![screen shot 2018-11-26 at 22 25 25](https://user-images.githubusercontent.com/2049645/49044335-bad65b00-f1cd-11e8-9434-68c3978bc96d.png)

The command executed is `autohint -nb -q AutohintBug.ufo`

**Comment by miguelsousa** [comment]
Khaled has addressed this issue in https://github.com/adobe-type-tools/psautohint/pull/112 . IIRC the only thing left to do is to integrate the newest version of psautohint into the afdko package.

**Comment by typemytype** [comment]
I was unaware of the duplicated  auto hinters...

is psauthint the advised auto hinter?

**Comment by typemytype** [comment]
if I feed the latest psautohint this otf it provides the same ERROR...

**Comment by miguelsousa** [comment]
> if I feed the latest psautohint this otf it provides the same ERROR...

I don't get any error with psautohint v1.9.0b2

**Comment by typemytype** [comment]
confirmed: psautohint 1.9.0 does not give this error 

thanks

**Comment by miguelsousa** [comment]
I've just issued afdko v2.8.4a0 which includes psautohint v1.9.1
