### ISSUE TITLE
[tx] subroutinizing with -no_futile may make font larger than without

### ISSUE THREAD

**Issue by blueshade7** [adobe-type-tools/afdko#688]
`-no_futile` option does not guarantee that it would make a subroutinized font smaller, but a case is observed where a subroutinized font with the option becomes substantially larger than without, by up to 12%.
This counter-intuitive behavior needs investigation. If necessary, the option should be re-implemented.

**Comment by blueshade7** [comment]
This is the way how -no_futile option currently works:
1. Subroutinize all charstrings & subroutines using pre-selected subroutine candidates. A set of subroutines called by each charstring or subroutine is selected greedily, i.e., to make a local optimality.
2. Count each subroutine usage.
3. If there are any 0- or 1-use subroutines, unselect them.
4. Repeat 1 through 3 until there are no more 0/1-use subroutines.

Due to the greediness at step 1, a global optimality is not guaranteed, actually it isn’t when there are any 0/1-use subroutines.
Unselecting 0-use subroutines and retrying is expected to produce a better result, but not guaranteed.
Even less so about unselecting 1-use subroutines, because a better solution might be instead increasing usage of each 1-use subroutine, which is not trivial to do.

**Comment by miguelsousa** [comment]
Fixed by #704
