### ISSUE TITLE
[makeotf] documentation contains no information about glyphs.com.adobe.type.processedglyphs layer

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#702]
I know about the `glyphs.com.adobe.type.processedglyphs` layer, which is created by `checkoutlinesUFO` and `(ps)autohint`, and which `makeotf` prefers when building a font. However, there is no mention of this layer in the documentation at `makeotf -h`.

Additionally, the tabbing in the documentation is a little hard to read (not sure that’s easy to control):
![screen shot 2018-12-18 at 16 38 17](https://user-images.githubusercontent.com/2049645/50164582-64979c00-02e3-11e9-8c81-9f0496e50425.png)

**Comment by miguelsousa** [comment]
@frankrolf please submit a fix

**Comment by frankrolf** [comment]
Will do!

**Comment by miguelsousa** [comment]
Fixed via #738
