### ISSUE TITLE
[checkoutlinesUFO] glyph file names might not correspond to existing file names …

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#703]
… resulting in overlaps not being removed in the OTF file.

The attached UFO file (c/o @rbmntjs) has a singe AE glyph, drawn with overlaps.
Nevertheless, it does not make it through the FDK workflow, and I have finally found out why:

Consider the following steps:

### ① remove overlap
```
$ checkoutlinesufo -e SerifText-Bold.ufo
AE There is an overlap.Done with font
```
checkoutlinesufo recoginzes the overlap – great!

### ② generate OTF
```
$ makeotf -f SerifText-Bold.ufo/
makeotf [Warning] Could not find default features file at 'None'. Font will be built without any layout features.
makeotfexe [NOTE] Adding glyph .notdef, SID 0.
Built development mode font 'SerifText-Bold.otf'.
```

### ③ convert back to UFO
```
$ tx -ufo -o SerifText-Bold_roundtrip.ufo SerifText-Bold.otf
```

The new UFO still has the overlaps in it, which means they are present in the OTF as well.
By coincidence I found out the reason for this is the glyphname-to-filename writer in `checkoutlinesufo`.

This is the original file tree of the UFO file:
```
SerifText-Bold.ufo:
	fontinfo.plist
	glyphs:
		AE_.glif
		contents.plist
	layercontents.plist
	lib.plist
	metainfo.plist
```

Here is how it looks after running checkoutlinesufo:
```
SerifText-Bold.ufo:
	data:
		com.adobe.type.processedHashMap
	fontinfo.plist
	glyphs:
		AE_.glif
		contents.plist
	glyphs.com.adobe.type.processedglyphs:
		A_E_.glif
		contents.plist
	layercontents.plist
	lib.plist
	metainfo.plist
```

As is obvious, `A_E_.glif` is not equivalent to `AE_.glif`, which is why `makeotf` does not recognize them as equivalent. When I rename the latter to A_E_.glif (and re-wire in contents.plist), everything works as expected.

I suggest for makeotf to compare the glif files through the contents.plist rather than their file names.
An intermediate solution for Robin might be normalizing the UFO file before running checkoutlinesUFO.

[SerifText-Bold.ufo.zip](https://github.com/adobe-type-tools/afdko/files/2691243/SerifText-Bold.ufo.zip)

**Comment by miguelsousa** [comment]
> I suggest for makeotf to compare the glif files through the **contents.plist** rather than their file names.

Agree. Looking into it.

**Comment by miguelsousa** [comment]
The failure to produce a font (via makeotf) without overlaps is caused by tx. I opened #740 specifically to address it.

**Comment by miguelsousa** [comment]
AFAICT checkoutlinesUFO is not doing anything wrong; the GLIF files it writes in **glyphs.com.adobe.type.processedglyphs** have a normalized filename, but that's a good thing, I think.
I'll leave this issue open until #740 is fixed.

**Comment by miguelsousa** [comment]
The bug in tx (#740) is fixed. Also added a makeotf test.
