### ISSUE TITLE
setting vAdv from hAdv if glyphs are substituted in vrt2

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#707]
I have a user wondering why some fullwidth glyphs are exported with vertical half height. It turns out that makeotf is copying the hAdv from the source to the vAdv of the target glyphs in the vrt2 feature. Why is it doing that?

This is the code he used (commasmall is half width):
```
sub comma.full by comma.full.vert; 
sub commasmall by comma.full.vert;
```

**Comment by kenlunde** [comment]
This is by design. The horizontal advance of the source glyphs in the 'vrt2' GSUB feature are applied as the vertical advance of the target glyph. If that behavior is not desired, a 'vmtx' table override needs to be specified.
