### ISSUE TITLE
[ttfcomponentizer] Set maxp table's maxComponentElements value

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#710]
Even though FontTools recalculates most of `maxp` table values, `maxComponentElements` is not one of them and needs to be explicitly set otherwise it ends up as zero.

Related issues:
https://github.com/adobe-fonts/source-sans-pro/issues/154
https://github.com/adobe-fonts/source-serif-pro/issues/44

**Comment by anthrotype** [comment]
maybe fonttools should do that. if you like to work on a PR i'd be happy to review

**Comment by miguelsousa** [comment]
@anthrotype upon looking at the code it seems that all that's needed is a one-line change:
```diff
--- a/Lib/fontTools/ttLib/tables/_m_a_x_p.py
+++ b/Lib/fontTools/ttLib/tables/_m_a_x_p.py
@@ -107,6 +107,7 @@ class table__m_a_x_p(DefaultTable.DefaultTable):
                self.maxContours = maxContours
                self.maxCompositePoints = maxCompositePoints
                self.maxCompositeContours = maxCompositeContours
+               self.maxComponentElements = maxComponentElements
                self.maxComponentDepth = maxComponentDepth
                if allXMinIsLsb:
                        headTable.flags = headTable.flags | 0x2
```
I'll make the PR now.

**Comment by anthrotype** [comment]
ouch! since when has this been broken?

**Comment by anthrotype** [comment]
according to git blame, since day one (Dec 16 1999)
good catch!

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/releases/tag/3.35.1

**Comment by miguelsousa** [comment]
thanks

**Comment by miguelsousa** [comment]
fixed via https://github.com/fonttools/fonttools/pull/1433
