### ISSUE TITLE
https://www.adobe.com/devnet/opentype/afdko.html points to a non-existent github url

### ISSUE THREAD

**Issue by Pomax** [adobe-type-tools/afdko#716]
https://www.adobe.com/devnet/opentype/afdko.html has a "[...] and on `github` for the open source release" link that points to https://github.com/adobe-type-tools/afdko/tree/master/afdko/Technical%20Documentation, which is a 404, rather than pointing to something that exists in the https://github.com/adobe-type-tools/afdko/tree/develop/docs dir.

**Comment by cjchapman** [comment]
I've updated the link. Thanks.
