### ISSUE TITLE
new "official" release due to CFF2?

### ISSUE THREAD

**Issue by Pomax** [adobe-type-tools/afdko#717]
According to https://www.adobe.com/devnet/opentype/afdko/eula.html the most recent version of the FDK is from April 2017, which predates CFF2 (at least, officially), and certainly predates issues around fixes necessary for CFF2 parsing. However, the github `releases` tab shows loads of builds with the most recent being less than 2 weeks ago, so: would it be possible to update https://www.adobe.com/devnet/opentype/afdko/eula.html so that it points people to 2.8 at the very least, or 2.8.4 as that's the latest version?

Or better yet, remove the mention of those old versions and instead give people a link to the releases page here on github, so that they can always download the latest version?

**Comment by readroberts** [comment]
@Pomax This should only be an issue if someone has bookmarked the EULA page, as the legacy AFDKO landing page clearly describes the state of affairs. However, I imagine such people exist, so I updated the EULA/download page to reflect that this downloads are legacy, and point back to the AFDKO landing page for instructions on how to get to the current AFDKO.

**Comment by Pomax** [comment]
I don't have it bookmarked: if I google for "Adobe FDK", I get https://www.adobe.com/devnet/opentype/afdko.html

I visit that page, it sends me to https://www.adobe.com/devnet/opentype/afdko/eula.html to download the FDK.

So this is something _everyone_ will run into, when told to go download the adobe fdk =)

**Comment by readroberts** [comment]
Well, the EULA page  and the AFDKO landing page now both say that the current AFDKO is on Github, and the local AFKDO are legacy versions. I would hope this is sufficient!

**Comment by Pomax** [comment]
Awesome, thanks!
