### ISSUE TITLE
Dash character `-` in postscriptNames in release mode

### ISSUE THREAD

**Issue by typoman** [adobe-type-tools/afdko#720]
By default, if there is a dash character in a glyph name and no 'public.postscriptNames' is found inside a UFO, the makeotf app removes the dash in the final binary in the release mode. But if I try to override this by adding 'public.postscriptNames' key to the ufo that contains the original glyph names with the `-` I get the following error and the glyph order of the UFO gets ignored for the glyphs which have the character.

`[../../../../../../..glyphOrder:xxx] (record skipped)(gnameError)\n' b'makeotfexe [WARNING] syntax error `

Is this a bug or there is no way to have subroutinization on an OTF with glyph names which have a dash in their names. I need to have the dash character because I'm doing some post-processing on the binary fonts and need their original glyph names, then I will change the glyph names to uniXXXX names myself using fontTools.

**Comment by readroberts** [comment]
First, "U+002D '-' Hyphen-minus " is allowed by makeotf in development names. It is not allowed in release names, as it it not a legal PostScript glyph name. This is not going to change - there is more than 30 years of software out there with a notion of a legal PostScript name. However, you can build a font without using release mode but with subroutinization: you omit the '-r' option to not build in release mode, and add the -S option to request subroutinization. You can also use the option "-gf < path to GOADB file>" without the -ga option. This has the effect of applying the Unicode values from the third field of the GOADB records, without renaming or re-ordering the glyphs. 

I am puzzled by your comment that the makeotf app removes the dash from glyph names, as I do not expect this behavior.  Are you sure you see this happening, or is it just that the GOADB file renames the glyphs to final names without a dash ( with either the -r or -ga options)?

**Comment by typoman** [comment]
> I am puzzled by your comment that the makeotf app removes the dash from glyph names, as I do not expect this behavior. Are you sure you see this happening, or is it just that the GOADB file renames the glyphs to final names without a dash ( with either the -r or -ga options)?

Sorry this is probably part what RoboFont does when it uses makeotf to generate the font. When I checked with makeotf command line tool, this doesn't happen. Thanks for the pointers!
