### ISSUE TITLE
Option to parse features using fontTools feaLib

### ISSUE THREAD

**Issue by typoman** [adobe-type-tools/afdko#724]
Since the fontTools feature file interpreter does not encounter overflow for large kerning lookups and possibly some other issues that makeotf encounters, I was wondering if it's possible to add an option to makeotf so the features will be parsed using fontTools while generating the binary?

**Comment by miguelsousa** [comment]
I think that'll be difficult to hook up.
Have you tried building the font without OT features and then using `fontTools.feaLib.builder.addOpenTypeFeatures()` ?

**Comment by typoman** [comment]
I thought about that too. But then I need to post process glyph names to uniXXXX production names using fontTools. It's possible but more clunky. That's why I thought it's better if this would be part of the compiler.

**Comment by miguelsousa** [comment]
**makeotf** is a lot more clunky, trust me...
