### ISSUE TITLE
[makeotfexe] Shorthand syntax for contextual multiple substitutions

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#725]
Currently makeotf does not support syntax like `sub a b' c by d e;`, and it will cause `Unsupported contextual GSUB replacement sequence` error.

Is there any reason for not supporting this syntax other than implementation limitation? In other words, would a PR for supporting this syntax be merged?

**Comment by readroberts** [comment]
I would welcome this. I think the only reason it isn't in the feature file spec is oversight: makeotf added support for multiple substitution about a year ( Jan 2009) after contextual substitution was supported (Mar 2008). Can anyone think of a reason to not support this?

**Comment by khaledhosny** [comment]
I can’t think of any reason, and FontTools’s feaLib already support this (probably no one noticed that it was missing from the spec). I already have a patch that seems to work.
