### ISSUE TITLE
[makeotfexe] Using .notdef glyph in a class causes error

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#726]
Given a feature file containing:
```
table GDEF {
  GlyphClassDef [.notdef], , , ;
} GDEF;
```
Processing it with makeotf causes:
```
makeotf [Warning] Could not find FontMenuNameDB file. Font will be built with menu names derived from PostScript name.
makeotfexe [WARNING] FontMenuNameDB file was not specified or not found. [Foo]
makeotfexe [FATAL] <Foo> aborting because of errors
makeotf [Error] Failed to build output font file 'Foo.otf'.
```

(ignoring the irrelevant warnings), there is no explanation for the cause of error and I had to debug the C code to find the root cause:
https://github.com/adobe-type-tools/afdko/blob/f10db2ebf8e0af3d7c565dafc041aedf3a28d042/c/makeotf/makeotf_lib/source/hotconv/featgram.c#L173-L182

Further more I think using `.notdef` here is valid and several other tools allow generating GDEF tables with `.notdef` assigned a glyph class.

**Comment by readroberts** [comment]
@mousa @cjchapman 
I agree that  .notdef should  be allowed to be part of glyph classes. The change needs to be from testing against gid== 0 to gid == GID_UNDEF in line 178.  However, featgram.c is a file derived from running the ANTLR parse against featgram.g; edits should be made in afdko/c/makeotf/makeotf_lib/build/hotpccts/featgram.g.
