### ISSUE TITLE
[tx] Must match foreground & processed glif files via contents.plist

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#740]
tx is NOT using the `contents.plist` files to find matching GLIF files in **glyphs** and **glyphs.com.adobe.type.processedglyphs**, originating this issue #703 

Running the command `tx -t1 font.ufo` on the attached font should produce an **AE** glyph without overlaps.

[font.ufo.zip](https://github.com/adobe-type-tools/afdko/files/2858202/font.ufo.zip)

**Comment by miguelsousa** [comment]
@cjchapman branch named `fix-bug470` has the test case

**Comment by cjchapman** [comment]
For anyone following this: I renamed the branch to `fix-bug740`.
