### ISSUE TITLE
How can I install afdko on Cygwin?

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-type-tools/afdko#748]
I am using cygwin. Attempting to install afdko using pip faced the following error. I hope to be able to use afdko on Cygwin. Is there anything I can do now?

$ pip install afdko
Collecting afdko
  Downloading https://files.pythonhosted.org/packages/6e/03/8bef8634b242e311f347e5275355b565d912361629202a75abce58c4fd4f/afdko-2.8.5.ta
    100% |████████████████████████████████| 13.2MB 225kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/Ktsuboi/psautohint_build/bin/python3 /home/Ktsuboi/psautohint_build/lib/python3.6/site-packages/pi
  Traceback (most recent call last):
    File "/home/Ktsuboi/psautohint_build/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/Ktsuboi/psautohint_build/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/Ktsuboi/psautohint_build/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_b
      return hook(config_settings)
    File "/tmp/pip-build-env-69yed0rn/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_buil
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-69yed0rn/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-69yed0rn/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 211, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-69yed0rn/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 274, in <module>
      main()
    File "setup.py", line 212, in main
      "afdko: Do not recognize target OS: {}".format(platform_system))
  KeyError: 'afdko: Do not recognize target OS: CYGWIN_NT-10.0'

  ----------------------------------------
Command "/home/Ktsuboi/psautohint_build/bin/python3 /home/Ktsuboi/psautohint_build/lib/python3.6/site-packages/pip/_vendor/pep517/_in_pme6tqbxc/afdko

**Comment by miguelsousa** [comment]
The process is getting caught here https://github.com/adobe-type-tools/afdko/blob/develop/setup.py#L212

I'll make some changes to `setup.py`.

Out of curiosity, what's the result of this Python snippet on your system?

```python
import platform
print(platform.system())
```

**Comment by miguelsousa** [comment]
@dadasutasudadas I've issued a new pre-release build. Try again in 30 minutes using this command:

    pip install -U afdko --pre

**Comment by dadasutasudadas** [comment]
@miguelsousa Thank you! 
I just tried "pip install - U afdko -- pre" Unfortunately the following error appears.

(*fileNameList)[i] = (Byte8 *)memNew((entp->d_namlen + 1) * sizeof(Byte8));
                                                       ^~~~~~~~
                                                       d_name
  make: *** [Makefile:85: Dsys.o] エラー 1
  afdko: Unknown OS: CYGWIN_NT-10.0
  afdko: Error executing build command.

  ----------------------------------------
  Failed building wheel for afdko
  Running setup.py clean for afdko
Failed to build afdko
Could not build wheels for afdko which use PEP 517 and cannot be installed directly

**Comment by cjchapman** [comment]
This is the block where the error is occurring:
https://github.com/adobe-type-tools/afdko/blob/47dc7bc2c9f3a707842c4bd7a22c4fee0cec09dd/c/sfntdiff/source/Dsys.c#L221-L252
The `d_name` part of the error message makes me think it's this line in particular (which is the line *before* the one shown in the error message):
https://github.com/adobe-type-tools/afdko/blob/47dc7bc2c9f3a707842c4bd7a22c4fee0cec09dd/c/sfntdiff/source/Dsys.c#L244

**Comment by miguelsousa** [comment]
@dadasutasudadas I'll look into this next week. Need to install Cygwin first to check which afdko's C tools can be compiled on that platform, if any.

**Comment by dadasutasudadas** [comment]
@miguelsousa Thank you. I tried doing things that I can do in my environment so I will report it.
The C tool which could not be built seems to be sfntdiff only. Other detype1.exe, makeotfexe.exe, mergefonts.exe, rotatefont.exe, sfntedit.exe, spot.exe, tx.exe, type1.exe successfully compiled.
It seems to be related to "d_reclen" used in Dsys.c can not be used in Cygwin.

**Comment by miguelsousa** [comment]
The error that happens when trying to compile **sfntdiff** is this:

```
../../../../source/Dsys.c: In function ‘sysReadInputDir’:
../../../../source/Dsys.c:245:53: error: ‘struct dirent’ has no member named ‘d_namlen’; did you mean ‘d_name’?
         (*fileNameList)[i] = (Byte8 *)memNew((entp->d_namlen + 1) * sizeof(Byte8));
                                                     ^~~~~~~~
                                                     d_name
```

Following the suggestion of renaming `d_namlen` to `d_name` leads to a different error.

**Comment by cjchapman** [comment]
@miguelsousa A work-around for this problem is described in this issue: https://github.com/rakshasa/rtorrent/issues/163

**Comment by miguelsousa** [comment]
@dadasutasudadas I've pushed a fix for the sfntdiff problem and issued a new pre-release build.
Please give it another try using:

    pip install -U afdko --pre

**Comment by dadasutasudadas** [comment]
@miguelsousa Installation was completed successfully. I'm really happy. Thank you so much!

**Comment by miguelsousa** [comment]
Good to know. Thanks for your report.
