### ISSUE TITLE
[makeotf] Duplicated warning for empty fontinfo fields

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#751]
When I just run `makeotf` on a very simple (attached) UFO which does not contain any copyright or trademark info, I get the following warning:
```
tx: --- font.ufo
tx: (ufr) Warning: Encountered empty <string> for fontinfo key copyright. Skipping
tx: (ufr) Warning: Encountered empty <string> for fontinfo key trademark. Skipping
tx: --- font.ufo
tx: (ufr) Warning: Encountered empty <string> for fontinfo key copyright. Skipping
tx: (ufr) Warning: Encountered empty <string> for fontinfo key trademark. Skipping
Built development mode font 'Exercise1-Regular.otf'.
```
I think it’s good to have the warning, however it doesn’t need to be duplicated.
[font.ufo.zip](https://github.com/adobe-type-tools/afdko/files/2923705/font.ufo.zip)

**Comment by miguelsousa** [comment]
The second set might be something that fdkutils is doing, whereas the first set is tx printing straight to stderr.

Try running a simple tx command to see how many sets of messages you get.

**Comment by frankrolf** [comment]
A single set only.
