### ISSUE TITLE
buildmasterotfs & buildcff2vf – why two tools?

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#752]
This is more of a question, and I expect there might be a reason I’m just not aware of:
Why are `buildmasterotfs` and `buildcff2vf` split into separate tools? They take the same input designspace file, which means they could theoretically be merged into a single command.

**Comment by miguelsousa** [comment]
It's the result of how the variable font-making workflow was assembled, and there hasn't been a strong reason to overhaul it. Some of the code currently in `buildcff2vf` is in the process of being moved to FontTools, but there are no plans to merge `buildmasterotfs` and `buildcff2vf` at the moment.

Having the workflow split in two steps provides at least a couple advantages I know of (and benefited from):
* makes it possible to post-process the OTFs (e.g. subset them) before the variable font is put together; this means one can use the same source UFOs to produce multiple VFs, for example.
* the step performed by `buildmasterotfs` can take a long time if the design space contains a lot of masters; being able to skip that step when you're trying to put together the source files for a VF project, speeds things up quite a bit.
