### ISSUE TITLE
[makeinstancesufo] minor problems

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#753]
`makeinstancesufo` has a few problems when generating instances:

★ instances’ `lib['public.glyphOrder']` is scrambled
★ instances lose all groups not related to kerning

In addition to that, I noticed that it is no longer possible to generate to the current path without `./` prefix:

this works:
`<instance familyname="Test" filename="./Test-Result.ufo" stylename="Result">`
this doesn’t work (but used to):
`<instance familyname="Test" filename="Test-Result.ufo" stylename="Result">`

**Comment by frankrolf** [comment]
Test scenario attached.
The command run is `makeinstancesufo -acnd Test.designspace`
[makeinstancesufo test.zip](https://github.com/adobe-type-tools/afdko/files/2926230/makeinstancesufo.test.zip)

**Comment by miguelsousa** [comment]
I'll investigate. My guess is that these are caused by **ufoProcessor**.

**Comment by miguelsousa** [comment]
Fix for the `filename` problem: https://github.com/LettError/ufoProcessor/pull/19

**Comment by miguelsousa** [comment]
The **groups** problem depends on this patch: https://github.com/LettError/ufoProcessor/pull/20
But you also need to add `<groups copy="1"/>` to the default master in the designspace file.

The `lib['public.glyphOrder']` problem will go away once you add `<lib copy="1"/>` to the default master.
