### ISSUE TITLE
[makeinstancesufo] x- & y-values flipped in anisotropic interpolation

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#756]
A designspace instance with anisotropic interpolation coordinates yields different results in Superpolator and `makeinstancesufo`. It seems the x- and y-values are flipped in the latter.

```
        <instance familyname="Exercise 2" filename="./Exercise2-x1000y0.ufo" postscriptfontname="Exercise2-x1000y0" stylename="x1000 y0">
            <location>
                <dimension name="weight" xvalue="1000" yvalue="0" />
            </location>
            <kerning />
            <info />
        </instance>

```

Superpolator preview:
<img width="1112" alt="screen shot 2019-03-05 at 14 10 01" src="https://user-images.githubusercontent.com/2049645/53807975-573c9600-3f51-11e9-87d0-8ec08d5be1fb.png">

makeinstancesufo result:
<img width="1294" alt="screen shot 2019-03-05 at 14 14 57" src="https://user-images.githubusercontent.com/2049645/53807980-5c014a00-3f51-11e9-9a5f-30e78012fe7e.png">

**Comment by miguelsousa** [comment]
I think it's an [**ufoProcessor** bug](https://github.com/LettError/ufoProcessor/pull/18)
