### ISSUE TITLE
[makeinstancesufo] Does not report compatibility errors

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#757]
I’m not sure this should be the purpose of this tool, but it would be nice to warn if glyphs are incompatible (and therefore result in a zero-width glyph).

**Comment by miguelsousa** [comment]
> I’m not sure this should be the purpose of this tool

It shouldn't. There are specific tools for that, like [Prepolator](http://tools.typesupply.com/) and [cu2qu.ufo.fonts_to_quadratic](https://github.com/googlei18n/cu2qu).
