### ISSUE TITLE
[makeotf] GOADB is losing unicode when glyph name contains -+~*!^:

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/afdko#766]
Unable to add unicode values with a GOADB for glyph names containing `-+~*!^:`, those character are supported since 2.5.64958 (released 2015-11-22)... 

with release mode `-r` on this is the error/warning from makeotf (also confusing as this should not be a warning or not be an error)  

`makeotfexe [WARNING] syntax error [test.fdk/glyphOrder:4] (record skipped)(gnameError)`

attached the test ufo contains a minimalistic character set containing glyphs with exotic naming.

[exoticCharBug.zip](https://github.com/adobe-type-tools/afdko/files/2951262/exoticCharBug.zip)

the GOADB looks like:

```glyphOrderAliasDB
a a uni0061
a.alt a.alt uni0062
a_alt a_alt uni0063
a-alt a-alt uni0064
a+alt a+alt uni0065
a:alt a:alt uni0066
a~alt a~alt uni0067
a^alt a^alt uni0068
a!alt a!alt uni0069
```

Im using the latest pipped FDK. 

thanks!

**Comment by miguelsousa** [comment]
Those characters are NOT supported in the names of the final glyphs. You can use them in the 2nd-column names (i.e. design names) but not in the first (i.e. final names).

https://github.com/adobe-type-tools/afdko/issues/720#issuecomment-459016875

**Comment by typemytype** [comment]
is this documented somewhere?

see https://github.com/adobe-type-tools/afdko/issues/682

**Comment by miguelsousa** [comment]
I'm hoping it will be once @readroberts fixes that bug.

**Comment by typemytype** [comment]
I dont think it a good plan to throw away existing unicode values (cmap table) on `-r` release mode.

**Comment by miguelsousa** [comment]
I'm confused. Are you suggesting that makeotf should just fail because of these entries in the GOADB

	a-alt a-alt uni0064
	a+alt a+alt uni0065
	a:alt a:alt uni0066
	a~alt a~alt uni0067
	a^alt a^alt uni0068
	a!alt a!alt uni0069

rather than skipping them?
