### ISSUE TITLE
What's the exact definition of bounding boxes of CFF glyphs?

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#768]
Box covers all **control points**, or **all curves**?
(TTF follows the first definition.)

**Comment by readroberts** [comment]
I can't actually find this documented anywhere. The Type 1 spec says only that the BBOX is set 'from the outlines'.  However, the afdko tools set the bbox using the extrema of all the curve segments, calculated from the horizontal and vertical tangents to the curve, not just of the control points.

**Comment by be5invis** [comment]
Also, CFF(2) supports fraction coordinates, so how should we round the “exact” bounding box into the bounds usable for other font parts (like hmtx and head)?


________________________________
发件人: Read Roberts <notifications@github.com>
发送时间: 星期四, 三月 14, 2019 01:56
收件人: adobe-type-tools/afdko
抄送: Belleve Invis; Author
主题: Re: [adobe-type-tools/afdko] What's the exact definition of bounding boxes of CFF glyphs? (#768)


I can't actually find this documented anywhere. The Type 1 spec says only that the BBOX is set 'from the outlines'. However, the afdko tools set the bbox using the extrema of all the curve segments, calculated from the horizontal and vertical tangents to the curve, not just of the control points.

―

**Comment by anthrotype** [comment]
FontTools takes the curve extrema’s bounds then rounds to int using floor and ceil
https://github.com/fonttools/fonttools/pull/970/files
