### ISSUE TITLE
what's the maxiumum allowed coordinate value for Type 2 charstrings

### ISSUE THREAD

**Issue by anthrotype** [adobe-type-tools/afdko#771]
While converting a bunch of SVG paths to a b/w icon font with CFF table, I stumbled by chance on a glyph which had (probably defective) huge coordinate values. That triggered a `struct.error` in fonttools while compiling the `head` table's font-wide bounding box, because the value exceeded the limits of signed short integer (int16) that the head table allows for the font bbox.
Compiling the CFF table itself didn't trigger an error, just a warning that leads to this lines in fonttools, where integers that exceeds those limits are upgraded to four-bytes Fixed numbers
https://github.com/fonttools/fonttools/blob/1fd11a3a0a63c8d11c1b6c1ddea5279530cd3814/Lib/fontTools/misc/psCharStrings.py#L190-L204

Now my question is, if a Type 2 charstring only has integer coordinates (not fractional ones), what are the maximum and minimum allowed values?

I suppose they should not exceed the size of the OpenType head table's font bbox? (int16)

I could not find a clear reference to this specific point in either the CFF spec nor the Type 2 spec.

Thanks

**Comment by anthrotype** [comment]
well, I suppose the paragraph "3.2 Charstring Number Encoding" ([page 12 and 13](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5177.Type2.pdf)) of the Type 2 Charstring format specification should be enough to claim that `-32768 <= x <= 32767` are the min/max limits for any number in a Type 2 charstring 

The CFF 1.0 spec "Operand encoding" table (page 10) in turn points to the Type2 spec.

**Comment by readroberts** [comment]
@behdad The practical limits are implementation. The currentAdobe core rasterizers fail if the value is more than +- 10,000. We tried to build a version of BickhamScript at a UPM of greater than 3000, and failed because of some of the largest swashes hit this limit. Behdad, do you what the limits are in Harfbuzz?

**Comment by behdad** [comment]
HarfBuzz doesn't have limits.  FreeType might.  I don't know off the top of my head.
