### ISSUE TITLE
[makeotf] fails with misleading ASCII byte (?)

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#779]
Another “obscure problem found during FDK workshop”:

This behavior is observed when the OS/2 vendor ID in a features file is entered using curly quotes:
```
table OS/2 {
      Vendor “TEST”;

} OS/2;
```
```
makeotf [Note] Using features file at './features.fea'.
Traceback (most recent call last):
  File "/usr/local/bin/makeotf", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/afdko/makeotf.py", line 2719, in main
    runMakeOTF(makeOTFParams)
  File "/usr/local/lib/python3.7/site-packages/afdko/makeotf.py", line 2595, in runMakeOTF
    fdkutils.runShellCmdLogging(commandString)
  File "/usr/local/lib/python3.7/site-packages/afdko/fdkutils.py", line 122, in runShellCmdLogging
    print(tostr(output))
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/py23.py", line 131, in tounicode
    return s.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 65: ordinal not in range(128)
```

`byte 0xe2` makes me look for U+00E2, which is `â`, and has nothing to do with the issue.

The same `byte 0xe2` is output, no matter if the wrongly-entered vendor ID is `“TEST”`, `“TEST"`, or `"TEST”` – so perhaps makeotf is reporting a code point that already went through some kind of charset conversion?

I wonder if it would be possible to read an external file beforehand, and notify the user 
“Hey, your file’s not ASCII”. An analysis like this would perhaps also allow to filter which exact characters are the problematic ones.

**Comment by josh-hadley** [comment]
After recent updates, I now get the following, using a .fea file using OS/2 Vendor as you described:
```
$ makeotf -f font.otf -o out.otf -ff bad_ascii.fea
makeotf [Warning] Could not find FontMenuNameDB file. Font will be built with menu names derived from PostScript name.
makeotfexe [WARNING] FontMenuNameDB file was not specified or not found. [SourceSerif-Test]
makeotfexe [FATAL] <SourceSerif-Test> invalid token (text was "?") [bad_ascii.fea 7]
Command '['makeotfexe', '-f', '/var/folders/36/_6l2ld7165d5rdrlshlnc6v80000gn/T/tmpr_ziurb0', '-o', 'out.otf', '-ff', 'bad_ascii.fea', '-shw']' returned non-zero exit status 1.
makeotf [Error] Failed to build output font file 'out.otf'.
```
i.e. it still fails, but in makeotfexe and an indication of the exact line number of failure (better, IMHO, than the vague UnicodeDecodeError from Python)

**Comment by frankrolf** [comment]
Great! Thank you! 😊
