### ISSUE TITLE
tx produced incorrectly-positioned pdf on several specific characters (perhaps with nested TTF references), like 'ᾬ'

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#78]
I am using `tx` to generate a PDF for [Iosevka r0.1.16-p1](https://github.com/be5invis/Iosevka/releases/tag/v0.1.16-p1):

```
tx -pdf iosevka-regular.ttf iosevka-regular.pdf
```
However I found some of the characters are incorrect, for example, /uni1FAC and /uni1FD3. I think it is related to nested TTF references.

PDF link: http://pan.baidu.com/s/1kTER5jD

tx version:
```
be5in ω Z:\iosevka\releases λ tx -v
Versions:
    tx        1.0.61
    absfont   1.0.47
    ctutil    2.0.1
    dynarr    2.0.3
    sfntread  1.0.5
    t2cstr    1.0.16
    cffread   2.0.46
    cffwrite  1.0.40
    sfntwrite 1.0.6
    pstoken   2.0.9
    t1cstr    1.0.15
    t1read    1.0.40
    ttread    1.0.20
    cfembed   2.0.25
    pdfwrite  1.0.5
    svread    1.0.6
    t1write   1.0.31
    svwrite   1.1.9
    uforead   1.0.8
    ufwrite   1.0.1
```

**Comment by readroberts** [comment]
This is a simple bug in ttread.c, present since it was first written. Code assumes that compound glyphs are not nested. See commit this morning.
