### ISSUE TITLE
need an example for rsub/reversesub

### ISSUE THREAD

**Issue by MayuraVerma** [adobe-type-tools/afdko#784]
Please provide an example for rsub/reversesub

https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5h-gsub-lookuptype-8-reverse-chaining-single-substitution

**Comment by readroberts** [comment]
I see the example: "reversesub [a e n] d' by d.alt;"   You may be confused by the fact  that the text does not explicitly identify this is as an example.

**Comment by MayuraVerma** [comment]
Please provide a simple explanation as to what happens in real world scenario.
similar to the below example.
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#example-1-2

**Comment by miguelsousa** [comment]
See [LookupType 8: Reverse Chaining Contextual Single Substitution Subtable](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-8-reverse-chaining-contextual-single-substitution-subtable)
