### ISSUE TITLE
Need a example  

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#788]
The description is "uses theSingleSubstFormat2 subtablefor lists to substitute punctuation glyphs in Japanesetext that is written vertically. Horizontally oriented parentheses and square brackets (theinput glyphs) arereplaced with vertically oriented parentheses and square brackets (the output glyphs). 
The Coveragetable, Format 1, identifies each input glyph index.The number of input glyph indices listed in the Coveragetable matches the number of output glyph indices listed in thesubtable. For correct substitution, the order of the glyph indices in the Coveragetable(input glyphs) must match the order in theSubstitutearray (output glyphs)"。

https://docs.microsoft.com/zh-cn/typography/opentype/spec/gsub#SS

**Comment by mhjy** [comment]
this is my lookup:
@biaodian_3000=[uni203C uni2047 uni2048 uni2049 uni3001 uni3002 uni3008 uni3009 
		uni300A uni300B  uni300C  uni300D  uni300E  uni300F  uni3010  uni3011 
		uni3014 uni3015 uni3016 uni3017 uni3018 uni3019 uni301A uni301B uni301D uni301E uni301F ];
@biaodian_3000_vert=[uni203C.vert uni2047.vert uni2048.vert uni2049.vert uni3001.vert uni3002.vert uni3008.vert uni3009.vert
		 uni300A.vert uni300B.vert uni300C.vert  uni300D.vert  uni300E.vert  uni300F.vert  uni3010.vert  uni3011.vert 
		uni3014.vert uni3015.vert uni3016.vert uni3017.vert uni3018.vert uni3019.vert uni301A.vert uni301B.vert uni301D.vert uni301E.vert uni301F.vert  ];
feature vert  
{	
	lookup test
	{
		sub [uni3008 uni3009 uni300A] by [uni3008.vert uni3009.vert uni300A.vert];
	}test;
	lookup test1
	{
		sub @biaodian_3000 by @biaodian_3000_vert;
	}test1;
		
} vert;

use the makeotf to build a font. than use "ttx -t GSUB fontname.ttf " to create a ttx file. the content is:
      <Lookup index="1">
        <LookupType value="1"/>
        <LookupFlag value="8"/>
        
        <SingleSubst index="0" Format="1">
          <Substitution in="uni3008" out="uni3008.vert"/>
          <Substitution in="uni3009" out="uni3009.vert"/>
          <Substitution in="uni300A" out="uni300A.vert"/>
        </SingleSubst>
      </Lookup>
      <Lookup index="2">
        <LookupType value="1"/>
        <LookupFlag value="8"/>
        
        <SingleSubst index="0" Format="2">
          <Substitution in="uni203C" out="uni203C.vert"/>
          <Substitution in="uni2047" out="uni2047.vert"/>
          <Substitution in="uni2048" out="uni2048.vert"/>
          <Substitution in="uni2049" out="uni2049.vert"/>
          <Substitution in="uni3001" out="uni3001.vert"/>
          <Substitution in="uni3002" out="uni3002.vert"/>
          <Substitution in="uni3008" out="uni3008.vert"/>
          <Substitution in="uni3009" out="uni3009.vert"/>
          <Substitution in="uni300A" out="uni300A.vert"/>
          <Substitution in="uni300B" out="uni300B.vert"/>
          <Substitution in="uni300C" out="uni300C.vert"/>
          <Substitution in="uni300D" out="uni300D.vert"/>
          <Substitution in="uni300E" out="uni300E.vert"/>
          <Substitution in="uni300F" out="uni300F.vert"/>
          <Substitution in="uni3010" out="uni3010.vert"/>
          <Substitution in="uni3011" out="uni3011.vert"/>
          <Substitution in="uni3014" out="uni3014.vert"/>
          <Substitution in="uni3015" out="uni3015.vert"/>
          <Substitution in="uni3016" out="uni3016.vert"/>
          <Substitution in="uni3017" out="uni3017.vert"/>
          <Substitution in="uni3018" out="uni3018.vert"/>
          <Substitution in="uni3019" out="uni3019.vert"/>
          <Substitution in="uni301A" out="uni301A.vert"/>
          <Substitution in="uni301B" out="uni301B.vert"/>
          <Substitution in="uni301D" out="uni301D.vert"/>
          <Substitution in="uni301E" out="uni301E.vert"/>
          <Substitution in="uni301F" out="uni301F.vert"/>
        </SingleSubst>
      </Lookup>

why???

**Comment by mhjy** [comment]
The single substitution have format 1 and format 2. The coverage table also have format 1 and format 2.
how to write the next lookup:
(1) single substitution format 1 + coverage format 1
(2) single substitution format 2 + coverage format 1
(3) single substitution format 1 + coverage format 2
(4) single substitution format 2 + coverage format 2 

help me, please! I need example.

**Comment by kenlunde** [comment]
1) Why do you have the three substitutions of the "test" lookup in the "test1" lookup?

2) As to why they use a different format, I suspect it is because the glyphs in the "test" lookup are completely contiguous, whereas the ones in the "test1" lookup are not.

**Comment by mhjy** [comment]
How to use "format 1 of Coverage table" in "format 2 of substitution subs"?

**Comment by miguelsousa** [comment]
The feature file syntax does not provide a way of specifying the format of the coverage table.
