### ISSUE TITLE
what error it's？（about hmtx）

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#789]
syntax error at "hmtx" missing { BASE GDEF head hhea name OS/2 vhea vmtx } 
-----------------------------------------------------------------------------------------
this is table hmtx:
table hmtx {
	AdvanceX uni3016 1416;			
}hmtx;

**Comment by miguelsousa** [comment]
You cannot override the `hmtx` table. See https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9
