### ISSUE TITLE
[makeotf] AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by BoldMonday** [adobe-type-tools/afdko#796]
I installed the latest version (2.8.9) of the afdko on a new machine running MacOS Mojave using `pip install --user afdko`.

When trying to run `makeotf` I get the following error:
```
Traceback (most recent call last):
  File "/Users/paulus/Library/Python/2.7/bin/makeotf", line 6, in <module>
    from afdko.makeotf import main
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/afdko/makeotf.py", line 14, in <module>
    from afdko import convertfonttocid, fdkutils, ufotools
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/afdko/ufotools.py", line 17, in <module>
    from fontTools.ufoLib import UFOReader
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fontTools/ufoLib/__init__.py", line 9, in <module>
    import fs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/__init__.py", line 8, in <module>
    from .opener import open_fs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/opener/__init__.py", line 14, in <module>
    from . import appfs, ftpfs, memoryfs, osfs, tarfs, tempfs, zipfs
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/opener/ftpfs.py", line 15, in <module>
    from ..errors import FSError, CreateFailed
  File "/Users/paulus/Library/Python/2.7/lib/python/site-packages/fs/errors.py", line 71, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by frankrolf** [comment]
While everything still should be Python2-compatible (and this seems to be a valid bug), Python 3 is the safer way forward.
Try installing the same in Python3 using `pip3`.

**Comment by miguelsousa** [comment]
The problem seems to be coming from `fontTools.ufoLib.UFOReader`. Not sure if it's worth fixing since the end for py27 support in FontTools and AFDKO is near.

**Comment by BoldMonday** [comment]
Thanks for checking Frank and Miguel.

The problem is that I still need a version of the afdko to work in a Python 2 environment because it will be integrated into other things. :/

Will report to the FontTools team...

**Comment by BoldMonday** [comment]
After some hints from the fontTools guys it became clear that ufoLib (and hence the afdko) requires the most recent version of the six library. The problem is that six is part of the Apple supplied Python 2.7.10 with MacOS Mojave. And therefore cannot be updated globally.

Only solution is to use a Python 2 virtual environment. I might be good to add a note about this to the afdko installation guide.

**Comment by miguelsousa** [comment]
The minimum requirement for the version of `six` would have to be imposed by FontTools.
Our README already recommends using a virtual environment.

**Comment by BoldMonday** [comment]
I know the README recommends virtual environment.

What I failed to express clearly is that it might be handy to add a note that a global install on MacOS is not very straightforward.

**Comment by anthrotype** [comment]
fonttools doesn't import `six` directly so if anything it should be pyfilesystem2 (`fs` module) that should require a minimum compatible version in their setup.py's `install_requires`

**Comment by BoldMonday** [comment]
You are correct @anthrotype. Sorry for mistakingly putting the blame on fonttools (after blaming the afdko).

**Comment by anthrotype** [comment]
no blame taken :)
