### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [adobe-type-tools/afdko#8]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [abfAFMBegFont](https://github.com/adobe-type-tools/afdko/blob/2bf85cf44a64148353b24db17e0cc41ede5493b1/FDK/Tools/Programs/public/lib/source/absfont/absfont_afm.c#L26)
- [fread](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html) ⇒ [getFileData](https://github.com/adobe-type-tools/afdko/blob/3f4eeec1c1623f427bfeb9b53e82e300d7f8a67e/FDK/Tools/Programs/autohint/source/main.c#L125)
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html) ⇒ [tmp_write](https://github.com/adobe-type-tools/afdko/blob/3f4eeec1c1623f427bfeb9b53e82e300d7f8a67e/FDK/Tools/Programs/mergeFonts/source/mergeFonts.c#L817)

**Comment by readroberts** [comment]
Closing this as being too broad to easily resolve. Our team does plan to apply static analysis tools to help us resolve all compile errors and improve code style, starting with the categories of issues that are most likely to cause us problems.
