### ISSUE TITLE
How to solve the error "makeotf [Error] Failed to build output font file 'c:\users\......."?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#801]
The message is " makeotf [Error] Failed to build output font file 'c:\users\mhjy\appdata\loc
al\temp\tmpgapctq'. ". Why? How to solve the error?

**Comment by frankrolf** [comment]
This question needs more context – the failure can have multiple causes (compilation error, write-protected destination, etc.).
Usually, the messages above give you a clue what’s wrong.

**Comment by mhjy** [comment]
I add the following code: print("-----the %s file size is %d --------" %(tempOutPath,os.path.getsize(tempOutPath)));

the message is : -----the c:\users\mhjy\appdata\local\temp\tmps6815m file size is 0 --------

Why? the tempfile is not build??
