### ISSUE TITLE
Syntax for MATH table

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#802]
I have a font where I need to build `MATH` table using FontTools, and I’m thinking it would be better to do this using feature files instead of an ad-hoc script so that others can easily do the same. There are two options:
1. Use `anon` blocks and have a feaLib parse that without affecting any other implementation, or
2. Document a `table MATH` syntax in the feature files specification and implement it in feaLib.

So my question is, would it be acceptable to send a pull request for 2) without implementing the table support in makeotf (since I can’t afford doing the makeotf implementation)?

**Comment by miguelsousa** [comment]
> would it be acceptable to send a pull request for 2) without implementing the table support in makeotf

Yes

**Comment by miguelsousa** [comment]
The spec already contains notes about things not being implemented in **makeotf**. And the support in `feaLib` is currently not the same as makeotf (e.g. `vmtx` table is not supported by the former. I started the work on that but had to move to other priorities. If anyone wants what I've done so far, let me know)

**Comment by khaledhosny** [comment]
I worked a bit on this and had like 60% of the syntax and FontTools code, then I lost it all with my laptop. I don’t think I’ll be working on it again any time soon.

**Comment by miguelsousa** [comment]
😞Sorry to hear that
