### ISSUE TITLE
Value record format A: are angle brackets optional ?

### ISSUE THREAD

**Issue by bobh0303** [adobe-type-tools/afdko#804]
Section [2.3.iv](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#2eiv-value-record) starts out by saying:

> A \<valuerecord\> is used in some positioning rules [§6].
>
>It must be enclosed by angle brackets, _except for format A, in which the angle brackets are optional._ 

(emphasis mine)

but then the following examples for Value Record format A suggest that brackets are not allowed:

` <metric>  # Angle brackets around value are not allowed.`
and
` -3  # without <>`

Which is correct?

**Comment by frankrolf** [comment]
You are witnessing an angle-brackets clash here. `<metric>` is just the variable name here, which stands for a numerical value. For clarification, see the following section, where you’ll find `<<metric><metric> <metric> <metric>>`, four numerical values. The fact that the angle brackets are used to determine variable names is pure coincidence.

**Comment by bobh0303** [comment]
Thanks for the quick response. And yes, I understood the semantic clash.

However, the two sentences at the start of the section are about _value records_, not the metrics within them, and it says a value record _must be enclosed by angle brackets, except for format A, in which the angle brackets are optional._  

If they are really optional for format A, then the example comments in the format A description could be modified to indicate that the brackets are allowed rather than prohibited (and also there may be a bug in fonttools because it balks at brackets for format A).

If they are not optional -- and in fact must not be present -- then the initial text could be better worded:

> It must be enclosed by angle brackets except in the case of format A.

or maybe:

> Except in the case of format A, value records must be enclosed in angle brackets.

**Comment by frankrolf** [comment]
They _may_ be present even in format A, in the following notation:
![2019-06-05_001000](https://user-images.githubusercontent.com/2049645/58929716-481edd00-8726-11e9-8f60-bf40027c930d.png)

**Comment by bobh0303** [comment]
The format A value record in your example is not using brackets. You are saying it is permitted to have written:
```
feature kern { # Kerning
    pos A V <-130>;
} kern;
```
Is that correct?

Neither `makeotf` nor fonttools accept the above code.

**Comment by frankrolf** [comment]
The code would have to be either
```
feature kern {
    pos A V <0 0 -130 0>;
} kern;
```
or 

```
feature kern {
    pos A V -130;
} kern;
```
(the bottom is a shorthand for the above scenario)

If angle brackets are used, a valuerecord consisting of 4 numbers is required. For right-to-left kerning, the valuerecord notation is obligatory:

```
feature kern {
    pos alefMadda ain <-190 0 -190 0>;
} kern;
```

**Comment by bobh0303** [comment]
Exactly. You are confirming that:

- value Record format B, i.e., the 4-value value record, must be written with brackets
- value Record format A, i.e., the single value record, must be written _without_ brackets.

Thus in value record format A the brackets are _prohibited_, not _optional_ (as the spec currently reads).

This is an error in the specification that has mislead more than one person. Could we correct it, please?

**Comment by miguelsousa** [comment]
> Could we correct it, please?

@bobh0303 absolutely. Please send in a PR. Thanks.

**Comment by bobh0303** [comment]
To which branch ... master or develop?

**Comment by miguelsousa** [comment]
develop
