### ISSUE TITLE
[buildcff2vf] Bug in supporting less usual GPOS/GSUB features

### ISSUE THREAD

**Issue by readroberts** [adobe-type-tools/afdko#817]
When building a variable font while using subsetting, fonttools removes unknown features from the final font. 'known features' is defined by a list of default features in fonttools/Lib/fontTools/subset/__init__.py. 'palt', used in the Adobe CJK fonts, is not on the list.

**Comment by anthrotype** [comment]
Those default subset features are those required for shaping. We can add palt to that list of you think it is required. Or you can call the subsetter with the right option.

**Comment by readroberts** [comment]
@anthrotype @behdad . I have fixed he issue by calling the subsetter with the right option. However, maybe some more features should be added to the default list. I see that none of the (all optional) features used by CJK fonts to control glyph width -  'fwid', 'halt', 'hwid', 'palt', 'qwid' and 'twid') are on the default list, which is defined as the set of features used by HarfBuzz for shaping, but 'vpal' and 'vrt2' are included. Is the subsetter default list is meant to include only features which are on by default? If so, then the current list makes sense.

**Comment by behdad** [comment]
> Is the subsetter default list is meant to include only features which are on by default?

Yes.

**Comment by miguelsousa** [comment]
Reopening because #825 is yet to be merged
