### ISSUE TITLE
[tx] SVG format and upside down?

### ISSUE THREAD

**Issue by anyong** [adobe-type-tools/afdko#818]
I am trying to export an SVG of a glyph from Source Han Sans. For example, glyph `0x4e01 丁`.

I use the command:

`tx -svg -g 2761 cidfont.ps.TW out.svg`

SVG output is:

```svg
<font horiz-adv-x="1000">
<!-- Copyright 2014, 2015, 2018 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'. Source is a trademark of Adobe in the United States and/or other countries. -->
<font-face font-family="SourceHanSansTW-Regular" units-per-em="1000" underline-position="-150" underline-thickness="50"/>
<glyph unicode="&#xE000;" horiz-adv-x="1000" d="M936,745l-872,0l0,-76l423,0l0,-624C487,22 478,15 454,14C427,13 337,13 244,16C259,-6 274,-44 280,-68C395,-68 469,-67 512,-53C554,-40 571,-15 571,44l0,625l365,0z"/>
</font>
```

I don't know what software to use to open this SVG file as it is not w3 standard spec. I would like to use it in a python script using a python graphics library to perform some alterations, and the current format does not work. Additionally, if I copy the `d="..."` path data into a standard SVG, the character appears flipped about the X axis.

![image](https://user-images.githubusercontent.com/6260469/59827987-9100a380-936c-11e9-9298-edc22ea25556.png)

Note the `viewBox` size as well (1000 x 850) which I found was the only size able to display the character correctly, and not sure why that is either.

I have looked at the `tx` code briefly, but it's beyond me. Could anyone explain how to get a standard SVG path to work with from a font file? Or alternatively, which format I might extract that would allow me to programmatically alter the shapes (which will then be re-combined into a new font).

Thank you!

(By the way, if anyone knows a better way to do this - a different file format, or another tool to do the modifications - that would be useful as well. By modifications I mean adding ruby text to the glyphs, and then recompiling the font with the ruby text baked in.)

**Comment by miguelsousa** [comment]
The SVG that **tx** outputs is an [SVG font](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts).

Use **fonts2svg.py** from the [opentype-svg](https://github.com/adobe-type-tools/opentype-svg) repo instead if what you want is the glyph as an SVG document.

Here's an example command,

    python3 fonts2svg.py -c ff0000 -g cid02158 SourceHanSansTW-Regular.otf

which outputs the following SVG:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -1000 1000 1000">
	<path fill="#ff0000" d="M966 -379C966 -637 757 -846 500 -846C243 -846 34 -637 34 -380C34 -123 243 86 500 86C757 86 966 -123 966 -379ZM499 -814C740 -814 934 -620 934 -380C934 -140 740 54 500 54C260 54 66 -140 66 -380C66 -620 260 -814 499 -814ZM380 -627L357 -568C445 -556 606 -514 678 -486L702 -546C628 -573 460 -616 380 -627ZM332 -452L310 -394C400 -380 550 -340 628 -309L652 -370C571 -400 424 -436 332 -452ZM308 -258L285 -199C388 -180 571 -134 656 -95L683 -153C597 -190 412 -239 308 -258Z"/>
</svg>
```

**Comment by miguelsousa** [comment]
As for modifying the glyphs in the font, that requires other tools. If you're comfortable with Python and plan to use an SVG editor to modify the paths, you can do it by writing a script that uses [fontTools](https://github.com/fonttools/fonttools).

**Comment by anyong** [comment]
@miguelsousa thank you for the information! I think I can find some python tools to use for modifying the SVGs, essentially I will just be adding additional ruby text into each glyph (so that character & reading are combined in a single glyph). If you have any recommendations for a tool that would make that easy, that'd be great.

I'm not sure what your suggestion regarding fontTools is, as I understand that is for converting .ttf files between binary and a human-readable XML format. In my case, since Source Han Sans is open source, I can start directly from the cidfont.ps files, unless I'm missing something?

In any case I believe the issue in the original post was solved already, so this issue can be closed!

**Comment by cjchapman** [comment]
@anyong There is a tool called TTX that is part of fontTools that lets you convert fonts to/from XML, but the fontTools library is much more than that: it's a library for manipulating font data. Take a look at the fontTools [Snippets](https://github.com/fonttools/fonttools/tree/master/Snippets) to see examples of other things you can do with fontTools. (It can do much more than you'll see in the snippets, but at least that may help you get started.)
