### ISSUE TITLE
Some errors occurred when I tried to install 2.9.9a11

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#844]
I'm trying to install 2.9.9a11 via `pip install afdko==2.9.9a11`, but some errors occurred (2.9.1 is OK).

OS: Windows 10 1903 64 bit
Python: 3.7.3 32 bit
pip: 19.1.1

```
……

Building wheels for collected packages: afdko
  Building wheel for afdko (PEP 517) ... error
  ERROR: Complete output from command 'c:\users\digidea\appdata\local\programs\python\python37-32\python.exe' 'c:\users\digidea\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Digidea\AppData\Local\Temp\tmpztx17i93':
  ERROR: running bdist_wheel
  running build
  running build_py
  " "
  "Building detype1..."
  'msbuild' is not recognized as an internal or external command,
  operable program or batch file.
  The system cannot find the path specified.
  afdko: Error executing build command.
  ----------------------------------------
  ERROR: Failed building wheel for afdko
  Running setup.py clean for afdko
Failed to build afdko
ERROR: Could not build wheels for afdko which use PEP 517 and cannot be installed directly
```

**Comment by miguelsousa** [comment]
We dropped the win32 wheel.
Your system is trying to build the wheel from the source files but it doesn't look like the tooling for building the C-tools is available.

You have two options:
* A. Uninstall your 32-bit Python and install the 64-bit version.
* B. Install Visual Studio 2017.

If I were you I'd choose option A.

**Comment by LIXiangChen** [comment]
@miguelsousa If you didn't remind me that I didn't notice that the win32 wheel was dropped. I have successfully installed it now, thank you.
