### ISSUE TITLE
FutureWarning in ufotools.py

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#854]
```
ufotools.py:1964: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not outlineXML:
```
https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/ufotools.py#L1964

**Comment by frankrolf** [comment]
Ha, I just wanted to file this! Thanks!
Attached is a test UFO.
It has a single glyph, and overlaps removed (therefore contains a processed layer).
[test.ufo.zip](https://github.com/adobe-type-tools/afdko/files/3406510/test.ufo.zip)

**Comment by josh-hadley** [comment]
Side-effect of switching to fonttools.misc.plistlib (actually [`lxml`](https://github.com/lxml/lxml/blob/a1bed49d6ac0b8d720fd910dc67dea99e7f2ad89/src/lxml/etree.pyx#L1171) which plistlib uses under the hood).
