### ISSUE TITLE
Convert all docs to Markdown

### ISSUE THREAD

**Issue by josh-hadley** [adobe-type-tools/afdko#855]
/afdko/docs folder is currently a mix of Markdown, INDD/PDF, plain-text, and HTML. It would be useful to have it all in Markdown (and perhaps using a consistent document structure if possible).

- [ ] CommandLineHowTo
- [ ] FDK_Build_Notes
- [ ] MakeOTFUserGuide
- [ ] MSFontValidatorIssues
- [ ] WinWeights

**Comment by miguelsousa** [comment]
Also check if #93 can be addressed.

**Comment by josh-hadley** [comment]
> Also check if #93 can be addressed.

The file referenced there has been removed...I think it is now in https://github.com/adobe-type-tools/afdko/blob/develop/docs/FDK_Build_Notes.txt which is on the list...I will circle back with the author of #93 when I get around to it and see if he can contribute or at least review.
