### ISSUE TITLE
Malformed example in spec

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#88]
In the [OpenType Feature File Specification](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html), example 1 of section 6.h.ii. “Specifying Contextual Positioning with explicit lookup references” seems syntactically malformed:
```
lookup CNTXT_PAIR_POS {
     position T o -10;
     position T c by -12;
} CNTXT_PAIR_POS;
 
lookup CNTXT_MARK_TO_BASE {
     position base o 
     position base c 
} CNTXT_MARK_TO_BASE;
 
feature test {
     substitute T' lookup CNTXT_PAIR_POS [o c]' @ALL_MARKS' lookup CNTXT_MARK_TO_BASE;
} test;
```

Would it be possible to fix the specification, so that the example is syntactically correct?

**Comment by readroberts** [comment]
I just pushed the fix for this in v1.1.7 of the file.
