### ISSUE TITLE
How to delete "hotconv 1.00;Makeotfexe 2.5.0.1 " from Version information?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#885]
How to delete "hotconv 1.00;Makeotfexe 2.5.0.1 " from Version information? Only left the version number.

**Comment by josh-hadley** [comment]
The version string (nameid 5) is set with this string and it cannot be overridden as part of the `makeotf` process. You can use `ttx` or other font editing tool to modify the string as a post-AFDKO operation if you wish to remove the "hotconv ..." portion.
