### ISSUE TITLE
Turn CFF/CFF2 subroutinizer into Python package?

### ISSUE THREAD

**Issue by madig** [adobe-type-tools/afdko#894]
Are there plans for this? It would be nice to have one fast subroutinizer available to ufo2ft and easily installable like with psautohint.

Looking at https://github.com/adobe-type-tools/afdko/pull/882, it seems that the code for CFF and CFF2 is split? What files would be needed if we wanted to support both?

**Comment by miguelsousa** [comment]
Doesn't [compreffor](https://github.com/googlefonts/compreffor) fill that gap already?

**Comment by madig** [comment]
For CFF yes, but it doesn't work on CFF2. We were wondering if it was easier to use/adapt the CFF2 code of the AFDKO than to implement the same in compreffor.

**Comment by miguelsousa** [comment]
I think it'd be easier to extend compreffor than to setup something from scratch. That said, anyone is welcome to spinoff a new package on top of tx's code. We don't have any plans for doing such.

**Comment by cjchapman** [comment]
@madig It is not "split". Here's the full subroutinization code with both CFF and CFF2 support that is used in `tx`:
https://github.com/adobe-type-tools/afdko/blob/develop/c/public/lib/source/cffwrite/cffwrite_subr.c
Search on `CFW_WRITE_CFF2` to see the small CFF2-specific parts that didn't make it into the `makeotf` subroutinizer.

**Comment by madig** [comment]
Ah, so I misunderstood the comments in the PR. Thanks :)
