### ISSUE TITLE
Unable to install afdko through pip36 on FreeBSD 12.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-type-tools/afdko#907]
I got the following error output during the installation onto my VPS:

```
Building wheels for collected packages: afdko
  Building wheel for afdko (PEP 517) ... error
  ERROR: Complete output from command /usr/local/bin/python3.6 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp5j1494nk:
  ERROR: running bdist_wheel
  running build
  running build_py
  + pwd
  + curDir=/tmp/pip-install-8bnv9k6x/afdko/c
  + [ -z '' ]
  + ls -1 ./detype1/build/linux/gcc/build.sh ./makeotf/build/linux/gcc/build.sh ./mergefonts/build/linux/gcc/build.sh ./rotatefont/build/linux/gcc/build.sh ./sfntdiff/build/linux/gcc/build.sh ./sfntedit/build/linux/gcc/build.sh ./spot/build/linux/gcc/build.sh ./tx/build/linux/gcc/build.sh ./type1/build/linux/gcc/build.sh
  + buildAllList='./detype1/build/linux/gcc/build.sh
  ./makeotf/build/linux/gcc/build.sh
  ./mergefonts/build/linux/gcc/build.sh
  ./rotatefont/build/linux/gcc/build.sh
  ./sfntdiff/build/linux/gcc/build.sh
  ./sfntedit/build/linux/gcc/build.sh
  ./spot/build/linux/gcc/build.sh
  ./tx/build/linux/gcc/build.sh
  ./type1/build/linux/gcc/build.sh'
  + echo '***Running ./detype1/build/linux/gcc/build.sh'
  ***Running ./detype1/build/linux/gcc/build.sh
  + dirname ./detype1/build/linux/gcc/build.sh
  + newDir=./detype1/build/linux/gcc
  + basename ./detype1/build/linux/gcc/build.sh
  + shFile=build.sh
  + cd ./detype1/build/linux/gcc
  + sh build.sh ''
  + target=detype1
  + pwd
  + curdir=/tmp/pip-install-8bnv9k6x/afdko/c/detype1/build/linux/gcc
  + [ -z '' ]
  + cd release
  + make
  make: "../../../../../public/config/linux/gcc/../../../../../public/config/linux/gcc/gcc.mak" line 26: Missing dependency operator
  make: "../../../../../public/config/linux/gcc/../../../../../public/config/linux/gcc/gcc.mak" line 28: Need an operator
  make: Fatal errors encountered -- cannot continue
  make: stopped in /tmp/pip-install-8bnv9k6x/afdko/c/detype1/build/linux/gcc/release
  afdko: Unknown OS: FreeBSD
  afdko: Error executing build command.
  ----------------------------------------
  ERROR: Failed building wheel for afdko
  Running setup.py clean for afdko
Failed to build afdko
ERROR: Could not build wheels for afdko which use PEP 517 and cannot be installed directly

```

**Comment by miguelsousa** [comment]
We don't provide wheels FreeBSD, so they have to be built from source.
Is your environment configured for building the tools from source? You probably need to have some sort of developer tooling installed.

**Comment by khaledhosny** [comment]
Looks like the make files are written for GNU Make and FreeBSD is probably not using that.

**Comment by miguelsousa** [comment]
@ShikiSuen I've created a branch called **freebsd** that contains some initial support for FreeBSD. To try it out, checkout the branch and run the following commands:

    cd afdko/c
    sh buildallfreebsd.sh

If you look inside the directory `afdko/c/build_all` the **type1** tool should now be in there.

I'm not planning to do any further work on that branch. Feel free to take my changes, add the necessary files for building the remaining C tools (spot, tx, makeotfexe, ...) and send us a PR.

BTW, once you can build all the C tools you'll be able to build the wheel file by running

    pip install .

from the **afdko** directory.

**Comment by ShikiSuen** [comment]
> @ShikiSuen I've created a branch called **freebsd** that contains some initial support for FreeBSD. To try it out, checkout the branch and run the following commands:
> 
> ```
> cd afdko/c
> sh buildallfreebsd.sh
> ```
> 
> If you look inside the directory `afdko/c/build_all` the **type1** tool should now be in there.
> 
> I'm not planning to do any further work on that branch. Feel free to take my changes, add the necessary files for building the remaining C tools (spot, tx, makeotfexe, ...) and send us a PR.
> 
> BTW, once you can build all the C tools you'll be able to build the wheel file by running
> 
> ```
> pip install .
> ```
> 
> from the **afdko** directory.

Thanks for your warm assistance. I will see how far can I get ahead.

**Comment by miguelsousa** [comment]
Closing due to lack of action.
