### ISSUE TITLE
dump flex hint in two lines

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#915]
Since commit aaf8bfe, flex hints are dumped in two lines instead of one (`/* Dump glyph flex. */`). This makes it more difficult to parse that output because it breaks the one line one command structure. Could that be reverted?

**Comment by miguelsousa** [comment]
You'll need to provide an example or test case in order for us to understand exactly what changed and where. Referencing a 4-year old commit doesn't help.

**Comment by schriftgestalt** [comment]
thanks
