### ISSUE TITLE
[makeinstancesufo] fails when building single instance (-i option)

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#922]
I’ve been getting the following traceback whenever I try to replace a single instance:

```
[Masters] makeinstancesufo -i 0 -d test.designspace
ERROR:afdko.makeinstancesufo:ufoProcessor error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ufoProcessor/__init__.py", line 117, in build
    r = document.generateUFO(processRules=processRules)
  File "/usr/local/lib/python3.7/site-packages/ufoProcessor/__init__.py", line 310, in generateUFO
    font.save(path, self.ufoVersion)
  File "/usr/local/lib/python3.7/site-packages/defcon/objects/font.py", line 820, in save
    structure=structure,
  File "/usr/local/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 960, in __init__
    self.layerContents = OrderedDict(self._readLayerContents(validate))
  File "/usr/local/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 599, in _readLayerContents
    raise UFOLibError(error)
fontTools.ufoLib.errors.UFOLibError: A glyphset does not exist at glyphs.
ERROR:afdko.makeinstancesufo:A glyphset does not exist at glyphs.
```

Deleting the instance and completely re-building it works, as well as complete re-building of all instances.

I can prepare some test files if needed.

**Comment by frankrolf** [comment]
The promised test case is attached.

To reproduce the error:
- cd to the `Masters` directory
- run `makeinstancesufo -d test.designspace`
- run `makeinstancesufo -i 0 -d test.designspace`

The 2nd command will fail with the above traceback.
Re-running `makeinstancesufo -d test.designspace` will show no problems.


[makeinstancesufo test case.zip](https://github.com/adobe-type-tools/afdko/files/3527527/makeinstancesufo.test.case.zip)

**Comment by miguelsousa** [comment]
After a closer look, I believe this got fixed by 87a5bab7f1ed26abb958109a4e2188f662df4335 which was part of #899 (an effort to maximize `makeinstancesufo` coverage). I'm planning to make a dot release either tomorrow or Friday, which will include 2 weeks-worth of fixes and enhancements. I'll close this issue once the release is out.

**Comment by miguelsousa** [comment]
@frankrolf version 3.0.1 is out. Please check that it fixes this issue. Thanks.

**Comment by frankrolf** [comment]
3.0.1 works – thank you!
