### ISSUE TITLE
Incomplete GNU/Linux build instructions at Read_Me_First.html

### ISSUE THREAD

**Issue by felipesanches** [adobe-type-tools/afdko#93]
(even though we have some build instructions at
https://raw.githubusercontent.com/adobe-type-tools/afdko/master/afdko/FDK%20Build%20Notes.txt ...)

The file https://github.com/adobe-type-tools/afdko/blob/master/afdko/Read_Me_First.html is misleading because it does not mention that one needs to run the afdko/afdko/Tools/Programs/BuildAllLinux.sh script. While the script filemane is quite obvious, it is really not obvious for the newcomer that this file must be run, since it is not a top-level file, so it may not be easily found at first. So the documentation should explicitely provide instructions about it.

It also says nothing about the fact that it needs gcc 32bit packages because it is currently impossible to build stable 64bit adfko tools (see https://github.com/adobe-type-tools/afdko/issues/57)

**Comment by davelab6** [comment]
Will @adobe-type-tools accept a PR that adjusts the Read_Me_First.html to (a) include such details and (b) switch to markdown? :)

**Comment by readroberts** [comment]
The "Read Me First" file, as noted in the AFDKO home page, is meant for users who are installing a fully configured AFDKO directory tree. It certainly not should not contain instructions for building the FDK from sources, as most of the AFDKO users already find using command-line tools alarmingly advanced. I did update the "Read Me First" file to indicate that developers should look at the "Build Notes" file. I also updated the latter to note that when building on 64 bit Linux, you need to install the 32-bit support libs. This file actually did already mention using BuildAllLinux.sh, in section 2.1.

I am reluctant to improve the sophistication of the notes, as the AFKO tools have been around for over 30 years, and formatting workflows tend to last only a  few years before something better comes along. When a set of information has some degree of complexity, the value of readability to the developer is certainly worth the maintenance effort, but when it is just a page or two for a small audience, I favor plain text, or at most simple html for the long term.

**Comment by felipesanches** [comment]
Yeah, I noticed later that it mentioned BuildAllLinux.sh in section 2.1 of the other document. But I was reading "Read Me First" First. :-)

**Comment by davelab6** [comment]
In terms of content, I think at a higher level, the current documentation
was a bit confusing for Felipe, and could be improved.

I agree that keeping the documentation simple is good, but I think Markdown
is very close to text plain and has the benefit that it can easily generate
richer html if required :)

**Comment by josh-hadley** [comment]
@felipesanches: I'm doing some cleanup of open AFDKO issues and came across this one that I don't think is relevant anymore, so I'm closing it. If it is still a problem, please re-open and comment as to possible ways we could solve it.

**Comment by felipesanches** [comment]
well... the URL mentioned in the initial issue does not even work anymore... https://github.com/adobe-type-tools/afdko/blob/master/afdko/Read_Me_First.html

Did it move somewhere else?

**Comment by josh-hadley** [comment]
> Did it move somewhere else?

Yes, I believe the content from that is now in https://github.com/adobe-type-tools/afdko/blob/develop/docs/FDK_Build_Notes.md or other notes linked from https://github.com/adobe-type-tools/afdko/blob/develop/docs/README.md which have addressed both concerns (unclear build instructions for Linux as well as conversion to Markdown), and is why I believe this issue is no longer relevant.

**Comment by felipesanches** [comment]
cool, thanks! I think it is all good now ;-)
