### ISSUE TITLE
[spec] Example table GDEF gives two caret positions for glyph f_i

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#94]
[Section 9.b](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.b) of the OpenType Feature File specification gives an example for `table GDEF`. Currently, it contains the following statement:  
```
LigatureCaretByPos f_i 400 380;
```

However, for an `f_i` glyph, there should probably be just a single caret position. Should the example be changed to some glyph with three components, perhaps f_f_l?

**Comment by behdad** [comment]
Also, the caret positions are supposed to be in increasing coordinate order...  Maybe just drop the 400?

**Comment by readroberts** [comment]
Fixed in feature file spec 1.19. Also added a note that a glyph may have only one LigatureCaret statement.
