### ISSUE TITLE
How to set the fsSelection in the OS/2 table?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#944]
How to set the fsSelection in the OS/2 table? There is no description in OpenTypeFeatureFileSpecification file.
![image](https://user-images.githubusercontent.com/5868202/64031369-d5819a00-cb7a-11e9-9077-d1a8747fb062.png)

The following error occurred at compile time:
![image](https://user-images.githubusercontent.com/5868202/64031514-24c7ca80-cb7b-11e9-9edc-cc6b73feae80.png)

![image](https://user-images.githubusercontent.com/5868202/64031539-35784080-cb7b-11e9-8be3-1f717179848c.png)

**Comment by connordavenport** [comment]
You can use a fontinfo file to set the fsselection. e.g. 
```
IsBoldStyle false
IsItalicStyle false
PreferOS/2TypoMetrics false
IsOS/2WidthWeigthSlopeOnly true
IsOS/2OBLIQUE false
```

**Comment by mhjy** [comment]
Can you explain it in more detail? Thanks.

**Comment by connordavenport** [comment]
Sorry about that, you can use a file called `fontinfo` in your font level folder using the ^above content (adjusting for the font style). [Here is a more detailed description](https://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.pdf#page=11)

**Comment by mhjy** [comment]
Thanks.
