### ISSUE TITLE
[makeotfexe] Feature files causes huge memory consumption

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#965]
While porting feaLib tests to makeotfexe, I came accross a seemingly innocent file that causes makeotfexe to consume huge amount of memory (not sure if it is leaking memory or not), it basically consumed all available memory. I tried to debug it, but it is rather difficult when it causes the OS to start killing applications to free memory.

The [file](https://raw.githubusercontent.com/fonttools/fonttools/master/Tests/feaLib/data/bug1307.fea) (from https://github.com/fonttools/fonttools/pull/1307).

**Comment by benkiel** [comment]
Perhaps because of lookups being used before language declarations? I don't think that's valid FDK syntax, but I may be wrong

**Comment by cjchapman** [comment]
@khaledhosny I'll look into it. Thanks.

**Comment by cjchapman** [comment]
@khaledhosny Looks like it's stuck in an infinite loop here:
https://github.com/adobe-type-tools/afdko/blob/ddb273ac31d10766a6fe8ea0b230593198a42351/c/makeotf/makeotf_lib/source/hotconv/feat.c#L4221-L4224
...because something in the `callLkp()` call stack keeps causing `h->DFLTLkps.cnt` to increment.

**Comment by cjchapman** [comment]
...this, specifically:
https://github.com/adobe-type-tools/afdko/blob/ddb273ac31d10766a6fe8ea0b230593198a42351/c/makeotf/makeotf_lib/source/hotconv/feat.c#L3029-L3032

**Comment by cjchapman** [comment]
@khaledhosny I have to leave now due to family commitments. If you want to take it from here, great, if not, I'll plan on picking this back up on Monday.

**Comment by khaledhosny** [comment]
I’m not having much luck with debugging. This is the smallest file to trigger the infinite loop.

```fea
languagesystem DFLT dflt;
lookup b {
    sub b by B;
} b;
lookup c {
    sub c by C;
} c;
lookup d {
    sub d by D;
} d;
feature liga {
    lookup b;
    script DFLT;
        lookup c;
        language dflt;
            lookup d;
} liga;
```

**Comment by cjchapman** [comment]
@khaledhosny OK, no worries, I'll plan on working on this when I get back to the office on Monday.
