### ISSUE TITLE
[spec] Outdated statements about glyph classes

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#970]
From [2.g.i](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2gi-ranges):

> A range of glyphs is denoted by a hyphen:
> ```
> [<firstGlyph> - <lastGlyph>]
> ```
> Spaces around the hyphen are not required since hyphens are not permitted in feature file glyph names. For example:
> ```
> [\0-\31]
> [A-Z]
> ```

But I believe this is no longer the case since hyphen in glyph names are permitted now.

**Comment by iterumllc** [comment]
I updated this language.
