### ISSUE TITLE
otf2ttf: support TTC input

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#986]
Make sure: one CFF to one `loca-glyf` pair.

**Comment by miguelsousa** [comment]
TTC input is already supported. You just need to use the `--face-index` option.

**Comment by be5invis** [comment]
@miguelsousa 
Currently it only converts _one_ subfont in TTC. What I wanted is to convert _every subfont_ and keeping glyph set shareness.

**Comment by miguelsousa** [comment]
Understood.

I think you have two options:
* Write a shell or python script that leverages **otf2ttf** and **otf2otc**, or
* Submit a pull request that enhances the current functionality of **otf2ttf**.
