### ISSUE TITLE
[makeotfexe] Crash with contextual pos rule

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#993]
The following (which I’m not sure is valid) crashes makeotfexe:
```fea
markClass [acute grave] <anchor 150 -10> @TOP_MARKS;                            
                                                                                
lookup mark {                                                                   
  position base [a e o u]' <anchor 250 450> mark @TOP_MARKS;                    
} mark;
```

**Comment by readroberts** [comment]
Yes, this is valid, and should not crash. It doesn't need to be contextual, but a developer may want to do this to keep the statement in the same lookup as other contextual rules.

**Comment by typoman** [comment]
I took the syntax example from [here (test files)](tests/makeotfexe_data/input/spec/6d-3.fea) but it crashes makeotf, is this invalid?
```
	lookup MARK_TOP_CTX {
	    pos base B A' D <anchor 300 900> mark @mark_top;
	} MARK_TOP_CTX;
```
Same rule doens't crash if there is no context. I've also tried the example from the docs, it also crashes makeotf with no clue on what went wrong. Full feauture for test:
```
languagesystem DFLT dflt;
languagesystem latn dflt;

markClass circumflex <anchor 271 514> @mark_top;
markClass caron <anchor 271 534> @mark_top;

feature mark {
	lookup MARK_TOP {
		pos base A <anchor 289 571> mark @mark_top;
	} MARK_TOP;

	lookup MARK_TOP_CTX {
	    pos base B A' D <anchor 300 900> mark @mark_top;
	} MARK_TOP_CTX;
} mark;

@BASE = [A B C D];
@MARK = [circumflex caron];

table GDEF {
    GlyphClassDef @BASE, , @MARK, ;
} GDEF;
```

**Comment by typoman** [comment]
I just realized the mark class should be marked wiht `'` not the base. There is a mistake in the docs [here](https://github.com/adobe-type-tools/afdko/blob/develop/docs/OpenTypeFeatureFileSpecification.md#L2467). This example is not compiling but if the mark class was marked, it compiles.
