### ISSUE TITLE
[makeotfexe] Is multiple master support usable?

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#995]
There seems to be some support for multiple master fonts in makeofexe but at first glance it seems to predate OpenType variable fonts. So I’m wondering if this support of any use today and, if yes, how to test it?

**Comment by readroberts** [comment]
This is code is not useful. It was written to support MM OTF fonts before Adobe MM support was killed. It supported only the Adobe MM paradigm, which is too limited for variable fonts. In particular, the supported syntax didn’t allow for sparse sources, or identifying for which region font a value was meant. This code does not need tests, and it would be good to remove the code altogether.
